### ISSUE TITLE
Card.io app token?

### ISSUE THREAD

**Issue by gsabater** [paypal/PayPal-Cordova-Plugin#10]
Hi there,
I'm using your plugin to accept paypal payments through my app, but my app can't scan any of the credit cards that i have.

By looking over the internet i've found that one app token must be used in card.io scans, so i'm wondering if we must provide such token somewhere in your plugin or if its not necessary.
If yes, how can i provide it? I've not found any reference in any of the .js files of your plugin.

Thanks

**Comment by riteish08** [comment]
Hi,

Great Plugin..!!!

How to disable "card.io" feature from this plugin?

Tried removing that plugin alone but its showing following error:

Error: The plugin 'card.io.cordova.mobilesdk' is required by (com.paypal.cordova.mobilesdk), skipping uninstallation. (try --force if trying to update)

Is it safe to remove by this method?
