### ISSUE TITLE
I have problem in android paypal integration

### ISSUE THREAD

**Issue by nitinsurani** [paypal/PayPal-Cordova-Plugin#101]
Hi,
I have problem in paypal plugin in android. I have successfully installed plugin and paypal UI is rendering. But when i fill credit cart screen and then click on "Charge Card" then no any process.... and i am redirect to paypal main screen. I have checked all my logs but nothing.
I am using "MyCordovaShop-master" fresh demo with installed 2 plugin. 
1)Console plugin
2)Paypal plugin
Can you help me to solve this?
 
Android version is: 4.0.2
Cordova version is: 5.1.1

**Comment by bhaskar-karmick** [comment]
Hi,
I also facing the same issue as mentioned by @nitinsurani.
Please suggest how this will be fixed
Thanks

**Comment by jaypatel512** [comment]
Hey @nitinsurani ! @bhaskar-karmick ! 

There was a bug we found recently in [Android SDK #186](https://github.com/paypal/PayPal-Android-SDK/issues/186). This caused the credit cards to not work, and default back to Main screen. We recently released the plugin with updated SDK, with the fix. Can you please make sure you have [v3.1.12 or higher](https://github.com/paypal/PayPal-Cordova-Plugin/releases/tag/v3.1.12) of this plugin. That should fix your issue. 

Please re-open the bug if that doesnt solve it. :)

**Comment by nitinsurani** [comment]
Hi Jay,

Thank you so much.. This 3.1.12 version is working fine now.. Thanks a
lot.. :)

On Thu, Aug 20, 2015 at 9:10 PM, Jay <notifications@github.com> wrote:

> Hey @nitinsurani <https://github.com/nitinsurani> ! @bhaskar-karmick
> <https://github.com/bhaskar-karmick> !
>
> There was a bug we found recently in Android SDK #186
> <https://github.com/paypal/PayPal-Android-SDK/issues/186>. This caused
> the credit cards to not work, and default back to Main screen. We recently
> released the plugin with updated SDK, with the fix. Can you please make
> sure you have v3.1.12 or higher
> <https://github.com/paypal/PayPal-Cordova-Plugin/releases/tag/v3.1.12> of
> this plugin. That should fix your issue.
>
> Please re-open the bug if that doesnt solve it. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paypal/PayPal-Cordova-Plugin/issues/101#issuecomment-133055169>
> .
>



-- 


[image: logo]
*Nitin Surani*
*Skype*: surani.nitin
* Mobile*: +918306066606
*oDesk*: Nitin Surani
<https://www.odesk.com/o/profiles/users/_~01a474fd07b3e148a8/>
surani.nitin@gmail.com | http://planexw <http://planexweb.com>eb.com
<http://planexweb.com>
We are developing mobile application in phonegap(iOs/Android) with
universal device support. We are delivering best solution to our clients
for Phonegap development, Wordpress development, Opencart development,
Codeigniter development, Joomla development, eCommerce development,
Shopping cart development, Web services development, HTML5 responsive web
designs/application designs. Website Redesign and application Redesign.
------------------------------------------------------------------------------------------------
<http://www.facebook.com/nitin.surani>
<http://in.linkedin.com/pub/nitin-surani/55/a05/140>
<http://twitter.com/nitinsurani> [image:
https://plus.google.com/114980194066923225365/posts]
<https://plus.google.com/114980194066923225365/posts>
<http://in.linkedin.com/pub/nitin-surani/55/a05/140>

**Comment by jaypatel512** [comment]
Cool ! Great to know :+1: Happy Coding
