### ISSUE TITLE
Confict with CardIo plugin and Paypal payment plugin

### ISSUE THREAD

**Issue by zefrench** [paypal/PayPal-Cordova-Plugin#103]
I'm using scan card (cardIO) plugin on my app and I have some call to the scan within my index.js in order to scan card that will not be used with a paypal account and it works like a charm.

BUT
I need to install the paypal plugin but as paypal plugin comes now with carIo library I get duplicate error : duplicate symbol _CardIOCurrentScanningOrientatio when I run the cordova build ios and.. the build failed.

I tried to remove the cardIO plugin but I get error on my app : Can't find variable: CardIO

Is it a way to use the both plugin ?

If you have any idea, tell me..

**Comment by tomwhipple** [comment]
This problem stems from the fact that the PayPal iOS SDK includes card.io. You'll want to find the card.io static library (.a file) and remove it from your project. You don't want to remove the card.io Cordova plugin since it has all of the JS wrappers that are required to access it directly.
