### ISSUE TITLE
Xcode 7 error on building app

### ISSUE THREAD

**Issue by noldotar** [paypal/PayPal-Cordova-Plugin#104]
Hi, I'm trying to building the app with Xcode 7, but it breaks with this error:

> linker command failed with exit code 1 (use -v to see invocation)
> /Users/Matteo/Developer/MyAPP/app/platforms/ios/MyAPP/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(libCardIO.a-arm64-master.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

``` error
Ld /Users/Matteo/Library/Developer/Xcode/DerivedData/MyAPP-dmppldvmfylhqwehjmhdkgauvrrh/Build/Products/Debug-iphoneos/MyAPP.app/MyAPP normal arm64
    cd /Users/Matteo/Developer/MyAPP/app/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -L/Users/Matteo/Library/Developer/Xcode/DerivedData/MyAPP-dmppldvmfylhqwehjmhdkgauvrrh/Build/Products/Debug-iphoneos -L/Users/Matteo/Developer/MyAPP/app/platforms/ios/MyAPP/Plugins/com.paypal.cordova.mobilesdk -F/Users/Matteo/Library/Developer/Xcode/DerivedData/MyAPP-dmppldvmfylhqwehjmhdkgauvrrh/Build/Products/Debug-iphoneos -filelist /Users/Matteo/Library/Developer/Xcode/DerivedData/MyAPP-dmppldvmfylhqwehjmhdkgauvrrh/Build/Intermediates/MyAPP.build/Debug-iphoneos/MyAPP.build/Objects-normal/arm64/MyAPP.LinkFileList -miphoneos-version-min=6.0 -dead_strip -fembed-bitcode-marker -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -framework AssetsLibrary /Users/Matteo/Library/Developer/Xcode/DerivedData/MyAPP-dmppldvmfylhqwehjmhdkgauvrrh/Build/Products/Debug-iphoneos/libCordova.a -framework CoreGraphics -framework MobileCoreServices -framework CoreLocation -lPayPalMobile -framework Accelerate -framework AudioToolbox -framework AVFoundation -framework CFNetwork -weak_framework CoreMedia -framework CoreVideo -framework MessageUI -framework OpenGLES -framework Security -framework SafariServices -framework SystemConfiguration -framework QuartzCore -framework UIKit -lc++ -lPayPalMobile -Xlinker -dependency_info -Xlinker /Users/Matteo/Library/Developer/Xcode/DerivedData/MyAPP-dmppldvmfylhqwehjmhdkgauvrrh/Build/Intermediates/MyAPP.build/Debug-iphoneos/MyAPP.build/Objects-normal/arm64/MyAPP_dependency_info.dat -o /Users/Matteo/Library/Developer/Xcode/DerivedData/MyAPP-dmppldvmfylhqwehjmhdkgauvrrh/Build/Products/Debug-iphoneos/MyAPP.app/MyAPP

ld: '/Users/Matteo/Developer/MyAPP/app/platforms/ios/MyAPP/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(libCardIO.a-arm64-master.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

My Cordova info:
Node version: v4.1.0
Cordova version: 5.3.1
Installed platforms: android 4.1.1, ios 3.9.1

Project Plugins:
* com.paypal.cordova.mobilesdk 3.1.13 "PayPalMobile"
* cordova-plugin-device 1.0.1 "Device"
* cordova-plugin-dialogs 1.1.1 "Notification"
* cordova-plugin-file 3.0.0 "File"
* cordova-plugin-geolocation 1.0.1 "Geolocation"
* cordova-plugin-media 1.0.1 "Media"
* cordova-plugin-splashscreen 2.1.0 "Splashscreen"
* cordova-plugin-whitelist 1.1.0 "Whitelist"
* de.appplant.cordova.plugin.hidden-statusbar-overlay 1.2.0 "HiddenStatusbarOverlay"
* phonegap-plugin-push 1.3.0 "PushPlugin"

iOS platform:
Xcode 7.0
Build version 7A220

Any suggest?
Thanks

**Comment by bluk** [comment]
Hi, you will need to disable Bitcode in your Xcode IDE. If you search under your target's Build Settings and select "All", you can search for Bitcode enabled. Currently the card.io library is not Bitcode enabled  (due to some low level code) so the PayPal SDK is not entirely Bitcode enabled. Apple is accepting non-Bitcode enabled applications as everyone transitions. You can track some of the card.io Bitcode progress in card-io/card.io-iOS-SDK#119 .

**Comment by noldotar** [comment]
Great! It works!!!
