### ISSUE TITLE
Unable to build app. Mach-O Linker Error

### ISSUE THREAD

**Issue by tomandhisjones** [paypal/PayPal-Cordova-Plugin#105]
I'm trying to build an ionic app with your plugin, but each time I try to build, I get a Linker error, and the build fails. I've added and removed platforms and plugins in various orders, to no success. It says I have duplicate symbols for architecture x86_64: 

Ld /Users/tfree2/Library/Developer/Xcode/DerivedData/Ninja_Scan-agrdvbengrwwmebkluhamofsddea/Build/Products/Debug-iphonesimulator/Ninja\ Scan.app/Ninja\ Scan normal x86_64
    cd /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios
    export IPHONEOS_DEPLOYMENT_TARGET=6.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -L/Users/tfree2/Library/Developer/Xcode/DerivedData/Ninja_Scan-agrdvbengrwwmebkluhamofsddea/Build/Products/Debug-iphonesimulator -L/Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja\ Scan/Plugins/com.paypal.cordova.mobilesdk -L/Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja\ Scan/Plugins/io.jxcore.node -F/Users/tfree2/Library/Developer/Xcode/DerivedData/Ninja_Scan-agrdvbengrwwmebkluhamofsddea/Build/Products/Debug-iphonesimulator -filelist /Users/tfree2/Library/Developer/Xcode/DerivedData/Ninja_Scan-agrdvbengrwwmebkluhamofsddea/Build/Intermediates/Ninja\ Scan.build/Debug-iphonesimulator/Ninja\ Scan.build/Objects-normal/x86_64/Ninja\ Scan.LinkFileList -Xlinker -objc_abi_version -Xlinker 2 -weak_framework CoreFoundation -weak_framework UIKit -weak_framework AVFoundation -weak_framework CoreMedia -weak-lSystem -ObjC -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=6.0 -framework AssetsLibrary /Users/tfree2/Library/Developer/Xcode/DerivedData/Ninja_Scan-agrdvbengrwwmebkluhamofsddea/Build/Products/Debug-iphonesimulator/libCordova.a -framework CoreGraphics -framework MobileCoreServices -lPayPalMobile -framework Accelerate -framework AudioToolbox -framework AVFoundation -framework CFNetwork -weak_framework CoreLocation -weak_framework CoreMedia -framework CoreVideo -framework MessageUI -framework OpenGLES -framework Security -framework SafariServices -framework SystemConfiguration -framework QuartzCore -framework UIKit -lc++ -lPayPalMobile -lcares -lchrome_zlib -lhttp_parser -ljx -lmozjs -lopenssl -lsqlite3 -luv -lleveldb -lleveldown -lsnappy -lstdc++.6.0.9 -framework Foundation -liconv -framework CoreImage -Xlinker -dependency_info -Xlinker /Users/tfree2/Library/Developer/Xcode/DerivedData/Ninja_Scan-agrdvbengrwwmebkluhamofsddea/Build/Intermediates/Ninja\ Scan.build/Debug-iphonesimulator/Ninja\ Scan.build/Objects-normal/x86_64/Ninja\ Scan_dependency_info.dat -o /Users/tfree2/Library/Developer/Xcode/DerivedData/Ninja_Scan-agrdvbengrwwmebkluhamofsddea/Build/Products/Debug-iphonesimulator/Ninja\ Scan.app/Ninja\ Scan

duplicate symbol _llvm.cmdline in:
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskDeviceData.o)
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskUtility.o)
duplicate symbol _llvm.embedded.module in:
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskDeviceData.o)
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskUtility.o)
duplicate symbol _llvm.cmdline in:
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskDeviceData.o)
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskConfiguration.o)
duplicate symbol _llvm.embedded.module in:
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskDeviceData.o)
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskConfiguration.o)
duplicate symbol _llvm.cmdline in:
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskDeviceData.o)
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskLinkerID.o)
duplicate symbol _llvm.embedded.module in:
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskDeviceData.o)
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskLinkerID.o)
duplicate symbol _llvm.cmdline in:
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskDeviceData.o)
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskComponent.o)
duplicate symbol _llvm.embedded.module in:
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskDeviceData.o)
    /Applications/MAMP/htdocs/ninja-scan/ninja-scan/platforms/ios/Ninja Scan/Plugins/com.paypal.cordova.mobilesdk/libPayPalMobile.a(PPRiskComponent.o)
ld: 8 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I've pulled down the demo app, and was able to successfully build and run with that, but I'm unsure what could be causing the problem with the app I am building. If I remove the paypal plugin, everything builds fine.

**Comment by bluk** [comment]
The latest PayPal-Cordova Plugin requires Xcode 7. The library is partially Bitcode enabled which Xcode 6.4 does not work well with. An alternative is to try to use the https://github.com/paypal/PayPal-iOS-SDK/releases/tag/2.11.5 libraries temporarily which should be built without any embedded Bitcode.

**Comment by tomandhisjones** [comment]
I originally tried this on Xcode 7 as well, with the same results. I downgraded Xcode to see if it would resolve the problem, and it didn't. I didn't have any problem building the sample app in Xcode 6.4

**Comment by tomwhipple** [comment]
I believe you still need to disable bitcode for XCode 7. We're tracking support for bitcode in https://github.com/paypal/PayPal-iOS-SDK/issues/284.

**Comment by pbojinov** [comment]
@tomandhisjones I had this same problem as well: `clang: error: linker command failed with exit code 1 (use -v to see invocation)`.

I was able to successfully build and archive in Xcode 7.0 (7A220) by setting `Enable Bitcode` to `No` in the target `Build Settings`.

1. Go to Build Settings
2. Search for "bitcode".
3. Set Enable Bitcode to No

![image](https://cloud.githubusercontent.com/assets/709616/10093950/a16fb9c8-630e-11e5-9add-815a896dd7f1.png)

For iOS apps, bitcode is the default, but optional. If you provide bitcode, all apps and frameworks in the app bundle need to include bitcode.

**Comment by tomandhisjones** [comment]
@pbojinov I did try that, and was able to successful build to my device, but wasn't able to build for it to run in the simulator. Did it work in the simulator for you?

**Comment by pbojinov** [comment]
It worked in the simulator for me. 

Interestingly enough it didn't complain about the bitcode when running in the simulator but it came up when trying to build for device.

**Comment by bluk** [comment]
@pbojinov Bitcode is normally only "enabled" when archiving your application for distribution or testing on a device.

@tomandhisjones I would also try to see if your Command Line Tools are updated for Xcode 7 and your toolchain is selected in the command line via `xcode-select`.

**Comment by bluk** [comment]
The Cordova plugin 3.1.16 has been updated with the latest PayPal iOS SDK 2.12.5 which contains various fixes. It has enabled Bitcode (which is where the increase in library size is coming from). Please reopen if this is still an issue.
