### ISSUE TITLE
`Checking this device...` always hangs.

### ISSUE THREAD

**Issue by markharding** [paypal/PayPal-Cordova-Plugin#106]
Since iOS 9 I'm not able to get past 'checking this device...' - it then says 'There was a problem communicating with the PayPal services. Please try again' after about a minute. Multiple devices. Unfortunately there are no error outputs are all. This was working on our production application until we upgraded to iOS 9 today. 

I think this could actually go deeper and be an issue with the PayPal SDK its self. 

Android is working fine with the same config.

```
	PayPalMobile.init(clientIDs, function() {

				var config = {
					defaultUserEmail: null,
					defaultUserPhoneCountryCode: null,
					defaultUserPhoneNumber: null,
					merchantName: "Minds",
					merchantPrivacyPolicyURL: null,
					merchantUserAgreementURL: null,
					acceptCreditCards: true,
					payPalShippingAddressOption: 0,
					rememberUser: true,
					languageOrLocale: null,
					disableBlurWhenBackgrounding: false,
					presentingInPopover: false,
					forceDefaultsInSandbox: false,
					sandboxUserPassword: null,
					sandboxUserPin: null
				};

				var payment = {
					subtotal: String($scope.data.usd),
					shipping: "0.00",
					tax: "0.00",
					amount: String($scope.data.usd),
					currency: "USD",
					shortDescription: "Points purchase",
					intent: "Auth"
				};
				PayPalMobile.prepareToRender("PayPalEnvironmentProduction", config, function(e) {
					// single payment
					PayPalMobile.renderSinglePaymentUI(payment, function(success) {
						$ionicLoading.show({
							template: '<p>Applying points...</p>'
						});
						console.log('SUCCESS!!');
						console.log(success);
						Client.post('api/v1/wallet/paypal/confirm', {
							id: success.response.authorization_id,
							points: $scope.data.points
						}, function(success) {
							console.log(success);
							$ionicLoading.hide();
							if (success.status == 'success') {
								$state.go('tab.newsfeed-wallet');
							}
						}, function(error) {
							$ionicLoading.hide();
						});
					}, function(canceled) {
						//	$scope.changeStep('quote');
						console.log('canceled paypal');
					});
				});
			});
```
--
(Possibly related to #82)

**Comment by tomwhipple** [comment]
Could you confirm which version of the Cordova plugin you are using?

If you were using an older version but building against iOS9, you could be hitting the App Transport Security (ATS) checks. As part of the latest round of updates, were able to consolidate communication to a single API endpoint that is compliant. However, older versions may be talking to endpoints that are not yet up to that standard.

**Comment by markharding** [comment]
I'm using using the master branch from here. Also we have the new transport security config set to allow all. Also there is no error log at all (security would have thrown a domain error?).

**Comment by tomwhipple** [comment]
True, there should be a log message.

We will investigate.

**Comment by ds8k** [comment]
Having this issue as well on iOS 9 with the latest version. Sandbox loads up fine however.

**Comment by tomwhipple** [comment]
We have been able to reproduce this and are working on a solution.

**Comment by noldotar** [comment]
Same here:
Node version: v4.1.0
Cordova version: 5.3.1
iOS platform: Xcode 7.0 Build version 7A220
Plugins:
com.paypal.cordova.mobilesdk 3.1.13 "PayPalMobile"
cordova-plugin-actionsheet 2.0.1 "ActionSheet"
cordova-plugin-device 1.0.1 "Device"
cordova-plugin-dialogs 1.1.1 "Notification"
cordova-plugin-file 3.0.0 "File"
cordova-plugin-geolocation 1.0.1 "Geolocation"
cordova-plugin-media 1.0.1 "Media"
cordova-plugin-splashscreen 2.1.0 "Splashscreen"
cordova-plugin-whitelist 1.1.0 "Whitelist"
ionic-plugin-keyboard 1.0.7 "Keyboard"
phonegap-plugin-push 1.3.0 "PushPlugin"

**Comment by walfro** [comment]
+1 Same here

Cordova CLI: 5.3.1
Ionic Version: 1.0.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0 
ios-sim version: 3.1.1 
OS: Mac OS X Yosemite
Node Version: v0.12.3
Xcode version: Xcode 7.0 Build version 7A220

**Comment by noldotar** [comment]
Hi, could we have a timing? Sorry but it's urgent for me...

**Comment by avidas** [comment]
Hey, we discovered that the issue came up in the cordova sdk after some endpoints were updated to be compliant to Apple's App Transport Security. While we are still looking at root cause for the issue, reverting to the previous version, 3.1.12, should work

**Comment by noldotar** [comment]
Yeah! I confirm that 3.1.12 works

**Comment by igordeoliveirasa** [comment]
Oh, I'd like to know about it too.

**Comment by bluk** [comment]
The Cordova plugin 3.1.16 has been updated with the latest PayPal iOS SDK 2.12.5 which contains various fixes. It should have fixed the `Checking this device...` issue on production and enabled Bitcode (which is where the increase in library size is coming from).
