### ISSUE TITLE
Note getting dynamic values for amount 

### ISSUE THREAD

**Issue by dilipwk** [paypal/PayPal-Cordova-Plugin#107]
```
  createPayment: function() {
    var paymentDetails = new PayPalPaymentDetails("1.00", "0.00", "0.00");
    var payment = new PayPalPayment("1.00", "USD", "Dilip Sauce", "Sale",
      paymentDetails);
    return payment;
  }
```
I couldn't make payment value ("1.00") dynamic 

Am working in Ionic angularjs

**Comment by Vincenttbk** [comment]
createPayment: function(value) {
var paymentDetails = new PayPalPaymentDetails(value, "0.00", "0.00");
var payment = new PayPalPayment(value, "USD", "Dilip Sauce", "Sale",
paymentDetails);
return payment;
}

**Comment by dilipwk** [comment]
buyNowBtn.onclick = function(e) {
      var fare=document.getElementById("fare");
      PayPalMobile.renderSinglePaymentUI(app.createPayment(fare), app.onSuccesfulPayment,
        app.onUserCanceled);
    };


  createPayment: function(val) {
    var paymentDetails = new PayPalPaymentDetails(val, "0.00", "0.00");
    var payment = new PayPalPayment(val, "USD", "Dilip Sauce", "Sale",
      paymentDetails);
    return payment;
  },

Is this correct ? where I declared dynamic value in a html file 
<input type="hidden" value="123" id="fare">

**Comment by doditsolutions** [comment]
We too getting same issues.

Can u please guide us how to get dynamic values in it. we have all value in scope. also in before index.html. so hot to get into index.html pages also from there to this js file.. any sample will be helpfull.

Thanks in advance.

**Comment by ppmtscory** [comment]
Closing as there's no issue with the plugin itself.
