### ISSUE TITLE
Phonegap build version lagging

### ISSUE THREAD

**Issue by sanctus671** [paypal/PayPal-Cordova-Plugin#110]
I'm having issues getting the app on the Apple store because it is crashing on iOS9 when trying to start the Paypal plugin. I looked at the version on Phonegap build, and it saying the latest version was uploaded feb 13, 2015. Since then there have been a few bug fixes for iOS. I'm not sure if it auto-deploys or not, but I'm hoping this is the reason for the crashes I'm getting.

**Comment by bluk** [comment]
The Cordova plugin has been updated with the latest PayPal iOS SDK 2.12.5 which contains various fixes. Please reopen or open a new issue for any specific issues.
