### ISSUE TITLE
PayPal SDK not working in IOS Production(Live) but for Sandbox its working fine

### ISSUE THREAD

**Issue by msssakshisharma** [paypal/PayPal-Cordova-Plugin#112]
I have integrate this paypal sdk in android and IOS.
In android its working fine for both Production and sandbox but in case of IOS its only work for Sandbox, failed for Production(LIVE) 

Its able to redirect paypal but only show loader.

please help 
Thanks

**Comment by ppmtscory** [comment]
@msssakshisharma you are most likely being affected by the same thing that's described in #111.  Please keep an eye on that issue for resolution.
