### ISSUE TITLE
Issue with cordova platform add android

### ISSUE THREAD

**Issue by madjido** [paypal/PayPal-Cordova-Plugin#113]
Hi,
I'm trying to create the project "MyShop" just as it is described in the paypal-cordova-plugin page, when i add android platform then i ge this error : 

Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.mycompany.myshop
	Name: MyShop
	Activity: MainActivity
	Android target: android-22
Copying template files...
Android project created with cordova-android@4.1.1
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for android
Installing "com.paypal.cordova.mobilesdk" for android
Error during processing of action! Attempting to revert...
Failed to install 'com.paypal.cordova.mobilesdk':Error: Uh oh!
"/home/cours/lab/MyShop/plugins/com.paypal.cordova.mobilesdk/src/android/libs/arm64_v8a" not found!
    at Object.module.exports.common.copyFile (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:38:40)
....

I can't figure it out, any idea will be greatly appreciated,
Thanks

**Comment by ds8k** [comment]
Same issue here

**Comment by mayurloved** [comment]
Same Issue too :(

**Comment by miche-atucha** [comment]
Me too! for the 3.1.16 version, and the plugin is in the project after the install crash

**Comment by bluk** [comment]
Does this happen for only the latest version? I think this is because the latest Android card.io version has support for more architectures.

**Comment by miche-atucha** [comment]
my project only have iOS platform, and still happen

**Comment by mayurloved** [comment]
I am Still awaiting for the Solution :(
