### ISSUE TITLE
Installing plugin to Android Platform 

### ISSUE THREAD

**Issue by saaksshi** [paypal/PayPal-Cordova-Plugin#116]
/plugins/com.paypal.cordova.mobilesdk/src/android/libs/arm64_v8a" not found!

This message I get .

**Comment by bluk** [comment]
@saaksshi Which version of the plugin are you using? `3.1.17` was released yesterday to help address this issue.

**Comment by bluk** [comment]
Please reopen if you still encounter this issue on the latest plugin version.
