### ISSUE TITLE
version and ios

### ISSUE THREAD

**Issue by miche-atucha** [paypal/PayPal-Cordova-Plugin#117]
My project is on ionic, I installed only iOS platform, and the command: ionic plugin add com.paypal.cordova.mobilesdk installs the 3.1.12 version, is this correct? is 3.1.17 not supported for iOS platform, i have cordova-ios v3.9.2

**Comment by bluk** [comment]
`3.1.17` should be supported for iOS and is [published to npm](https://www.npmjs.com/package/com.paypal.cordova.mobilesdk). A normal `cordova plugin add com.paypal.cordova.mobilesdk` and `cordova plugin update ios` seems to update the version used for a regular Cordova install.

**Comment by miche-atucha** [comment]
i update today and it is ok, thanks!
