### ISSUE TITLE
Plugin not using correct clientIDs

### ISSUE THREAD

**Issue by rcorrie** [paypal/PayPal-Cordova-Plugin#118]
This is a strange one... I set up the project as instructed, set up my clientID's, etc. The plugin works.

Now I changed out the clientIDs to a different account, but all transactions are still being posted to the old account clientID's.

I've set up breakpoints in the safari inspector as well as in the PayPalMobileCordovaPlugin.m and in both places the clientID's look correct yet the plugin is still posting transactions to the old account.

Any ideas are welcome!

**Comment by bluk** [comment]
Hmmm...I would try to find the old clientID anywhere in your code base to see if it's being kept in some staging location or stale build directory. If you did a search for `PayPalEnvironmentSandbox` or `PayPalEnvironmentProduction`, you may find other places where you may be setting the client ID.

**Comment by rcorrie** [comment]
Thanks for you time! It's a Non-issue, it was due to a lack of understanding the paypal developer console UI.
