### ISSUE TITLE
Does the mobile sdk need a specific version of jquery or bootstrap?

### ISSUE THREAD

**Issue by leoo232** [paypal/PayPal-Cordova-Plugin#119]
Hi all,

Transferred a working app to new design layout and the paypal payment button wont click? any version specific dependency for dependency jquery or bootstrap? does it support a minimum and maximum version?

thx

**Comment by romk1n** [comment]
@leoo232 this plugin doesn't use `jquery` nor `bootstrap` there is no dependency on those frameworks.
