### ISSUE TITLE
Possibility of personal payment with paypal sdk/plugin

### ISSUE THREAD

**Issue by mfkenson** [paypal/PayPal-Cordova-Plugin#121]
Does PayPal SDK / plugin support personal payment?
There are 100+ users on my platform and I would like to make something like user to user payment. (assuming they all have paypal accounts).
Any hint/direction/alternative solution is appreciated! Thanks

**Comment by bluk** [comment]
Sorry direct personal user-to-user transfer isn't currently supported in the SDKs, and I don't believe there are any APIs for this. You may want to look at [PayPal.me](https://www.paypal.me) though.
