### ISSUE TITLE
[android] JSON error when initialize plugin on latest version

### ISSUE THREAD

**Issue by marcio199226** [paypal/PayPal-Cordova-Plugin#124]
HI i have tried to use this plugin but i have always a JSON error in my console using this plugin with ionic.

Anyone know how to fix it?

**Comment by bluk** [comment]
Can you please be more specific about the JSON error and what version of the plugin you are using?

**Comment by marcio199226** [comment]
i have used the latest version.
I have used this service also https://gist.github.com/Urbiwanus/c1e456f889f53e940a11 
i have tried use this plugin without service posted above but i had the same result when i run:
    PayPalMobile.init(); //with args
In console i have JSON error and no more info about this error.

I tried to reinstall your plugin and remove android platform to add it again later but nothing i have no luch with this plugin.

If there is a workaround please tell me otherwise i will have to implement payment by self through in app browser i would prefer avoid this.

Thanks in advance and sorry for my english!

**Comment by marcio199226** [comment]
nevermind i solve my trouble by self implementing it within inappbrowser.

Thanks and wish you good work.

**Comment by bluk** [comment]
Great! Thanks for reporting back.

**Comment by philecom** [comment]
@marcio199226  Please can you post your solution here, maybe it will help someone as i am facing the same issue
