### ISSUE TITLE
How to send payment to personal account

### ISSUE THREAD

**Issue by anandstarz** [paypal/PayPal-Cordova-Plugin#125]
Hi there am using Cordova Paypal plugin located here,

https://github.com/paypal/PayPal-Cordova-Plugin.

I have created sandbox account in Paypal developer. then I created one app.

It creates Business account like "anandstarz-facilitator@gmail.com".

I have created two personal accounts "mark@gmail.com" , "anandstarz-buyer@gmail.com"

When am using the app, (I did't mentioned receiver account details)

I logged in using "anandstarz-buyer@gmail.com" and paid amount.

Now the Business account "anandstarz-facilitator@gmail.com" is receive the amount.

Question?

How could I send the amount to other personal account? I mean how to sent to "mark@gmail.com".

**Comment by bluk** [comment]
The REST Payment APIs which this plugin is based on does not support PayPal consumer to consumer aka peer-to-peer payments (versus buyer to merchant). You can try looking into [PayPal.Me](https://www.paypal.me). While it doesn't use PayPal accounts, [Venmo](https://developer.venmo.com/docs/) is also popular and may support your use case.

**Comment by anandstarz** [comment]
Hi I have seen those things but which is not supported in my location.
