### ISSUE TITLE
3.1.19 PayPalMobile.init() returns JSON Error

### ISSUE THREAD

**Issue by w4ilun** [paypal/PayPal-Cordova-Plugin#126]
Tested on Cordova 5.4.1

Using the sample code and instructions provided, ran the example with:

```javascript

var clientIDs = {
    'PayPalEnvironmentSandbox' : 'MY_PAYPAL_SANDBOX_CLIENTID'
}

```

Line 41 in cdv-plugin-paypal-mobile-sdk.js returns "JSON Error"

**Comment by bluk** [comment]
@w4ilun You may have to have the following:

```
    var clientIDs = {
      "PayPalEnvironmentProduction": "YOUR_PRODUCTION_CLIENT_ID",
      "PayPalEnvironmentSandbox": "YOUR_SANDBOX_CLIENT_ID"
    };
```

If you do not have a production client ID, you can just use any placeholder value.

**Comment by w4ilun** [comment]
Using a placeholder value for the production client ID works, thanks @bluk! Would be nice to have a more verbose error response in the future.
