### ISSUE TITLE
Credit card payment not accepted

### ISSUE THREAD

**Issue by sanctus671** [paypal/PayPal-Cordova-Plugin#127]
Hi,

I'm getting an error when users are trying to pay with a credit card via the cordova plugin. It is saying "merchant does not accept payments on this type". I saw that the REST api currently has a restriction on which countries it supports. I checked out the list: https://developer.paypal.com/webapps/developer/docs/integration/direct/rest-api-payment-country-currency-support/#direct-credit-card-payments. The account is Australian which is on that list (AUD). So why is the direct credit card payment method not allowed? Am I missing something here? If it isn't allowed in Australia, what are the alternatives to getting PayPal and direct credit card payments working in a Cordova app?

Thanks

**Comment by bluk** [comment]
Unfortunately, direct credit card for AU merchants aren't supported today. Talked with a teammate who stated if you're a US or UK merchant, it may be possible to do AUD DCC.
