### ISSUE TITLE
Phonegap Build documentation out of date

### ISSUE THREAD

**Issue by jessemonroy650** [paypal/PayPal-Cordova-Plugin#128]
Your README.md is out of date for *Phonegap Build*. It is causing confusion in the forums. I'm constantly correcting people on this.

Source `source="plugins.cordova.io" ` is no longer valid.
Source should be `source=npm`. If you have not moved to NPM, I encourage you to.

Best of Luck
Jesse

**Comment by bluk** [comment]
Thanks, I fixed the README.
