### ISSUE TITLE
Pulling 3.1.12 instead of 3.1.19 using cordova plugin command 

### ISSUE THREAD

**Issue by Reiji87** [paypal/PayPal-Cordova-Plugin#129]
Hi,

Im using cordova plugin add command to add the cordova paypal plugin, but it is feteching version 3.1.12 instead of 3.1.19?

Can anyone help me with this?

Thank you

**Comment by jaypatel512** [comment]
This generally happens when the cache is not yet updated in cordova repositories. However, we made some changes to Cordova Plugin in Android SDK specifically, that would reduce this caching issues.
