### ISSUE TITLE
how to integrate cordova paypal php ?????

### ISSUE THREAD

**Issue by sam2908** [paypal/PayPal-Cordova-Plugin#130]
Hello,

how to integrate cordova paypal php ?????

Thank you :)

**Comment by papasmurph** [comment]
This is probably what you need: https://github.com/paypal/PayPal-PHP-SDK, not this plugin.

**Comment by alien3d** [comment]
CORDOVA mean client base language. PHP is server base.

**Comment by jaypatel512** [comment]
Closing the issue, as the answer was provided by @papasmurph and @alien3d !
