### ISSUE TITLE
PGB can't build for Android with 3.1.20

### ISSUE THREAD

**Issue by papasmurph** [paypal/PayPal-Cordova-Plugin#133]
iOS is fine. Android is not. I include js/paypal-mobile-js-helper.js in index.html. Anything else needed now?

See below:

-compile:
    [javac] Compiling 15 source files to /project/bin/classes
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:20: error: package com.paypal.android.sdk.payments does not exist
    [javac] import com.paypal.android.sdk.payments.*;
    [javac] ^
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:28: error: cannot find symbol
    [javac]     private PayPalConfiguration configuration = new PayPalConfiguration();
    [javac]             ^
    [javac]   symbol:   class PayPalConfiguration
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:255: error: cannot find symbol
    [javac]     private PayPalOAuthScopes getOauthScopes(JSONArray scopeList)  throws JSONException {
    [javac]             ^
    [javac]   symbol:   class PayPalOAuthScopes
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:329: error: cannot find symbol
    [javac]     private PayPalPaymentDetails parsePaymentDetails(JSONObject object) throws JSONException {
    [javac]             ^
    [javac]   symbol:   class PayPalPaymentDetails
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:342: error: cannot find symbol
    [javac]     private PayPalItem[] parsePaymentItems(JSONArray array) throws JSONException {
    [javac]             ^
    [javac]   symbol:   class PayPalItem
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:364: error: cannot find symbol
    [javac]     private ShippingAddress getPayPalShippingAddress(JSONObject object) throws JSONException {
    [javac]             ^
    [javac]   symbol:   class ShippingAddress
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:25: error: cannot find symbol
    [javac]     private String environment = PayPalConfiguration.ENVIRONMENT_PRODUCTION;
    [javac]                                  ^
    [javac]   symbol:   variable PayPalConfiguration
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:28: error: cannot find symbol
    [javac]     private PayPalConfiguration configuration = new PayPalConfiguration();
    [javac]                                                     ^
    [javac]   symbol:   class PayPalConfiguration
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:69: error: cannot find symbol
    [javac]             this.activity.stopService(new Intent(this.activity, PayPalService.class));
    [javac]                                                                 ^
    [javac]   symbol:   class PayPalService
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:76: error: cannot find symbol
    [javac]         this.callbackContext.success(Version.PRODUCT_VERSION);
    [javac]                                      ^
    [javac]   symbol:   variable Version
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:91: error: cannot find symbol
    [javac]             this.environment = PayPalConfiguration.ENVIRONMENT_NO_NETWORK;
    [javac]                                ^
    [javac]   symbol:   variable PayPalConfiguration
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:93: error: cannot find symbol
    [javac]             this.environment = PayPalConfiguration.ENVIRONMENT_PRODUCTION;
    [javac]                                ^
    [javac]   symbol:   variable PayPalConfiguration
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:96: error: cannot find symbol
    [javac]             this.environment = PayPalConfiguration.ENVIRONMENT_SANDBOX;
    [javac]                                ^
    [javac]   symbol:   variable PayPalConfiguration
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:121: error: cannot find symbol
    [javac]         String correlationId = PayPalConfiguration.getClientMetadataId(this.cordova.getActivity());
    [javac]                                ^
    [javac]   symbol:   variable PayPalConfiguration
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:127: error: cannot find symbol
    [javac]             serverStarted = this.activity.stopService(new Intent(this.activity, PayPalService.class));
    [javac]                                                                                 ^
    [javac]   symbol:   class PayPalService
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:130: error: cannot find symbol
    [javac]         Intent intent = new Intent(this.activity, PayPalService.class);
    [javac]                                                   ^
    [javac]   symbol:   class PayPalService
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:131: error: cannot find symbol
    [javac]         intent.putExtra(PayPalService.EXTRA_PAYPAL_CONFIGURATION, this.configuration);
    [javac]                         ^
    [javac]   symbol:   variable PayPalService
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:153: error: cannot find symbol
    [javac]             paymentIntent = PayPalPayment.PAYMENT_INTENT_SALE;
    [javac]                             ^
    [javac]   symbol:   variable PayPalPayment
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:155: error: cannot find symbol
    [javac]             paymentIntent = PayPalPayment.PAYMENT_INTENT_ORDER;
    [javac]                             ^
    [javac]   symbol:   variable PayPalPayment
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:157: error: cannot find symbol
    [javac]             paymentIntent = PayPalPayment.PAYMENT_INTENT_AUTHORIZE;
    [javac]                             ^
    [javac]   symbol:   variable PayPalPayment
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:194: error: cannot find symbol
    [javac]         PayPalPayment payment = new PayPalPayment(new BigDecimal(amount),
    [javac]         ^
    [javac]   symbol:   class PayPalPayment
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:194: error: cannot find symbol
    [javac]         PayPalPayment payment = new PayPalPayment(new BigDecimal(amount),
    [javac]                                     ^
    [javac]   symbol:   class PayPalPayment
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:224: error: cannot find symbol
    [javac]             Intent intent = new Intent(this.activity, PaymentActivity.class);
    [javac]                                                       ^
    [javac]   symbol:   class PaymentActivity
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:225: error: cannot find symbol
    [javac]             intent.putExtra(PaymentActivity.EXTRA_PAYMENT, payment);
    [javac]                             ^
    [javac]   symbol:   variable PaymentActivity
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:238: error: cannot find symbol
    [javac]         Intent intent = new Intent(this.activity, PayPalFuturePaymentActivity.class);
    [javac]                                                   ^
    [javac]   symbol:   class PayPalFuturePaymentActivity
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:249: error: cannot find symbol
    [javac]         Intent intent = new Intent(this.activity, PayPalProfileSharingActivity.class);
    [javac]                                                   ^
    [javac]   symbol:   class PayPalProfileSharingActivity
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:251: error: cannot find symbol
    [javac]         intent.putExtra(PayPalProfileSharingActivity.EXTRA_REQUESTED_SCOPES, getOauthScopes(args.getJSONArray(0)));
    [javac]                         ^
    [javac]   symbol:   variable PayPalProfileSharingActivity
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:264: error: cannot find symbol
    [javac]                 scopes.add(PayPalOAuthScopes.PAYPAL_SCOPE_PROFILE);
    [javac]                            ^
    [javac]   symbol:   variable PayPalOAuthScopes
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:266: error: cannot find symbol
    [javac]                 scopes.add(PayPalOAuthScopes.PAYPAL_SCOPE_EMAIL);
    [javac]                            ^
    [javac]   symbol:   variable PayPalOAuthScopes
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:268: error: cannot find symbol
    [javac]                 scopes.add(PayPalOAuthScopes.PAYPAL_SCOPE_PHONE);
    [javac]                            ^
    [javac]   symbol:   variable PayPalOAuthScopes
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:270: error: cannot find symbol
    [javac]                 scopes.add(PayPalOAuthScopes.PAYPAL_SCOPE_ADDRESS);
    [javac]                            ^
    [javac]   symbol:   variable PayPalOAuthScopes
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:272: error: cannot find symbol
    [javac]                 scopes.add(PayPalOAuthScopes.PAYPAL_SCOPE_PAYPAL_ATTRIBUTES);
    [javac]                            ^
    [javac]   symbol:   variable PayPalOAuthScopes
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:274: error: cannot find symbol
    [javac]                 scopes.add(PayPalOAuthScopes.PAYPAL_SCOPE_FUTURE_PAYMENTS);
    [javac]                            ^
    [javac]   symbol:   variable PayPalOAuthScopes
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:279: error: cannot find symbol
    [javac]         return new PayPalOAuthScopes(scopes);
    [javac]                    ^
    [javac]   symbol:   class PayPalOAuthScopes
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:338: error: cannot find symbol
    [javac]         PayPalPaymentDetails paymentDetails =  new PayPalPaymentDetails(shipping, subtotal, tax);
    [javac]         ^
    [javac]   symbol:   class PayPalPaymentDetails
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:338: error: cannot find symbol
    [javac]         PayPalPaymentDetails paymentDetails =  new PayPalPaymentDetails(shipping, subtotal, tax);
    [javac]                                                    ^
    [javac]   symbol:   class PayPalPaymentDetails
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:347: error: cannot find symbol
    [javac]         PayPalItem[] items = new PayPalItem[array.length()];
    [javac]         ^
    [javac]   symbol:   class PayPalItem
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:347: error: cannot find symbol
    [javac]         PayPalItem[] items = new PayPalItem[array.length()];
    [javac]                                  ^
    [javac]   symbol:   class PayPalItem
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:356: error: cannot find symbol
    [javac]             PayPalItem item = new PayPalItem(name, quantity, price, currency, sku);
    [javac]             ^
    [javac]   symbol:   class PayPalItem
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:356: error: cannot find symbol
    [javac]             PayPalItem item = new PayPalItem(name, quantity, price, currency, sku);
    [javac]                                   ^
    [javac]   symbol:   class PayPalItem
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:372: error: cannot find symbol
    [javac]         ShippingAddress shippingAddress =
    [javac]         ^
    [javac]   symbol:   class ShippingAddress
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:373: error: cannot find symbol
    [javac]                 new ShippingAddress().recipientName(name).line1(line1).line2(line2)
    [javac]                     ^
    [javac]   symbol:   class ShippingAddress
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:382: error: cannot find symbol
    [javac]                 PaymentConfirmation confirmation = null;
    [javac]                 ^
    [javac]   symbol:   class PaymentConfirmation
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:383: error: cannot find symbol
    [javac]                 if (intent.hasExtra(PaymentActivity.EXTRA_RESULT_CONFIRMATION)) {
    [javac]                                     ^
    [javac]   symbol:   variable PaymentActivity
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:385: error: cannot find symbol
    [javac]                             .getParcelableExtra(PaymentActivity.EXTRA_RESULT_CONFIRMATION);
    [javac]                                                 ^
    [javac]   symbol:   variable PaymentActivity
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:393: error: cannot find symbol
    [javac]             } else if (resultCode == PaymentActivity.RESULT_EXTRAS_INVALID) {
    [javac]                                      ^
    [javac]   symbol:   variable PaymentActivity
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:400: error: cannot find symbol
    [javac]                 PayPalAuthorization auth = null;
    [javac]                 ^
    [javac]   symbol:   class PayPalAuthorization
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:401: error: cannot find symbol
    [javac]                 if (intent.hasExtra(PayPalFuturePaymentActivity.EXTRA_RESULT_AUTHORIZATION)) {
    [javac]                                     ^
    [javac]   symbol:   variable PayPalFuturePaymentActivity
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:402: error: cannot find symbol
    [javac]                     auth = intent.getParcelableExtra(PayPalFuturePaymentActivity.EXTRA_RESULT_AUTHORIZATION);
    [javac]                                                      ^
    [javac]   symbol:   variable PayPalFuturePaymentActivity
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:410: error: cannot find symbol
    [javac]             } else if (resultCode == PayPalFuturePaymentActivity.RESULT_EXTRAS_INVALID) {
    [javac]                                      ^
    [javac]   symbol:   variable PayPalFuturePaymentActivity
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:415: error: cannot find symbol
    [javac]                 PayPalAuthorization auth = null;
    [javac]                 ^
    [javac]   symbol:   class PayPalAuthorization
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:416: error: cannot find symbol
    [javac]                 if (intent.hasExtra(PayPalProfileSharingActivity.EXTRA_RESULT_AUTHORIZATION)) {
    [javac]                                     ^
    [javac]   symbol:   variable PayPalProfileSharingActivity
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:417: error: cannot find symbol
    [javac]                     auth = intent.getParcelableExtra(PayPalProfileSharingActivity.EXTRA_RESULT_AUTHORIZATION);
    [javac]                                                      ^
    [javac]   symbol:   variable PayPalProfileSharingActivity
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] /project/src/com/paypal/cordova/sdk/PayPalMobileCordovaPlugin.java:425: error: cannot find symbol
    [javac]             } else if (resultCode == PayPalProfileSharingActivity.RESULT_EXTRAS_INVALID) {
    [javac]                                      ^
    [javac]   symbol:   variable PayPalProfileSharingActivity
    [javac]   location: class PayPalMobileCordovaPlugin
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 54 errors

BUILD FAILED
/android-sdk/tools/ant/build.xml:716: The following error occurred while executing this line:
/android-sdk/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.

Total time: 5 seconds

/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: ant with args: debug,-f,/project/build.xml

**Comment by jaypatel512** [comment]
I would recommend you trying https://github.com/romk1n/MyCordovaShop as a sample for getting started with Cordova Plugin. You can then directly modify it to your use and continue using it further.

I tested the latest release with the sample and it worked properly. 

Re-open if the issue still exists.

**Comment by papasmurph** [comment]
My app is based on that code, but of course rewritten. It worked a few days ago for both platforms, now it doesn't build for Android. I can perform payments with iOS and I get the right responses as well, so nothing is wrong there.

Did you test it with PGB or command line? I use PGB.

**Comment by jaypatel512** [comment]
We did make change to cordova plugin in the latest build. We are now using maven dependency to bring all android dependency. This might have affected you some way. I am try to reproduce this issue again. However, if you could, I would appreciate if you could run the given above sample code, and see if that works. This way, I could get better help on debugging and fixing this issue.

**Comment by papasmurph** [comment]
I also noted that PGB has 3.1.19.

**Comment by papasmurph** [comment]
Same problem.

I had to modify config.xml:

`<?xml version='1.0' encoding='utf-8'?>
<widget
    xmlns="http://www.w3.org/ns/widgets"
    xmlns:gap="http://phonegap.com/ns/1.0"
    xmlns:android="http://schemas.android.com/apk/res/android"
    id="com.mycompany.cordova.myshop"
    version="0.1"
    android-versionCode="001"
>
    <name>MyCordovaShop</name>
    <description>A sample Apache Cordova application that responds to the deviceready event.</description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">Apache Cordova Team</author>
    <content src="index.html" />
    <access origin="*" />

    <gap:plugin name="com.paypal.cordova.mobilesdk" source="npm" />
</widget>`
