### ISSUE TITLE
How to get payment id ?

### ISSUE THREAD

**Issue by netstudenton** [paypal/PayPal-Cordova-Plugin#137]
How to get the payment id from a payment made within the plugin ?
I want store this id for future analysis of the status.

**Comment by jaypatel512** [comment]
In general, you can follow the instructions as shown in the [Sample App](https://github.com/romk1n/MyCordovaShop/blob/master/www/js/index.js#L60) here, and obtain the payment object, which will contain  the payment Id for a successful payment.
