### ISSUE TITLE
doesn't work on android.

### ISSUE THREAD

**Issue by DenysHill** [paypal/PayPal-Cordova-Plugin#140]
I added this plugin using cordova cli.

> cordova plugin add https://github.com/paypal/PayPal-Cordova-Plugin/

and i added paypal sdk. (https://github.com/paypal/PayPal-Android-SDK)
compile 'com.paypal.sdk:paypal-android-sdk:2.12.4'

and i added palpal-mobile-js-helper.js file to my project.

I think i added this plugin exactly.

------

but it does not work on Android 5.0 and the app does crash.

**Comment by jaypatel512** [comment]
You dont have to add paypal sdk (Android SDK) to make it work for Cordova Plugin. 

Just follow the steps here, and you should be able to install this fine.
