### ISSUE TITLE
PHP currency not supported?

### ISSUE THREAD

**Issue by norvinjohn** [paypal/PayPal-Cordova-Plugin#141]
Hello,

Thanks for the great plugin!

I' am a beginner in developing hybrid mobile application using ionic. My question, is the plugin capable of handling a Philippine Peso (PHP)  currency? I' am currently encountering this issue using my sandbox account in PayPal.

Here the service I' am using to interface my application to your plugin.
[paypalservice.txt](https://github.com/paypal/PayPal-Cordova-Plugin/files/89627/paypalservice.txt)

Hope to hear from you soon. Thanks in advance!

**Comment by bluk** [comment]
Going by the [supported currency documentation](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/) for the REST APIs on developer.paypal.com, the Philippine Peso (PHP) currency is supported.

Is there an error that you are encountering? I couldn't tell from the code snippet that you attached what the actual error is.

**Comment by norvinjohn** [comment]
Sorry incomplete info. Although I did not receive any error logs from my console.

Response from the plugin:
![screenshot_2016-01-14-08-40-14](https://cloud.githubusercontent.com/assets/6295837/12312498/f3ff24c4-ba9a-11e5-9872-99f745ef1711.png)

Response from my sandbox account:
{
	"status": 400,
	"duration_time": 538,
	"body": {
		"message": "Currency is not supported",
		"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#CURRENCY_NOT_ALLOWED",
		"name": "CURRENCY_NOT_ALLOWED",
		"debug_id": "63fbb248c748b"
	},
	"additional_properties": {},
	"header": {
		"Content-Length": "195",
		"Content-Language": "*",
		"CORRELATION-ID": "63fbb248c748b",
		"Date": "Thu, 14 Jan 2016 00:40:09 GMT",
		"Connection": "close",
		"Paypal-Debug-Id": "63fbb248c748b",
		"PROXY_SERVER_INFO": "hostu003dslcsbplatformapiserv3002.slc.paypal.com;threadIdu003d412",
		"Content-Type": "application/json"
	}
}

**Comment by bluk** [comment]
The `PHP` currency should work for PayPal account payments (where you use a PayPal account to pay instead of a credit card directly). I don't believe direct credit card payments support the Philippine Peso (PHP) currency. To make sure though, you can contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com)

**Comment by atiladelcanton** [comment]
@norvinjohn  


you are using integration using the right ionic ?

you took issue with Client vendor ID in integration?

And from what I saw you chose to use all php integration via the app as it does ?

**Comment by norvinjohn** [comment]
Hi @bluk thanks for taking time to answer my question. I will try to contact Paypal's technical support if direct credit card payment with PHP is not supported.

@atiladelcanton
Yes I' am using currently using ionic version 1.6.5. Did not encounter any issue with client vendor ID integration. Yes that is correct.

**Comment by juwlee** [comment]
@norvinjohn FYI, [currencies supported by PayPal REST APIs](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/), although I would double check with PayPal MTS as @bluk suggested.

**Comment by atiladelcanton** [comment]
@norvinjohn 

Show me it would be possible Implementation YOURS?

For I am the day with ONE problem that prevent me from continuing

**Comment by pp-randy** [comment]
@norvinjohn take a look at the classic direct payment credit card documentation https://developer.paypal.com/docs/classic/api/currency_codes/#creditcard

I was able to test and Australian merchant with PHP currency.

**Comment by norvinjohn** [comment]
Noted @juwlee 

@atiladelcanton it's probably better if you share your current code with us to see where your having error/problem in the implementation.

Thanks @pp-randy I found your answer very helpful, though I' am unable to confirm it yet but base on the reference you shared my merchant sandbox account is US based. 

I will inform you as soon as possible if that is really the cause of the "unsupported currency" response.

Thanks guys I appreciate your help and effort in answering/sharing of your thoughts. It's my first time to post a question here in github :D

**Comment by norvinjohn** [comment]
@pp-randy confirmed your answer US base merchant account really don't support PHP currency. Thanks again @pp-randy hope to see you comment again if I had some issue :+1:  :)

**Comment by atiladelcanton** [comment]
#Service.js

```javascript
angular.module('starter.services', [])

.factory('PaypalService', ['$q', '$ionicPlatform', 'shopSettings', '$filter', '$timeout', function ($q, $ionicPlatform, shopSettings, $filter, $timeout) {



        var init_defer;
        /**
         * Service object
         * @type object
         */
        var service = {
            initPaymentUI: initPaymentUI,
            createPayment: createPayment,
            configuration: configuration,
            onPayPalMobileInit: onPayPalMobileInit,
            makePayment: makePayment
        };


        /**
         * @ngdoc method
         * @name initPaymentUI
         * @methodOf app.PaypalService
         * @description
         * Inits the payapl ui with certain envs. 
         *
         * 
         * @returns {object} Promise paypal ui init done
         */
        function initPaymentUI() {

            init_defer = $q.defer();
            $ionicPlatform.ready().then(function () {

                var clientIDs = {
                    "PayPalEnvironmentProduction": shopSettings.payPalProductionId,
                    "PayPalEnvironmentSandbox": shopSettings.payPalSandboxId
                };
                PayPalMobile.init(clientIDs, onPayPalMobileInit);
            });

            return init_defer.promise;

        }


        /**
         * @ngdoc method
         * @name createPayment
         * @methodOf app.PaypalService
         * @param {string|number} total total sum. Pattern 12.23
         * @param {string} name name of the item in paypal
         * @description
         * Creates a paypal payment object 
         *
         * 
         * @returns {object} PayPalPaymentObject
         */
        function createPayment(total, name) {
                
            // "Sale  == >  immediate payment
            // "Auth" for payment authorization only, to be captured separately at a later time.
            // "Order" for taking an order, with authorization and capture to be done separately at a later time.
            var payment = new PayPalPayment("" + total, "BRL", "" + name, "Sale");
            return payment;
        }
        /**
         * @ngdoc method
         * @name configuration
         * @methodOf app.PaypalService
         * @description
         * Helper to create a paypal configuration object
         *
         * 
         * @returns {object} PayPal configuration
         */
        function configuration() {
            // for more options see `paypal-mobile-js-helper.js`
            var config = new PayPalConfiguration({defaultUserEmail:shopSettings.paypalDefaultUserEmail,merchantName: shopSettings.payPalShopName,sandboxUserPassword:shopSettings.paypalSandboxUserPassword});
            return config;
        }

        function onPayPalMobileInit() {
            $ionicPlatform.ready().then(function () {
                // must be called
                // use PayPalEnvironmentNoNetwork mode to get look and feel of the flow
                PayPalMobile.prepareToRender(shopSettings.payPalEnv, configuration(), function () {

                    $timeout(function () {
                        init_defer.resolve();
                    });

                });
            });
        }

        /**
         * @ngdoc method
         * @name makePayment
         * @methodOf app.PaypalService
         * @param {string|number} total total sum. Pattern 12.23
         * @param {string} name name of the item in paypal
         * @description
         * Performs a paypal single payment 
         *
         * 
         * @returns {object} Promise gets resolved on successful payment, rejected on error 
         */
        function makePayment(total, name) {
            var defer = $q.defer();
            total = $filter('number')(total, 2);
            $ionicPlatform.ready().then(function () {
                PayPalMobile.renderSinglePaymentUI(createPayment(total, name), function (result) {
                    $timeout(function () {
                        defer.resolve(result);
                    });
                    console.log(result.response);
                    
                }, function (error) {
                    $timeout(function () {
                        defer.reject(error);
                    });
                });
            });

            return defer.promise;
        }

        return service;
    }]);
```
#app.js
```javascript
.constant('shopSettings',{
   payPalSandboxId : 'sAUetkHKulmos10U2n6aKnAa-OYbKoNHPDw5tm-lB_ZZRZzfJOCBRN8eW3iVJ8gQLHTJkyiA_I81ZPIls',
   payPalProductionId : 'AR0B3czEp1BkI0dmwePGNoKYTBf0H6ggoQ-3Clhf9QSbK-0SzN5YOG5BUDUZ7hr70ngdsh3-gc78SoGQ',
   payPalEnv: 'PayPalEnvironmentNoNetwork',   // for testing  production for production
   payPalShopName : 'Movein',
   paypalLanguageOrLocale : 'pt_BR'
   
})
```
#Implementation
```javascript
PaypalService.initPaymentUI().then(function () {
            PaypalService.makePayment(12.80, "Total").then(function(promise){
               console.log('foiii');
               console.log(promise);
               
                $ionicPopup.alert({
                                         title: 'Compra realizada com sucesso!',
                                         template:'Sua compra foi realizada: Cod Transação PayPal:'+payment.response.id
                                       });
            });
         });
```

**Comment by norvinjohn** [comment]
@atiladelcanton 

What I noticed is that we have different configuration.

Your configuration:
```javascript
function configuration() {
            // for more options see `paypal-mobile-js-helper.js`
            var config = new PayPalConfiguration({defaultUserEmail:shopSettings.paypalDefaultUserEmail,merchantName: shopSettings.payPalShopName,sandboxUserPassword:shopSettings.paypalSandboxUserPassword});
            return config;
        }
```

My configuration:
Note this configuration is based on the example provided by the author of this plugin.
```javascript
function configuration() {
            // for more options see `paypal-mobile-js-helper.js`
            var config = new PayPalConfiguration({merchantName: AppSettings.payPalAppName, merchantPrivacyPolicyURL: AppSettings.payPalMerchantPrivacyPolicyURL, merchantUserAgreementURL: AppSettings.payPalMerchantUserAgreementURL});
            return config;
        }
```

**Comment by bluk** [comment]
It seems the original issue has been resolved with the `PHP` currency, so will close this issue. If there's any other issue, please open a new one. Thanks.
