### ISSUE TITLE
How do I submit an item for you anymore ?

### ISSUE THREAD

**Issue by atiladelcanton** [paypal/PayPal-Cordova-Plugin#143]
Is there a way to spend more than one product to make payment or can only spend , because in my case the customer can buy two or more different items

**Comment by bluk** [comment]
Yes, see the [items property](https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/www/paypal-mobile-js-helper.js#L88) which is an array of [PayPalItem](https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/www/paypal-mobile-js-helper.js#L16) objects. The PayPalPayment will be the total amount and you can list individual items using PayPalItem objects.

**Comment by atiladelcanton** [comment]
I saw THIS Function , More How do I implement and send to paypal , there is no example

**Comment by bluk** [comment]
The code can be something like this:

```
var paymentDetails = new PayPalPaymentDetails("30.00", "2.00", "8.00");
var payment = new PayPalPayment("40.00", "USD", "Package Of Clothes", "sale", paymentDetails);
var paymentItemArray = [ new PayPalItem("Shirt", 1, "10.00", "USD", "shirtSKU"), new PayPalItem("Pants", 1, "20.00", "USD", "pantsSKU") ];
payment.items = paymentItemArray;
```

The total/subtotal amounts must correctly add up to the right total values. Hope that helps.

**Comment by bluk** [comment]
Seems this was resolved. Please leave a comment or open a new issue if you still need assistance. Thanks.
