### ISSUE TITLE
Problem communicating with PayPal server

### ISSUE THREAD

**Issue by norvinjohn** [paypal/PayPal-Cordova-Plugin#145]
Hi again guy! :D

Does this happen often?

![screenshot_2016-01-23-14-22-44](https://cloud.githubusercontent.com/assets/6295837/12529116/4208b32a-c1e8-11e5-855e-29825b296663.png)

Sorry did not notice you already have some updates regarding this issue.

Thanks again and God bless.

**Comment by norvinjohn** [comment]
Additional information: This error occur while using sandbox account. 

Thanks in advance for the reply. :D

**Comment by jaypatel512** [comment]
Closing this issue as this issue has been taken care of in the latest version.
