### ISSUE TITLE
Error while building app with android and ios.

### ISSUE THREAD

**Issue by RenuDaffodilsw** [paypal/PayPal-Cordova-Plugin#156]
I am using cordova-android (3.6.4) and cordova-ios (3.9.2) but the build fails for both.
I have added plugin using 'cordova plugin add com.paypal.cordova.mobilesdk'.

KIndly find the attachment for more detail :
[androidErrror.txt](https://github.com/paypal/PayPal-Cordova-Plugin/files/146554/androidErrror.txt)
[iOSErrror.txt](https://github.com/paypal/PayPal-Cordova-Plugin/files/146555/iOSErrror.txt)

**Comment by bluk** [comment]
Which version of Xcode are you using for the iOS build? Generally, you are required to have the latest Xcode (7.2.1 right now).

**Comment by RenuDaffodilsw** [comment]
I m using 7.1,  is it alright or I have to update this?

**Comment by bluk** [comment]
7.1 should be good enough but I would always recommend using the latest official Xcode toolchain.

Looking at the error for iOS, it seems the compiler does not understand the nullable, non null and other nullability annotations. This was added in the Xcode 7.x versions.

My original guess was the version of Xcode you are using to compile is too old to understand the annotations.

Can you try running
```
$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -v
```
To see which version of LLVM toolchain (the Xcode compiler) used.

It should be something like
```
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
```

You can also just use `xcode-select -p` to understand which Xcode you're running if you have multiple installations.

**Comment by bluk** [comment]
If this is still an issue, please leave a comment.

**Comment by gtsopour** [comment]
Hello @bluk,
I have the same issue and I am receiving the same error with both XCode 6.2 or 7.3? Any other advice?

Best
George

**Comment by bluk** [comment]
@gtsopour You should need Xcode 7.3 (not 6.2). 

What is output when you execute:
```
$(xcode-select -p)/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -v
```

**Comment by gtsopour** [comment]
@bluk thank for getting back to me. I really appreciate that!

Right now I am in the following Mac:
 
clang --version
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

But I receive the same issue even if with XCode 7.3 in my new Mac. I will send you this Mac info tomorrow morning my time.

Best
George

**Comment by bluk** [comment]
@gtsopour If you just want to bypass this specific issue, you can probably just find the header files (*.h) and remove the `nullable` and `nonnull` wherever you see it. There shouldn't be any harm for you in doing so.

You will be required to use Xcode 7.3 though because the static library is compiled with bitcode and that requires an Xcode 7.x-based toolset.
