### ISSUE TITLE
onSuccessfulPayment not returning transaction

### ISSUE THREAD

**Issue by yydmay** [paypal/PayPal-Cordova-Plugin#161]
I've integrated the demo into my application, i clicked 'buy now' button, went through the payment process and it succeeded, however, the onSuccessfulPayment returned the following object. it contains only the payment ID, no transaction information provided, I then logged in to my paypal sandbox account, I can only see emails to my sellers and buyers account, but no transactions logged.
Is this the final transaction? or just an authorization? I don't seem to be able to execute this payment since I don't see a payer ID returned in the object

{
    "client":{
        "environment":"sandbox",
        "paypal_sdk_version":"2.9.11",
        "platform":"Android",
        "product_name":"PayPal-Android-SDK"
    },
    "response":{
        "create_time":"2016-xx-xxTxx:xx:xxZ",
        "id":"PAY-XXXXXXXXXXXXXXXXXXXXXXXX",
        "intent":"sale",
        "state":"approved"
    },
    "response_type":"payment"
}

**Comment by ppmtscory** [comment]
@yydmay this is exactly what you should be receiving back.  The next step is to verify the payment, which is explained [here](https://developer.paypal.com/webapps/developer/docs/integration/mobile/verify-mobile-payment/).

**Comment by yydmay** [comment]
Thank you very much for quick reply. more on implementaion
1. Cordova plugin doesn't actually execute a payment? I have to use REST API to finish the transaction?
2. After verifying the payment, I am still not able to execute it as the payer ID is missing. the document says the payer ID is returned in return_url, but Cordova plugin does not allow to configure.

Sorry for noob questions since there is not developers guide available for paypal cordova integration

**Comment by ppmtscory** [comment]
The payment is already completed at the point you get the response, however you need to do the verify payment step to ensure that the response actually came from PayPal and it wasn't just somebody sending a random payment response to your client.  Within the verify payment response...
```
You should verify that the Payment:
-     Is approved ("state": "approved").
-     Contains a Transaction with:
        -  An Amount with total and currency values that match your expectation.
        -  A Sale that is completed (in related_resources, with "state": "completed").
```

**Comment by yydmay** [comment]
Thanks again for helping me out

**Comment by ppmtscory** [comment]
No problem!
