### ISSUE TITLE
OneTouch compatibility

### ISSUE THREAD

**Issue by enricodeleo** [paypal/PayPal-Cordova-Plugin#162]
Hi! Has anyone tested the new feature OneTouch with the mobile SDK? Does it work?

**Comment by bluk** [comment]
The Android portion of this mobile SDK will attempt to use the PayPal Wallet app when possible (similar to One Touch). This isn't One Touch exactly but it should help with the login experience. The iOS portion of this SDK does not.

A future possibility for One Touch support is via the Braintree mobile SDKs, but I don't believe there are any official Cordova bindings yet.
