### ISSUE TITLE
what countries supported in this plugin?

### ISSUE THREAD

**Issue by cutout33** [paypal/PayPal-Cordova-Plugin#163]
Hi,

I wanted to know what are the countries supported with this plugin? does it support all countries or just US?

**Comment by bluk** [comment]
The Android and iOS SDKs that the Cordova plugin are based on are supported in the countries and currencies mentioned on [this developer doc page](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/). Direct credit card support is much more limited than PayPal account support, so please be aware.
