### ISSUE TITLE
There was a problem setting up this payment. Please visit the paypal website to check your account.

### ISSUE THREAD

**Issue by odentiML** [paypal/PayPal-Cordova-Plugin#165]
Hi,

I opened a new issue regarding this error we have when trying to do a payment in live mode (more details in the link) :
https://github.com/paypal/PayPal-Android-SDK/issues/276

Does someone had this error too and managed to solve it ?

Thanks for your help.

**Comment by ppmtscory** [comment]
@odentiML you will need to contact customer support as it has to do with a setting/toggle for your buyer account.  You can contact your local customer support by clicking 'contact us' at the bottom of any PayPal page.  There isn't anything that is at fault within the SDK so I will be closing this issue.

**Comment by philecom** [comment]
the first thing is to visit your sandbox and make sure the user has enough fund in the testing account.
Also make sure you have correct data in the configuration
