### ISSUE TITLE
xcode6 version support

### ISSUE THREAD

**Issue by badpenguin** [paypal/PayPal-Cordova-Plugin#174]
wich is the latest version that does support xcode6?
i tried the latest version and it fails to build.

**Comment by bluk** [comment]
Probably [3.1.11](https://github.com/paypal/PayPal-Cordova-Plugin/releases/tag/3.1.11). I would kindly suggest you update to Xcode 7 at your earliest convenience, so you can also consume the latest fixes in Apple's iOS SDK and this SDK.
