### ISSUE TITLE
Does not clear previously entered credit card info

### ISSUE THREAD

**Issue by navinnd** [paypal/PayPal-Cordova-Plugin#175]
This plugin remembers user's credit card info. It can be considered as feature, however it should give user an option to choose so. Is there any way we can clear this info after successful payment.

**Comment by romk1n** [comment]
@navinnd you can pass a parameter remember user to be false and the payment data would not be saved https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/www/paypal-mobile-js-helper.js#L156

**Comment by pp-randy** [comment]
Closing this issue as it appears and answer has been provided. Please let us know if further assistance is needed.
