### ISSUE TITLE
Unable to resolve host "api-m.sandbox.paypal.com"

### ISSUE THREAD

**Issue by Omnitasker** [paypal/PayPal-Cordova-Plugin#180]
### Required Information

- Mode Sandbox
- Cordova Plugin Version: cli-5.2.0
- Platforms (Both):
- Device OS Version and Device (iOS 8.4.1 on an iPhone 4s, Android 4.4.2 on HTC One.):
- PayPal-Debug-ID(s) (from any logs):

05-20 14:38:09.039: E/paypal.sdk(4588): request failed with server response:Unable to resolve host "api-m.sandbox.paypal.com": No address associated with hostname
05-20 14:38:09.049: E/paypal.sdk(4588): SERVER_COMMUNICATION_ERROR

I'm getting this errror, it worked few days ago, but now it's always this error. Version of plugin is 3.2.0, using phonegap build. Please help

**Comment by Omnitasker** [comment]
I just tried downgrading to older versions - same error.

**Comment by bluk** [comment]
This seems like a DNS issue with your connection. Can you ping `api-m.sandbox.paypal.com` from your machine or try to do a DNS lookup?

**Comment by Omnitasker** [comment]
You are right, it was DNS issue, wifi was connected and working but for some reasone it could not resolve this host. I swicthed to mobile data and paypal went throught. Thanks

**Comment by bluk** [comment]
Cool, glad it works now.
