### ISSUE TITLE
Latest PayPal MPL (2.1.7) not working, is it? getPayPalInst not giving any respnse in Simulator and giving “not compatible” error on device

### ISSUE THREAD

**Issue by uttamraj143** [paypal/PayPal-Cordova-Plugin#181]
Since yesterday I am getting weird errors/responses in PayPal MPL iOS library (2.1.7)

On simulator, when I call

[[PayPal getPayPalInst] preapprovalWithKey:payPalPreAprovalKey andMerchantName:@"<app-name>"];
nothing happens, and by nothing I mean nothing. No error, no response, no delegate method called and obviously no MPL payment window opens at all.

And on device, the payment UI opens up but when I log in with sandbox credentials I get the following error: "This app contains payment capabilities that aren't compatible with your device."

**Comment by uttamraj143** [comment]
![paypal](https://cloud.githubusercontent.com/assets/12625654/15798692/e7671b2a-2a5e-11e6-9352-d7b816011ec0.jpg)

**Comment by bluk** [comment]
There is an existing issue at https://github.com/paypal/sdk-packages/issues/74 which we'll use to post updates. Thanks for reporting the issue.

**Comment by uttamraj143** [comment]
May I know when could i expect to fix this issue?
