### ISSUE TITLE
PayPal Express Checkout support

### ISSUE THREAD

**Issue by smjgithub** [paypal/PayPal-Cordova-Plugin#182]
Does this plugin support 'PayPal Express Checkout'

The plugin gives the options of 'PayPal with PayPal' or 'Pay with Card' but my account type does not support credit card payments?

PayPal have advised that I could use 'Express Checkout' but not sure if this is possible with the plugin?

**Comment by bluk** [comment]
The official [Express Checkout](https://developer.paypal.com/docs/classic/products/express-checkout/) is an integration between your website and PayPal. I would use it if your customers browses to your website and buy things using your website whether on a computer or a mobile device. It's a relatively simple integration for a website. This Cordova plugin is not related to Express Checkout.

This Cordova plugin (and the respective Android and iOS SDKs that it makes available for use in Cordova-based apps) is a native integration into an Android or iOS app. It allows you to accept PayPal payments and credit cards (if your account is enabled and your country is supported).

If you are heavily reliant on credit card support or want to one day adopt things like Apple/Android Pay in addition to PayPal, I would look into the [Braintree offerings](https://www.braintreepayments.com). Braintree is a PayPal company.

Hope that helps!

**Comment by smjgithub** [comment]
OK, I checked out the PhoneGap Braintree plugin but there is little to no documentation so not sure whether this would ultimately allow app users to pay with credit card if it's still basically connected to a PayPal account?

I've implemented In-App Purchases for iOS so I guess I'll do that for Android too and then if people use PayPal plugin then they'll have to pay with PayPal balance since PayPal are not willing to enable my account for credit card acceptance at this time.

Thanks for your reply 👍

**Comment by limaneto** [comment]
So how can I use Express Checkout, more precisely the Server Side Rest integration part on my Cordova base app ? Thanks.

**Comment by pp-randy** [comment]
You can use Pay with PayPal option in the application itself.  Otherwise, you could use future payments and charge using your server integration.
