### ISSUE TITLE
Paypal Production Email Erro

### ISSUE THREAD

**Issue by dabeer5stardesigner** [paypal/PayPal-Cordova-Plugin#191]
When i install demo app and change PayPalEnvironmentProduction to my paypal email address. After convert app using cordova and click buy now button its give me the error <img src="http://5stardesigners.com/wp-content/uploads/2016/07/Screenshot_2016-07-12-18-33-091.png">

I have change these two below code

initPaymentUI: function() {
    var clientIDs = {
      "PayPalEnvironmentProduction": "customer.services@xxxxxxxxxx.com",
      "PayPalEnvironmentSandbox": ""
    };
    PayPalMobile.init(clientIDs, app.onPayPalMobileInit);

  },

 PayPalMobile.prepareToRender("PayPalEnvironmentProduction", app.configuration(),

**Comment by bluk** [comment]
The client ID must be a registered app's client ID (it is not a PayPal account email address). You can create an app in the [PayPal Developer Dashboard](https://developer.paypal.com/developer/applications/). You may have to Log In in the upper right first.

More info can be found in the [PayPal Android SDK](https://github.com/paypal/PayPal-Android-SDK#credentials) README (which this Cordova plugin is based on).

If you still have an issue, please leave a comment or open a new one. Thanks.

**Comment by dabeer5stardesigner** [comment]
Thanks Problem Solve @bluk
