### ISSUE TITLE
Unable to pay

### ISSUE THREAD

**Issue by norvinjohn** [paypal/PayPal-Cordova-Plugin#194]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- Cordova Plugin Version: 3.2.2
- Platforms (iOS/Android/Both): Android
- Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.): android 4.4.4
- PayPal-Debug-ID(s) (from any logs): 

### Issue Description

> I just want to know if the paypal is currently down or the library has to do something about it. Below is the only detail I can get. 
![screenshot_2016-07-26-08-20-33](https://cloud.githubusercontent.com/assets/6295837/17121998/4c3cdb74-530a-11e6-8374-9f41ef48adca.png)

> Thanks in advance

Regards,
-Norvin

**Comment by cecoon** [comment]
same here
![screenshot_2016-07-26-09-12-43](https://cloud.githubusercontent.com/assets/8214905/17129131/9aeaaccc-5311-11e6-8a4a-d73b0b7c0020.png)

**Comment by fursid** [comment]
Required Information

**Mode (Mock/Sandbox/Live):** 
Sandbox

**Cordova Plugin Version:** 
3.1.17

**Platforms (iOS/Android/Both):** 
Both

**Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.):** 
Tested on 

- Android v4.4.2 on Infinix-x551
- Android v5.0 on Lenovo X2-EU
- Android v5.1 on Inifnix-x551
- Android v6.0.1 on Samsung SM-G925I 
- Apple - iPhone 6	v9.2.1
- Apple - iPad Mini	v9.3.2

**PayPal-Debug-ID(s) (from any logs):** 
--

**Issue Description:** 
As soon as I initiate the payment by running the following code:

`
payPalCheckout      : function () {
                that = router.activeItem();
                self = this;
                function initPaymentUI() {
                    console.log("initPaymentUI");
                    var clientIDs = {
                        "PayPalEnvironmentProduction": app.PayPalEnvironmentProduction,
                        "PayPalEnvironmentSandbox"   : app.PayPalEnvironmentSandbox
                    };
                    PayPalMobile.init(clientIDs, onPayPalMobileInit);
                }

                function onPayPalMobileInit() {
                    // must be called
                    // use PayPalEnvironmentNoNetwork mode to get look and feel of the flow
                    if (app.PayPalEnvironment == "prod") {
                        PayPalMobile.prepareToRender("PayPalEnvironmentProduction", configuration(), onPrepareRender);
                    } else {
                        PayPalMobile.prepareToRender("PayPalEnvironmentSandbox", configuration(), onPrepareRender);
                    }
                }

                function configuration() {
                    // for more options see `paypal-mobile-js-helper.js`
                    var config = new PayPalConfiguration({
                        merchantName            : "SM",
                        merchantPrivacyPolicyURL: "http://www.example.com/mobapp/smapp/#help",
                        merchantUserAgreementURL: "http://www.example.com/mobapp/smapp/#help"
                    });
                    return config;
                }

                function onPrepareRender() {
                    // single payment
                    PayPalMobile.renderSinglePaymentUI(createPayment(), onSuccesfulPayment, onUserCanceled);
                }

                function createPayment() {
                   
                    // for simplicity use predefined amount
                    // optional payment details for more information check [helper js file](https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/www/paypal-mobile-js-helper.js)
                    var paymentDetails = new PayPalPaymentDetails("5", "0.00", "0.00");
                    var payment = new PayPalPayment("5", "GBP", "SwopMarket Cart: ", "Sale", paymentDetails);
                    console.log("payment", payment);
                    return payment;
                }

                function onSuccesfulPayment(payment) {
                    console.log('onSuccesfulPayment success ', payment);
                    console.log("payment success: " + JSON.stringify(payment, null, 2));
                    if (payment.response.state == "approved") {
                        self.addOrderToDB(payment);
                    } else {
                        uikit.notify("<div class='uk-text-center'>Cancelled by user.</div>", {status: 'warning'});
                    }

                }

                function onUserCanceled(result) {
                    uikit.notify("<div class='uk-text-center'> Payment Error! <br/> There seems to be something wrong. Please try again in a moment. </div>", {status: 'warning'});
                    console.log("result", result);
                }

                initPaymentUI();
`

and the plugin is launched the following screen with error "Try Again: There was a problem communicating with the PayPal servers. Please try again." 
![7_aab979c5bdc0e6702b02bddc4a34f5ac3ad89a11_o 1](https://cloud.githubusercontent.com/assets/563015/17273046/35adee60-56c1-11e6-83b9-058d9c68d9e2.jpg)

**Comment by jaypatel512** [comment]
I was able to reproduce and fix the issue on my end, by enabling `Allow payments sent to me in a currency I do not hold:` section to accept all currency. By Default, it will not accept currencies that you do not hold in your sandbox account. 

to fix this, here are the steps you can take. You can reach out to [PayPal Merchant Technical Support](https://developer.paypal.com/support/) related to this:

1. Login to `sandbox.paypal.com` in Icognito window.
2. Login with your `sandbox account`. Make sure that is the same account used for creating the app whose clientId you are using. 
3. Click on "Business Setup" in left bar.
4. Click on "Profile" on the top menu.
5. Click `My selling tools` -> `Getting paid and managing my risk` -> `Block Payments`.
6. Enable 1st option: `Yes, accept and convert them to U.S. Dollars. Additional charges apply.`.

These steps should solve the issue you are facing. I have attached few images at the bottom to help you navigate if you get lost. Please reach out to MTS for more assistance.

![screen shot 2016-08-02 at 12 31 48 pm](https://cloud.githubusercontent.com/assets/1309895/17338678/fa0f04ea-58ad-11e6-8648-60d81215c5ca.png)
![screen shot 2016-08-02 at 12 33 26 pm](https://cloud.githubusercontent.com/assets/1309895/17338686/fea66ae8-58ad-11e6-9164-7ec48fe956df.png)
![screen shot 2016-08-02 at 12 34 05 pm](https://cloud.githubusercontent.com/assets/1309895/17338691/04ef01e4-58ae-11e6-901f-096a07e77de2.png)
![screen shot 2016-08-02 at 12 34 25 pm](https://cloud.githubusercontent.com/assets/1309895/17338693/08e72204-58ae-11e6-833d-603e473d3431.png)
![screen shot 2016-08-02 at 12 35 19 pm](https://cloud.githubusercontent.com/assets/1309895/17338699/0ccf6408-58ae-11e6-8abe-8b1cedc4c602.png)

**Comment by markserbol** [comment]
This works for me. Thanks @jaypatel512 !
