### ISSUE TITLE
"Gradle free" plugin

### ISSUE THREAD

**Issue by afxgroup** [paypal/PayPal-Cordova-Plugin#196]
- Sandbox:
- Android:
- All:

It is possible to create a fork of this plugin that don't use gradle? many automatic builders (like IntelXDK) doesn't accept plugins that has a gradle script into. What gradle is used for in this plugin (and in card.io)?

**Comment by jaypatel512** [comment]
The gradle file is used to download the `card.io` library as well as `paypal-android-sdk` library. This is required for proper functionality of the plugin in android. 

I think the Intel XDK team are working on enabling gradle support soon.

**Comment by afxgroup** [comment]
So it is used only for the download of card.io? just to understand if i can try to remove the script and include the card.io manually until they fix the problem

**Comment by jaypatel512** [comment]
The latest version only downloads mSDK as shown here. You can now download card.io separately if you wish.

```
dependencies {
   compile('com.paypal.sdk:paypal-android-sdk:2.14.4') {
      exclude group: 'io.card'
   }
}
```

**Comment by jaypatel512** [comment]
Here is the link to card.io cordova plugin repository: https://github.com/card-io/card.io-Cordova-Plugin

**Comment by afxgroup** [comment]
yes i've downloaded it and however also that plugin use gradle.. so i must wait for intel developers..
