### ISSUE TITLE
express checkout version?

### ISSUE THREAD

**Issue by roysG** [paypal/PayPal-Cordova-Plugin#197]
### Required Information

- Mode (Mock/Sandbox/Live):
- Cordova Plugin Version:
- Platforms (iOS/Android/Both):
- Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.):
- PayPal-Debug-ID(s) (from any logs):

### Issue Description

> Please include as many details (logs, steps to reproduce, screenshots, frameworks/dependencies) as you can to help us reproduce this issue faster.

**Comment by jaypatel512** [comment]
Please add more details. closing this issue as invalid.
