### ISSUE TITLE
Phonegap build version coming soon?

### ISSUE THREAD

**Issue by shaunthomson** [paypal/PayPal-Cordova-Plugin#20]
Gidday guys

Can I add my vote for you to please submit the plugin to PhoneGap Build so us Buildies can use it to?

Cheers!

**Comment by romk1n** [comment]
Just to update this thread that we have released the plugin to Cordova Repository and you can simply install it using 

```bash
$cordova plugin add com.paypal.cordova.mobilesdk
```

**Comment by sudotong** [comment]
Is there still no hope of this plugin reaching phonegap build?

**Comment by jadman02** [comment]
Hey sudotong and Shaun...I haven't finished making my app but I just installed this plugin using the phonegap build service (and it seems to be working so far)

In my config.xml I put this:

<gap:plugin name="com.paypal.cordova.mobilesdk" source="plugins.cordova.io" />

Then I added the sandbox ID by going to: https://developer.paypal.com and making an app (it took literally a second to do)'

As the plugin developers state, to make sure you see the sandbox transactions occuring "...set environment to PayPalEnvironmentSandbox"

In ..js/index.js:

onPayPalMobileInit: function() {
    // must be called
    // use PayPalEnvironmentNoNetwork mode to get look and feel of the flow
    PayPalMobile.prepareToRender("PayPalEnvironmentSandbox", app.configuration(),
      app.onPrepareRender);
  },

**Comment by pablocarson** [comment]
jadman,

I'm looking through Adobe's Phonegap Build's documentation and don't see any mention of index.js, which seems to be part of the cordova Phonegap implementation. Can you confirm whether you're talking about Phonegap Build or using the term "build" generically in the context of cordova? Thanks in advance.

(btw, this is why I think Phonegap Build is a terrible name for the Adobe cloud product.)

**Comment by romk1n** [comment]
@pablocarson the @jadman02 is right. reference to `index.js` is just simply an example on how to use the plugin. You can use it in any of your `.js`. files.

**Comment by romk1n** [comment]
I am also closing this issue since we have now uploaded the plugin to plugins.cordova.io . To use it just add to your config.xml: 

`<gap:plugin name="com.paypal.cordova.mobilesdk" source="plugins.cordova.io" />`

For more details checkout out here http://docs.build.phonegap.com/en_US/configuring_plugins.md.html#Plugins
