### ISSUE TITLE
Support for Hong Kong address format

### ISSUE THREAD

**Issue by RavenStormbringer** [paypal/PayPal-Cordova-Plugin#202]
### Required Information

- Mode (Mock/Sandbox/Live): All
- Cordova Plugin Version: 3.2.2
- Platforms (iOS/Android/Both): Both

### Issue Description

I'm working on expanding our implementation of this plugin to include other countries my company supports, including Hong Kong.  According to HK's address formatting it seems like more lines are required.  The HongKong Post defines its address format as follows:

Mr. CHAN Tai-man - recipient name
Flat A, 12th Floor - line 1
Kowloon Government Offices - line 2
405 Nathan Road - **line 3?**
YAU MA TEI - city
KOWLOON - state?

I've seen some formats on other, less official, sites that suggest a comma after the floor for the building making it a line1/2 format.  What is expected when shipping to this country?

**Comment by bluk** [comment]
I think you will have to contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com) to get advice on what to do. PayPal's REST API only has [2 lines for the address](https://developer.paypal.com/docs/api/payments/#definition-shipping_address) which is what the PayPal mobile SDKs are based on.
