### ISSUE TITLE
Hide pay with card button

### ISSUE THREAD

**Issue by norvinjohn** [paypal/PayPal-Cordova-Plugin#203]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox/Live
- Cordova Plugin Version: 3.2.2
- Platforms (iOS/Android/Both): Both
- Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.): 
- PayPal-Debug-ID(s) (from any logs):

### Issue Description
Hello guys, I just want to ask if its possible to hide the "Pay with card" button. If possible how?

Thanks for this great plugin!

**Comment by bluk** [comment]
See the [`acceptCreditCards` option](https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/www/paypal-mobile-js-helper.js#L135). If you set it to false, it should not show the button.
