### ISSUE TITLE
Can't get out of sandbox mode to live!

### ISSUE THREAD

**Issue by Jamesmallon1** [paypal/PayPal-Cordova-Plugin#213]
Mode: Sandbox/Live.
Cordova Version: 6.00 - Phonegap Build
Platform: IOS
Device OS: 9.3 - iPhone 5s

Dear All,

Really struggling here. PayPal seems to have extremely limited documentation for this plugin and I really need some help. I have installed this plugin and it completely works on iOS however I cant work out how to send payments to live or how to get out of sandbox mode.

I got my live APP ID by registering at this link:
https://www.paypal-apps.com/user/my-account/applications

I then changed the "PayPalEnvironmentProduction" variable to the Live ID i received. However the paypal plugin still says "Mock Data" and no payments are going through?

Can anyone lend a hand?

James

**Comment by Jamesmallon1** [comment]
Here is my code:

```
var app = {
    // Application Constructor
    initialize: function() {
        this.bindEvents();
    },
    // Bind Event Listeners
    //
    // Bind any events that are required on startup. Common events are:
    // 'load', 'deviceready', 'offline', and 'online'.
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    // deviceready Event Handler
    //
    // The scope of 'this' is the event. In order to call the 'receivedEvent'
    // function, we must explicitly call 'app.receivedEvent(...);'
    onDeviceReady: function() {
        app.receivedEvent('deviceready');
    },
    // Update DOM on a Received Event
    receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        console.log('Received Event: ' + id);
        app.initPaymentUI();
    },

      initPaymentUI : function () {
     var clientIDs = {
       "PayPalEnvironmentProduction": "APP-488XXXXXXXXXXXXXX",
       "PayPalEnvironmentSandbox": "APP-80W284485P519543T"
     };
     PayPalMobile.init(clientIDs, app.onPayPalMobileInit);

   },
   onSuccesfulPayment : function(payment) {
     goToNextPage();
   },
   // This code is only used for independent card.io scanning abilities
   onCardIOComplete: function(card) {
     console.log("Card Scanned success: " + JSON.stringify(card, null, 4));
   },
   onAuthorizationCallback : function(authorization) {
     console.log("authorization: " + JSON.stringify(authorization, null, 4));
   },
   createPayment : function () {
     // for simplicity use predefined amount
     // optional payment details for more information check [helper js file](https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/www/paypal-mobile-js-helper.js)
     var paymentDetails = new PayPalPaymentDetails(totalAmount, "0.00", "0.00");
     var payment = new PayPalPayment(totalAmount, "GBP", "EssexLaundryApp", "Sale", paymentDetails);
     return payment;
   },
   configuration : function () {
     // for more options see `paypal-mobile-js-helper.js`
     var config = new PayPalConfiguration({merchantName: "APPNAME", merchantPrivacyPolicyURL: "https://APPNAME.com", merchantUserAgreementURL: "https://mytestshop.com/agreement"});
     return config;
   },
    
    onClickPay : function(){
           PayPalMobile.renderSinglePaymentUI(app.createPayment(), app.onSuccesfulPayment, app.onUserCanceled);
    },
   onPrepareRender : function() {
     // buttons defined in index.html
     //  <button id="buyNowBtn"> Buy Now !</button>
     //  <button id="buyInFutureBtn"> Pay in Future !</button>
     //  <button id="profileSharingBtn"> ProfileSharing !</button>
     //  <button id="cardScanBtn">Advanced: Use card.io scan only</button>
     var buyNowBtn = document.getElementById("paymentButtonYo");
     var buyInFutureBtn = document.getElementById("buyInFutureBtn");
     var profileSharingBtn = document.getElementById("profileSharingBtn");
     var cardScanBtn = document.getElementById("cardScanBtn");

     buyNowBtn.onclick = function(e) {
       // single payment
       PayPalMobile.renderSinglePaymentUI(app.createPayment(), app.onSuccesfulPayment, app.onUserCanceled);
     };

     buyInFutureBtn.onclick = function(e) {
       // future payment
       PayPalMobile.renderFuturePaymentUI(app.onAuthorizationCallback, app.onUserCanceled);
     };

     profileSharingBtn.onclick = function(e) {
       // profile sharing
       PayPalMobile.renderProfileSharingUI(["profile", "email", "phone", "address", "futurepayments", "paypalattributes"], app.onAuthorizationCallback, app.onUserCanceled);
     };

     cardScanBtn.onclick = function(e) {
       // card.io scanning independent of paypal payments. 
       // This is used for cases where you only need to scan credit cards and not use PayPal as funding option.
       CardIO.scan({
                    "requireExpiry": true,
                    "requireCVV": false,
                    "requirePostalCode": false,
                    "restrictPostalCodeToNumericOnly": true
                  },
                  app.onCardIOComplete,
                  app.onUserCanceled
                );
      };
   },
   onPayPalMobileInit : function() {
     // must be called
     // use PayPalEnvironmentNoNetwork mode to get look and feel of the flow
     PayPalMobile.prepareToRender("PayPalEnvironmentProduction", app.configuration(), app.onPrepareRender);
   },
   onUserCanceled : function(result) {
     console.log(result);
       $("#loading").css("visibility","hidden");
   }
};
```

**Comment by bluk** [comment]
You need to create a REST API application ( https://developer.paypal.com/developer/applications/ ) for this plugin. You can look at https://github.com/paypal/PayPal-iOS-SDK/#credentials for documentation on how to get the credentials. This Cordova plugin is based on the PayPal-iOS-SDK and PayPal-Android-SDK projects.

If this doesn't resolve your issue, please leave a comment and we can reopen. Hope that helps!

**Comment by Jamesmallon1** [comment]
Hello there,

Thanks for your response I am now using REST API client credentials. 
Couple of quick questions, do I have to verify payments and charge cards like using Stripe? If so can you point me to a guide to do this. My servers run debian.

Kind regards,
James

**Comment by Jamesmallon1** [comment]
Hi I'm still really struggling with this and I don't know what to do.. 

I have now put my REST API client ID as the production ID variable.. But paypal is still in sandbox mode. Nothing is clear in the PayPal documentation. Can you please explain step by step what I must do to make my apps paypal plugin live?

**Comment by Jamesmallon1** [comment]
Any help?

**Comment by bluk** [comment]
Is this line of code:

```
PayPalMobile.prepareToRender("PayPalEnvironmentProduction", app.configuration(), app.onPrepareRender);
```

still in your code base and being executed (like adding a console.log line above and below to make sure)? In your original issue, you mentioned you were in mock mode and then now you're in sandbox mode, so I'm guessing this has been changed. The mode should be indicated at the bottom of the screen if you are in mock or sandbox mode in a gray bar.

**Comment by Jamesmallon1** [comment]
Hi it's in mock mode.

James

**Comment by soycodigo** [comment]
Hi. I have the same problem as James. I can not find the way out of sandbox
Please, help

**Comment by Jamesmallon1** [comment]
This problem still persists for me also I will try rewriting it tomorrow. If not I will need some assistance. Will update this thread at about 8pm GMT tomorrow if I have a solution.

James

**Comment by soycodigo** [comment]
It's okay. I'll be waiting answer. Greetings.

**Comment by Jamesmallon1** [comment]
Right I have found out how to fix the issue.

The issue lies in the fact that the device received event part was never fired. This means that the line:
app.initPaymentUI();

was never called and PayPal was never initiated. To fix this issue just simply write a timer function and call init paypal 10 seconds after startup. Really poor coding but the only workaround as i cannot identify the reason for received event not firing!

James

**Comment by pp-randy** [comment]
@AbdullahNasir if you are still facing this problem could you create a new issue in the repo.  Also it would be good to know if this is just iOS or Android facing as well.
