### ISSUE TITLE
PayPal not working with iOS 10

### ISSUE THREAD

**Issue by Marix1** [paypal/PayPal-Cordova-Plugin#218]
Until iOS 10 PayPal ist working.

Now if i try to pay with paypal the app crashed every time

But only Buy Now crash the app on iOS 10.
Pay in Future etc is working.

And i cant debug because it crash immediately on "return payment;"

i use ver. 3.3.0

**Comment by bluk** [comment]
@Marix1 Have you added a `NSCameraUsageDescription` in your Info.plist? More details are in the [release notes](https://github.com/paypal/PayPal-Cordova-Plugin/releases/tag/3.3.0). See https://github.com/card-io/card.io-iOS-SDK/issues/209

**Comment by bluk** [comment]
Please also try upgrading to version 3.3.1 due to an issue with the card.io dependency not being upgraded. If that doesn't fix your issue, please leave a comment. Thanks.

**Comment by Marix1** [comment]
Thanks.

@bluk i use phonegap build so i cant use only 
<gap:plugin name="com.paypal.cordova.mobilesdk" source="npm" version="3.3.1" /> 

now its working on iOS 10  - i have just made a payment. 

One point - default langugage is german - but paypal loging was in english
Before iOS 10 that was also in german

**Comment by bluk** [comment]
@Marix1 On your simulator/device, what languages are enabled (and in what order) in your `Settings > General > Language & Region` setting? The underlying PayPal iOS SDK is reading from the locale settings on the phone now and using a prioritized list from iOS.

If you're running in the Xcode Simulator, you may also have to change the Simulator's settings and in the Xcode build scheme, you may have to change the `Application Language` and `Application Region`. From the Xcode menu, it's `Product > Scheme > Edit Scheme...` (and select the scheme for your app).

![screen shot 2016-09-25 at 11 45 15 am](https://cloud.githubusercontent.com/assets/94150/18816780/babdda90-8315-11e6-80fd-8e98fe5356c6.png)

**Comment by Marix1** [comment]
Sorry i dont use xcode my mac is to old.

For testing i use an iPad now with iOS 10.0.2
Default language on iPad is german.
But the PayPal popup window is english.
is the an variable for languange to set manually?

**Comment by bluk** [comment]
You can try setting the [language or locale using the configuration property](https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/www/paypal-mobile-js-helper.js#L169). If that doesn't work, can you please take a screenshot of the `Settings > General > Language & Region` screen?

**Comment by Marix1** [comment]
Hello,
i upload 2 identically apps (only texts/logos are diffrent) to itunes at Sep-19 
One passed.  The other i change at bit in meantime.
At this app paypal is working on iOS 10 with version 3.3.0 even the language is correct!!

The error must be include after Sep.19.

Now if i try version 3.3.0 or 3.3.1 the language is wrong.
But 3.3.0 is working too on iOA 10 - no crash anymore.
Now i test to include the plugins from Sep.19 to actual .ipa - but same language error.

So it could be an error from phonegap build itself ???

**Comment by bluk** [comment]
@Marix1 The only thing I can think of is that somehow the dependencies may be being updated in-between app submissions but I'm not sure.

It sounds like things are working so I'll close the issue.
