### ISSUE TITLE
[CardIOUtilities preloadCardIO]: unrecognized selector sent to class 0x105ee4140

### ISSUE THREAD

**Issue by pozzer1972** [paypal/PayPal-Cordova-Plugin#219]
### Required Information

- Mode: Sandbox on ionic emulate ios:
- Cordova Plugin Version:3.3.0:
- Platforms (iOS/Android/Both): iOS
- Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.): iOS 10 iPhone 6
- PayPal-Debug-ID(s) (from any logs):

### Issue Description

> Please include as many details (logs, steps to reproduce, screenshots, frameworks/dependencies) as you can to help us reproduce this issue faster.

This is the log detail I received from the emalator:

card.io: Camera support only available on armv7(s) architecture -- can't use camera
+[CardIOUtilities preloadCardIO]: unrecognized selector sent to class 0x105ee4140
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[CardIOUtilities preloadCardIO]: unrecognized selector sent to class 0x105ee4140'

After calling the Paypal came up from bottom and take some seconds to "Checking this device" process... after a while the application stop working close all and I see the default iOs screen.

Let me know

Thank you

**Comment by bluk** [comment]
Thanks for reporting the issue. This should be fixed in [release 3.3.1](https://github.com/paypal/PayPal-Cordova-Plugin/releases/tag/3.3.1) which upgrades the card.io dependency.
