### ISSUE TITLE
Tips for disabling card.io ?

### ISSUE THREAD

**Issue by pozzer1972** [paypal/PayPal-Cordova-Plugin#220]
There's a way to disable (for testing) the card.io dependency and disable the card scan ?

So we can test the standatd paypal functionality ?

Thank you!

**Comment by bluk** [comment]
If you disable credit cards, you shouldn't encounter any card.io dependency. You won't be able to test the credit card functionality but the standard PayPal functionality should work.

https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/www/paypal-mobile-js-helper.js#L135
