### ISSUE TITLE
Cannot add plugin 

### ISSUE THREAD

**Issue by appzone** [paypal/PayPal-Cordova-Plugin#225]
Hi

i try the guide in the readme

  $ cordova create MyShop com.mycompany.myshop "MyShop"
   $ cd MyShop
   # using cordova repository (many thanks to @Ramneekhanda for helping with this)
   $ cordova plugin add com.paypal.cordova.mobilesdk

then i get the following information
Installing "com.paypal.cordova.mobilesdk" for android
Fetching plugin "card.io.cordova.mobilasdk" via npm

and after that no progress, it stuck on fetching card.io plugin 
i wait around 30 minutes and it still same no progress

any help will appreciate 

thanks

**Comment by bluk** [comment]
The card.io plugin is a large repository so it may take some time before it is downloaded. We are looking for alternative solutions that are compatible with dependency management systems but if you have recommendations, that would be great. I'm not sure if you can pre-fetch the cardio plugin outside the command which may also help.

**Comment by jaypatel512** [comment]
Installation may take some time specially if it includes card.io libraries for npm. It should optimize in multiple tries if npm is set to cache these packages.

**Comment by jaypatel512** [comment]
You could try adding directly from github as shown in the README.md if that solves this issue for you.
