### ISSUE TITLE
How to enable plugin to live credential?

### ISSUE THREAD

**Issue by nive745** [paypal/PayPal-Cordova-Plugin#227]
Hi,

How can i enable sandbox or live mode to your plugin?

### Required Information
- Mode (Mock/Sandbox/Live):
- Cordova Plugin Version:
- Platforms (iOS/Android/Both):
- Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.):
- PayPal-Debug-ID(s) (from any logs):

### Issue Description

> Please include as many details (logs, steps to reproduce, screenshots, frameworks/dependencies) as you can to help us reproduce this issue faster.

**Comment by soycodigo** [comment]
You find answer to this? I have the same problem.

**Comment by nive745** [comment]
You have to define Environment in onPayPalMobileInit method of paypal.

There are three environment for paypal.

 - PayPalEnvironmentSandbox
 - PayPalEnvironmentProduction
 - PayPalEnvironmentNetwork

onPayPalMobileInit: function() {
    // must be called
    // use PayPalEnvironmentNoNetwork mode to get look and feel of the flow
    PayPalMobile.prepareToRender("PayPalEnvironmentSandbox",
app.configuration(),
      app.onPrepareRender);
  },

Change method in prepareToRender function and thats it.

Thanks,
Nikhil Thaker
