### ISSUE TITLE
Transaction Id not found in response.

### ISSUE THREAD

**Issue by parmarhardik** [paypal/PayPal-Cordova-Plugin#228]
Hi,

How can I get the transaction id in response from paypal after successful transaction. We've already checked response, but didn't get that transaction in response.

Please can you help me to get out from this issue. Here is the attached screenshots for more details.
![paypal-response](https://cloud.githubusercontent.com/assets/5364133/19116980/083890b8-8b35-11e6-8579-d5ef597142c5.PNG)

![paypal-details](https://cloud.githubusercontent.com/assets/5364133/19116743/278a8ecc-8b34-11e6-8668-049dd1a3d22a.png)
![paypal-dashboard](https://cloud.githubusercontent.com/assets/5364133/19116886/a3c288f0-8b34-11e6-8c81-0662b6a7a3eb.png)

Thanks.

**Comment by ppmtscory** [comment]
@parmarhardik you need to do the second step of verifying the payment, which is explained [here](https://developer.paypal.com/docs/integration/mobile/verify-mobile-payment/).  The response from the plugin is the same as from the mobile SDK which is just the Pay-ID and then you'll get the transaction ID in the response from verifying the payment.
