### ISSUE TITLE
Can you please explain the workflow for the entire process using the plugin.

### ISSUE THREAD

**Issue by ashutosh-finelogics** [paypal/PayPal-Cordova-Plugin#234]
### Required Information

- Mode (Mock/Sandbox/Live): All
- Cordova Plugin Version: Latest
- Platforms (iOS/Android/Both): Both
- Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.):
- PayPal-Debug-ID(s) (from any logs):

### Issue Description

Can anyone please explain the workflow for the entire process... I mean after a customer pays through the app, what should be done at the server side and how? Is IPN necessary for it too.
Iam integrating mobile with paypal using paypal app sdk for the first time and Iam a bit confused.
Any help would be great and make me oblized...

**Comment by bluk** [comment]
The underlying PayPal Android and iOS SDKs have [documentation related to verifying payments](https://github.com/paypal/PayPal-Android-SDK/#next-steps) and the general overview of the process which you may find helpful.
