### ISSUE TITLE
Android Crashes on opening PayPal

### ISSUE THREAD

**Issue by Jamesmallon1** [paypal/PayPal-Cordova-Plugin#235]
### Required Information

- Live Mode.
- Latest Plugin
- Android
- Samsung S5, S7 and Bluestacks Api 22,22,19
- Built with Phonegap Build.
- MinSDKVersion: 16.

### Issue Description

Here is the logs from ADB Logcat

`E/AndroidRuntime(25734): FATAL EXCEPTION: main
E/AndroidRuntime(25734): Process: com.amir.essexlaundryapp, PID: 25734
E/AndroidRuntime(25734): java.lang.RuntimeException: Unable to bind to service com.paypal.android.sdk.payments.PayPalService@4e7f24e4 with Intent { cmp=com.amir.essexlaundryapp/com.paypal.android.sdk.payments.PayPalService (has extras) }: java.lang.RuntimeException: Missing EXTRA_PAYPAL_CONFIGURATION. To avoid this error, set EXTRA_PAYPAL_CONFIGURATION in both PayPalService, and the initializing activity.
E/AndroidRuntime(25734):        at android.app.ActivityThread.handleBindService(ActivityThread.java:2611)
E/AndroidRuntime(25734):        at android.app.ActivityThread.access$1900(ActivityThread.java:135)
E/AndroidRuntime(25734):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
E/AndroidRuntime(25734):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(25734):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(25734):        at android.app.ActivityThread.main(ActivityThread.java:5021)
E/AndroidRuntime(25734):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(25734):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(25734):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:827)
E/AndroidRuntime(25734):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:643)
E/AndroidRuntime(25734):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(25734): Caused by: java.lang.RuntimeException: Missing EXTRA_PAYPAL_CONFIGURATION. To avoid this error, set EXTRA_PAYPAL_CONFIGURATION in both PayPalService, and the initializing activity.
E/AndroidRuntime(25734):        at com.paypal.android.sdk.payments.PayPalService.a(Unknown Source)
E/AndroidRuntime(25734):        at com.paypal.android.sdk.payments.PayPalService.onBind(Unknown Source)
E/AndroidRuntime(25734):        at android.app.ActivityThread.handleBindService(ActivityThread.java:2598)
E/AndroidRuntime(25734):        ... 10 more`

app.configuration():
`var config = new PayPalConfiguration({merchantName: "EssexLaundryApp", merchantPrivacyPolicyURL: "https://exclusivecleaners.co.uk/terms", merchantUserAgreementURL: "https://exclusivecleaners.co.uk/agreement", languageOrLocale: "en"});
     return config;`

To be honest I'm at a complete loss with this SDK I have had countless errors and there's nothing in the documentation. Please can someone help me I have to submit this in 2 days time.

Kind regards,
James

**Comment by jaypatel512** [comment]
Are you able to reproduce this issue if you install the Demo app in your phone/emulator ? That can help us identify the issue being in the SDK or the device. Please re-open if the issue is still reproducible in Demo app. I was not able to do that in my environment, and may need more information.
