### ISSUE TITLE
Integration recurring payment option in paypal-cordova-plugin

### ISSUE THREAD

**Issue by lovey92** [paypal/PayPal-Cordova-Plugin#236]
### Required Information

- Mode (Mock/Sandbox/Live):
- Cordova Plugin Version:
- Platforms (iOS/Android/Both):
- Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.):
- PayPal-Debug-ID(s) (from any logs):

### Issue Description

> Please include as many details (logs, steps to reproduce, screenshots, frameworks/dependencies) as you can to help us reproduce this issue faster.

**Comment by lovey92** [comment]
Hi, 

Is there any option and have you worked on adding recurring payment option in paypal-cordova-plugin?

Please add this option or please suggest how do we implement recurring payment in paypal-cordova-plugin.

Thanks

**Comment by bluk** [comment]
Subscription/recurring (a.k.a. non-user initiated) payments are not supported with this plugin. The best way is to have the user subscribe via visiting your website and using the [Billing Plans](https://developer.paypal.com/docs/integration/direct/create-billing-plan/) API which have various server side language SDK support.
