### ISSUE TITLE
How Can I call the clearAllUserData method?

### ISSUE THREAD

**Issue by manuel-norsync** [paypal/PayPal-Cordova-Plugin#237]
### Required Information

- Mode (Mock/Sandbox/Live): SandBox
- Platforms (iOS/Android/Both): Both

### Issue Description

> Is there a way to remove all stored data from Users, like accounts and credit cards numbers?
I know that there is an option to prevent that. But I am looking for an option to do it dynamically.

Thanks.

**Comment by jaypatel512** [comment]
Currently, we do not have that feature created, and we do not intend to add this feature in near future. If more developers asks for this feature, we will revisit the decision. Thanks.
