### ISSUE TITLE
failing to build

### ISSUE THREAD

**Issue by sreekar89** [paypal/PayPal-Cordova-Plugin#238]
### Issue Description

BUILD FAILED

Total time: 27.078 secs
Error: /Users/paulsreekars/adheights/cdvpaypal/MyShop/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/paulsreekars/adheights/cdvpaypal/MyShop/platforms/android/AndroidManifest.xml:13:5-74 Error:
	uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.paypal.sdk:paypal-android-sdk:2.14.6] /Users/paulsreekars/adheights/cdvpaypal/MyShop/platforms/android/build/intermediates/exploded-aar/com.paypal.sdk/paypal-android-sdk/2.14.6/AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="com.paypal.android.sdk.payments" to force usage

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.paypal.sdk:paypal-android-sdk:2.14.6] /Users/paulsreekars/adheights/cdvpaypal/MyShop/platforms/android/build/intermediates/exploded-aar/com.paypal.sdk/paypal-android-sdk/2.14.6/AndroidManifest.xml
  	Suggestion: use tools:overrideLibrary="com.paypal.android.sdk.payments" to force usage

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by jaypatel512** [comment]
Looks like your project's minVersion is 14, which cannot be smaller than version 16 in our library. If you still want to use the library, you can manually override using `tools:overrideLibrary` in `uses-sdk`.
