### ISSUE TITLE
Does this plugin work with the PayPal Chip Card Reader?

### ISSUE THREAD

**Issue by junerockwell** [paypal/PayPal-Cordova-Plugin#240]
1. Am I able to send the full charge amount to the Chip Card Reader for the customer to see how much they're going to be paying before swiping the card (magnetic swipe/chip reading) or contactless payment (iOS Pay/Android Pay)?

2. And, will the chip card reader send back data for my hybrid mobile app to print to a receipt and inform the hybrid app that the transaction is over?

**Comment by bluk** [comment]
This plugin is not for the PayPal Here / Chip Card Reader product. Please see https://developer.paypal.com/docs/integration/paypal-here/ for more information about PayPal Here. I don't believe there is an official Cordova Plugin available for the PayPal Here product, but you can find the [native SDKs here](https://github.com/PayPal-Mobile). Hope that helps.
