### ISSUE TITLE
app crashes on PayPalMobile.renderSinglePaymentUI

### ISSUE THREAD

**Issue by wowzaaa** [paypal/PayPal-Cordova-Plugin#248]
Hi

So the code inside my app is:
```
PayPalMobile.renderSinglePaymentUI(
          new PayPalPayment("50.00", "USD", "Awesome Sauce", "Sale", new PayPalPaymentDetails("50.00", "0.00", "0.00")),
          function(payment) {
            console.log("payment success: " + JSON.stringify(payment, null, 4));
          },
          function(result) {
            console.log(result);
          });
```

As you can see it is a dummy code but it manages to break my app

I looked inside the logs and managed to find this:
```
12-01 20:02:42.062  9854  9854 D AndroidRuntime: Shutting down VM
12-01 20:02:42.062  9854  9854 E AndroidRuntime: FATAL EXCEPTION: main
12-01 20:02:42.062  9854  9854 E AndroidRuntime: Process: com.wowzaaa.rts, PID: 9854
12-01 20:02:42.062  9854  9854 E AndroidRuntime: java.lang.RuntimeException: Unable to bind to service com.paypal.android.sdk.payments.PayPalService@f9f7fa6 with Intent { cmp=com.wowzaaa.rts/com.paypal.android.sdk.payments.PayPalService VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} (has extras) }: java.lang.RuntimeException: Missing EXTRA_PAYPAL_CONFIGURATION. To avoid this error, set EXTRA_PAYPAL_CONFIGURATION in both PayPalService, and the initializing activity.
12-01 20:02:42.062  9854  9854 E AndroidRuntime:        at android.app.ActivityThread.handleBindService(ActivityThread.java:3848)
12-01 20:02:42.062  9854  9854 E AndroidRuntime:        at android.app.ActivityThread.access$2200(ActivityThread.java:222)
12-01 20:02:42.062  9854  9854 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1888)
12-01 20:02:42.062  9854  9854 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
12-01 20:02:42.062  9854  9854 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:158)
12-01 20:02:42.062  9854  9854 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7229)
12-01 20:02:42.062  9854  9854 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-01 20:02:42.062  9854  9854 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
12-01 20:02:42.062  9854  9854 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
12-01 20:02:42.062  9854  9854 E AndroidRuntime: Caused by: java.lang.RuntimeException: Missing EXTRA_PAYPAL_CONFIGURATION. To avoid this error, set EXTRA_PAYPAL_CONFIGURATION in both PayPalService, and the initializing activity.
12-01 20:02:42.062  9854  9854 E AndroidRuntime:        at com.paypal.android.sdk.payments.PayPalService.a(Unknown Source)
12-01 20:02:42.062  9854  9854 E AndroidRuntime:        at com.paypal.android.sdk.payments.PayPalService.onBind(Unknown Source)
12-01 20:02:42.062  9854  9854 E AndroidRuntime:        at android.app.ActivityThread.handleBindService(ActivityThread.java:3835)
12-01 20:02:42.062  9854  9854 E AndroidRuntime:        ... 8 more
```
 
any idea on how to get this to work? :)

thanks

**Comment by Demayl** [comment]
Same error here. Tested with versions 3.3.1 and 3.2.2 in phonegap cli ver 6.3.1 ( latest )

**Comment by yogeshvardhmane** [comment]
My app also crashing when integrated with angularjs.

**Comment by ppmtscory** [comment]
Are you only seeing this with your app or are you also getting it with the sample app/code that's in the repo?  Also, am I safe in assuming that you've `set EXTRA_PAYPAL_CONFIGURATION in both PayPalService, and the initializing activity`?

**Comment by AbdullahNasir** [comment]
I am still facing this issue, any solution ?

**Comment by AbdullahNasir** [comment]
@ppmtscory how do we set  EXTRA_PAYPAL_CONFIGURATION ? I am also getting this error 
"Missing EXTRA_PAYPAL_CONFIGURATION To avoid this error, set EXTRA_PAYPAL_CONFIGURATION in both PayPalService, and the initializing activity"

**Comment by yogeshvardhmane** [comment]
Make sure you have following things configured correctly.
1  client ids
2  onpreparerender method is present in your code
3 you are calling prepare to render method

Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Mar 17, 2017 at 3:31 PM +0530, "AbdullahNasir" <notifications@github.com<mailto:notifications@github.com>> wrote:


I am still facing this issue, any solution ?

**Comment by AbdullahNasir** [comment]
@yogeshvardhmane yes that was the issue. thanks

**Comment by xiaoleih41** [comment]
It looks like the issue has been solved. Please let us know if you have any further questions. Thanks, Xiaolei

**Comment by HemaWaThi** [comment]
Hi all,
When i use paypal from cordova phonegap, my app becomes crash and error occur in console as below.
Error: exec proxy not found for :: PayPalMobile :: renderSinglePaymentUI
(index):359 Missing Command Error
I would like to use paypal call function inside one of the function but i face the error.
Can someone knows pls help me?
I tried to attach the screen shot can't attach into editor.

Thank you very much!
Hema

**Comment by pp-randy** [comment]
@HemaWaThi please create a new issue if you are still experiencing a problem.  Also please be sure that you provide the platform and other details requested in the issue template.
