### ISSUE TITLE
Cordova build size issue

### ISSUE THREAD

**Issue by sudharsanmit** [paypal/PayPal-Cordova-Plugin#249]
I built my app for android without paypal plugin -> SIZE = 3.98 MB
After adding plugin -> SIZE = 25.2 MB

Is this normal?
I am running Cordova 6.0 and paypal plugin version 3.3.1.

**Comment by bluk** [comment]
Please see https://github.com/paypal/PayPal-Android-SDK/issues/251 for information related to the size. It is due to to the multiple architectures as well as some of the dependencies (which may be optional).

**Comment by sudharsanmit** [comment]
Thank you.
