### ISSUE TITLE
PayPal SDK is calling an invasive method `TelephonyManager.getLine1Number`

### ISSUE THREAD

**Issue by lietu** [paypal/PayPal-Cordova-Plugin#252]
### Required Information

- Mode (Mock/Sandbox/Live): Live
- Cordova Plugin Version: 3.3.1
- Platforms (iOS/Android/Both): Android
- Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.): All
- PayPal-Debug-ID(s) (from any logs): None

### Issue Description

We're using the PayPal SDK on our Cordova application that we've released on both Google Play and App Store. Now we're in the process of trying to get our app featured in a Google Play collection, and bumped into an issue.

Google found references to the `getLine1Number` method in the Android `TelephonyManager`, which they find invasive and a large privacy risk. We traced this usage down to the PayPal Android SDK.

The only usage of this method in our application we found in `com.paypal.android.sdk.payments.at` class private method `l` (names likely obfuscated during compilation), and it looks like it's used for debugging in case of errors. 

Attached a dex dump of the method that has this reference. [getline1number.txt](https://github.com/paypal/PayPal-Cordova-Plugin/files/660918/getline1number.txt)

A Java Decompiler tells me the block reads as follows:

```
if (localbl.a(bm.n))
{
  if (!bool) {
    break label2068;
  }
  localObject4 = localTelephonyManager.getLine1Number();
  label819:
  localas.r = ((String)localObject4);
}
```

We're using the Cordova plugin `3.3.1` which depends on `com.paypal.sdk:paypal-android-sdk:2.14.6`.

How can we get rid of this invasive code?

**Comment by ppmtscory** [comment]
@lietu apologies for the delay.  We'll take a look at where this is being used and let you know what we come up with.  Out of curiosity, are you looking to submit to their Education/Family program or just a normal app submission?  We've not seen this warning previously and there's no mention of _you shouldn't use this_ in the Google docs for `getLine1Number()` that I could find.

**Comment by lietu** [comment]
Not in any special category, just a normal app. It's been out for Android for a year already, and there is indeed nothing mentioning `you shouldn't use this` in the Google's docs for the functionality. However, they have some guidelines on e.g. apps not using permissions they don't need to use, which they are especially picky about when considering apps for promoting in e.g. their collections.

Here's a few direct quotes from emails we received from them:

```
The 'getLine1Number' method - accessed with the READ_PHONE_STATE permission found in your 
manifest doesn't seem necessary to support core features. Your app must only request the 
absolute minimum that it needs to support core functionality.

For more info:

http://developer.android.com/distribute/essentials/quality/core.html#fn
```

```
I'm afraid that it is too much of an invasive permission that we cannot waive unless it is 
essential to the app.
```

**Comment by ppmtscory** [comment]
@lietu my apologies if I've missed it in our correspondence but have you tried removing the `READ_PHONE_STATE` permission from your manifest?  We're currently working with the internal team that's responsible for the library that's utilizing `getLine1Number` but wondering if this would work for you in the meantime.

**Comment by lietu** [comment]
I'm pretty sure we're currently using `READ_PHONE_STATE` to monitor network status, but I could give it a go. I'll let you know if that works as a temporary workaround.

**Comment by lietu** [comment]
We found several other plugins that depend on `READ_PHONE_STATE` and removing it would cripple our application severely, so that is not a possible workaround at this time.

**Comment by lietu** [comment]
Any ETA on an update? Google is not really budging with this, and we're currently facing the choice of if we remove PayPal support from our app to get accepted by Google.

**Comment by lkorth** [comment]
#262 fixes it.

**Comment by lietu** [comment]
Thanks for the help. I can confirm that with #262 the invasive code is gone, and Google confirmed this as well.
