### ISSUE TITLE
How can I specify the language to render the PayPal plugin?

### ISSUE THREAD

**Issue by elysiopires** [paypal/PayPal-Cordova-Plugin#254]
I want to know how can I specify the language to render the PayPal Plugin. In my case portuguesa-brazil.

Thx,
Elysio

**Comment by bluk** [comment]
Please see https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/www/paypal-mobile-js-helper.js#L169 . You can set the language or locale in the configuration.
