### ISSUE TITLE
PayPal and jQuery Mobile

### ISSUE THREAD

**Issue by SeptekLab** [paypal/PayPal-Cordova-Plugin#255]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- Cordova Plugin Version: last one (just installed)
- Platforms (iOS/Android/Both): iOS
- Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.):
- PayPal-Debug-ID(s) (from any logs):

### Issue Description

Hi,
I created the cordova project and applied PayPal pluin perfectly (the button works and all).
Now I'm trying to inject jquery mobile but it seems like it doesn't load..
How can I fix this? I can't believe I'm the only one who tries to have PayPal and jQuery Mobile cohoperate... Thanks for any help

**Comment by bluk** [comment]
Is there any error message and any code snippet you can give? That may help someone narrow down the issue.

**Comment by xiaoleih41** [comment]
We are closing this ticket. Please let us know if you have any further questions. Thanks, Xiaolei
