### ISSUE TITLE
PAYMENT_CREATION_ERROR in live mode

### ISSUE THREAD

**Issue by kennethwwu** [paypal/PayPal-Cordova-Plugin#256]
### Required Information

- Mode (Mock/Sandbox/Live): Live
- Cordova Plugin Version: com.paypal.cordova.mobilesdk 3.3.1 "PayPalMobile"
- Platforms (iOS/Android/Both): IOS
- Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.): IOS 10.2 on iphone 7+
- PayPal-Debug-ID(s) (from any logs):d3b6943abc0bb, d3b6943abc0bb

### Issue Description

Switch to live mode in my ionic app, keep getting error msg when login a paypal account:
'PayPal SDK: Request has failed with error: PAYMENT_CREATION_ERROR - There was a problem setting up this payment. Please visit the PayPal website to check your account. (422)'

in the live app setting page the 'Log In with PayPal' option is unticked, it ask for a Return URL when i tick it, what Return URL should put in?

**Comment by pp-randy** [comment]
I apologize for the delay in following up. Log in with PayPal is an option to let users log into your service using PayPal as the login provider.  Most likely this was an issue with your Live App permissions for payments.  If this is still ongoing please provide a new paypal debug id and I will try to assist you further.
