### ISSUE TITLE
Is this plugin works in Brazil to receive amounts in BRL?

### ISSUE THREAD

**Issue by elysiopires** [paypal/PayPal-Cordova-Plugin#257]
Hello!

I want to know if this plugin works in Brazil to receive amounts in BRL?

Thx,
Elysio

**Comment by bluk** [comment]
This plugin uses the PayPal Mobile SDKs which in turn uses the REST API. Please see the [REST API Supported Currencies](https://developer.paypal.com/webapps/developer/docs/integration/direct/rest-api-payment-country-currency-support/) which has a special note about `BRL`. If you have further questions, please contact [PayPal Support](https://www.paypal.com/selfhelp/home).
