### ISSUE TITLE
Payment Failed

### ISSUE THREAD

**Issue by SpellCraft** [paypal/PayPal-Cordova-Plugin#259]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- Cordova Plugin Version: 3.3.1
- Platforms (iOS/Android/Both): Both
- Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.):
iOS 10.2 on iPhone 7 Plus and Android 6.0.1 on Xiaomi MI 4c and Nexus 5
- PayPal-Debug-ID(s) (from any logs): None. See bellow.

### Issue Description

I'm trying to use my local currency, NOK, however I'm constantly getting a "Payment Failed" error saying that this currency is not currently supported by Paypal!

To reproduce simply build the MyCordovaShop example, change the currency from USD to NOK in the PayPalPayment function within index.js and switch the environment from PayPalEnvironmentNoNetwork to PayPalEnvironmentSandbox.

I logged on to the sandbox website using my -facilitator user that was generated through the Developer center, all currencies are set to NOK as well as having accepting all currencies and converting to NOK enabled from the sandbox facilitator accounts' business tools.

Is this an issue limited to sandbox alone? Is there something on my end that I've messed up?
I could alternatively share my entire project for you guys to see if needed as well.

**Comment by pp-randy** [comment]
I am testing with both sandbox created Norway Business and Buyer accounts and not getting a failure.  Do you have a debug_id or any logging available?

**Comment by SpellCraft** [comment]
Thanks for commenting @pp-randy 

Chrome Developer Console isn't reporting any errors. All I'm getting when clicking "Charge Card" is a notification box telling me the currency isn't supported.

![screenshot_20170125-160758](https://cloud.githubusercontent.com/assets/19538199/22295850/a06313dc-e318-11e6-8063-1ff562e46c7f.png)

I think I'm using the correct Sandbox Client ID as well? The Client ID you're issued when you've added a REST API app at the Paypal Developer Dashboard.

**Comment by pp-randy** [comment]
I was testing PayPal Payment.  

This is for a Credit Card payment?  These would be the restrictions on Currency for Credit Cards https://developer.paypal.com/docs/classic/api/currency_codes/#creditcard
From the above document if your facilitator account is US account it won't work for NOK.

**Comment by SpellCraft** [comment]
Yes! It's a credit card payment (Tried with Visa, MasterCard)

Everything is displayed in Norwegian (I should have signed up from Norway as well when I created my account) and everything else.  Checking the account details for the facilitator on the Dashboard lists it as Norwegian as well.
![chrome_2017-01-25_16-29-50](https://cloud.githubusercontent.com/assets/19538199/22296841/b5e944bc-e31b-11e6-8e5b-de6b35d0eab9.png)

**Comment by pp-randy** [comment]
You would need a country in this list for Credit Card payment though since they are not supported as being the receiver in all countries https://developer.paypal.com/docs/classic/api/currency_codes/#creditcard

If your live account will be from Norway I don't see Credit Card as being an option, only PayPal payments.

**Comment by SpellCraft** [comment]
Ah snap, that went straight over my head. I completely missed what you were trying to say earlier.

Before closing the comment, would it be easy enough to call up Paypal support and have them change my country or would I simply need to create a new business account specifically for that?

Thanks again for the insight.

**Comment by pp-randy** [comment]
For Sandbox create a new account and REST App to test with.  For Live I don't really know much about that process so I apologize.

**Comment by SpellCraft** [comment]
Thank you @pp-randy !
