### ISSUE TITLE
request failed with server response:stream was reset: INTERNAL_ERROR / SERVER_COMMUNICATION_ERROR

### ISSUE THREAD

**Issue by OctavioSI** [paypal/PayPal-Cordova-Plugin#260]
### Required Information

- Mode (Mock/Sandbox/Live): Sandbox
- Cordova Plugin Version: 3.3.1
- Platforms (iOS/Android/Both): Android
- Device OS Version and Device (iOS 9.x on an iPhone 6, Android Marshmallow on Nexus 6, etc.): Android 6.0 on Moto G 3rd Gen
- PayPal-Debug-ID(s) (from any logs):

### Issue Description

> Please include as many details (logs, steps to reproduce, screenshots, frameworks/dependencies) as you can to help us reproduce this issue faster.

Whenever trying to access Sandbox PayPal to proceed with a payment, an error stating that "There was a problem communicating with the PayPal servers. Please try again."

logcat shows the following:
```
01-17 16:18:21.736 E: request failed with server response:stream was reset: INTERNAL_ERROR
01-17 16:18:21.737 E: SERVER_COMMUNICATION_ERROR
```

After many tries, once in a while I am able to login, but the error is almost always there. I have followed some similar questions at stackoverflow and also within issues in other paypal repositories here in Github, and some state that it could be an issue with the PayPal SDK version. However, I am with the latest plugin version and the SDK version is far more recent than the ones in such questions.

A month ago or so it was working without a glitch, so I wonder whether it is something due to an update.

Thanks

**Comment by pp-randy** [comment]
I apologize for the delay in following up.  Usually internal errors are intermittent. Please let us know if this issue is still ongoing.
