### ISSUE TITLE
Phonegap Build:  iTunes reject the plugin

### ISSUE THREAD

**Issue by Marix1** [paypal/PayPal-Cordova-Plugin#264]
iTunes reject the plugin with:

Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an **NSPhotoLibraryUsageDescription** key with a string value explaining to the user how the app uses this data. 

Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an **NSCameraUsageDescription** key with a string value explaining to the user how the app uses this data. 

What should I do the my app work again?

**Comment by jgabrielfaria** [comment]
Hi @Marix1!

This a requirement for the new iOS version.

Try to add this when adding de plugin:

```
cordova plugin add <plugin_name> --variable CAMERA_USAGE_DESCRIPTION="do something"
```

**Comment by pp-randy** [comment]
Closing the issue since a solution appears to be provided.  Thank you @jgabrielfaria.
