### ISSUE TITLE
Find App Client ID and Sandbox Client ID

### ISSUE THREAD

**Issue by fredroo** [paypal/PayPal-Cordova-Plugin#266]
Where find my Client ID in my paypal account and sandbox Client ID

**Comment by fredroo** [comment]
@braebot help, where find this ID's

**Comment by pp-randy** [comment]
You log into https://developer.paypal.com and click Dashboard on the top Right.  Then My Apps and Credentials which is this link https://developer.paypal.com/developer/applications/.  Scroll down to REST API Apps and click Create App.
![image](https://cloud.githubusercontent.com/assets/6819909/23661335/06493064-0312-11e7-9fac-16f9135f18b1.png)

Once the App is created it will have a toggle for sandbox and live and show the credentials.
![image](https://cloud.githubusercontent.com/assets/6819909/23661395/4743285e-0312-11e7-811e-e83c64a38778.png)


Please let me know if you need anything further.

**Comment by fredroo** [comment]
![image](https://cloud.githubusercontent.com/assets/6863089/23663085/eb991782-0327-11e7-9526-c522eea1a70b.png)
how fix this error?

**Comment by pp-randy** [comment]
Use the Sandbox -> Accounts link on the left of the error.  Create a business account.

**Comment by fredroo** [comment]
![account](https://cloud.githubusercontent.com/assets/6863089/23672541/d19466b8-034d-11e7-82c1-03253ced64e8.png)

@pp-randy create account business but not work to create rest api

my account is from Brazil

**Comment by fredroo** [comment]
![image](https://cloud.githubusercontent.com/assets/6863089/23672604/f93a0420-034d-11e7-945a-39d1e6d5921e.png)

**Comment by pp-randy** [comment]
It appears there is an error with the Brazil sandbox account creation that might be related.  Lets start tracking that here:  https://github.com/paypal/PayPal-REST-API-issues/issues/23

File a ticket at http://www.paypal-techsupport.com/ as well they may be able to provide additional help.
