### ISSUE TITLE
Phonegap Build v6.5.0 issue

### ISSUE THREAD

**Issue by maplerichie** [paypal/PayPal-Cordova-Plugin#268]
My config.xml 

    <preference name="android-build-tool" value="gradle"/>
    <preference name="android-minSdkVersion" value="19"/>
    <preference name="android-targetSdkVersion" value="19"/>

When building in Phonegap build, cli-6.5.0
The error msg: "Error - The minSdkVersion as specified in your config.xml (or the default value of 14) is less than required by a library included in your application: com.paypal.android.sdk.payments - You can fix this here"

**Comment by pp-randy** [comment]
@maplerichie were you able to resolve this issue?

**Comment by valgen** [comment]
I think I'm having the same issue while testing on Android. Did you manage to solve it? I'll follow the suggestion mentioned in the error message, but first I need to figure out how to do it.

`1>MSBUILD : cordova-build error : C:\Users\valin\Documents\Visual Studio 2015\Projects\BlankCordovaApp_Paypal\BlankCordovaApp_Paypal\platforms\android\AndroidManifest.xml:13:5-74 Error:
1>  C:\Users\xxxxxxxxx\Documents\Visual Studio 2015\Projects\BlankCordovaApp_Paypal\BlankCordovaApp_Paypal\platforms\android\AndroidManifest.xml:13:5-74 Error
1>MSBUILD : cordova-build error :  uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.paypal.sdk:paypal-android-sdk:2.15.3] C:\Users\xxxxxxxxx\Documents\Visual Studio 2015\Projects\BlankCordovaApp_Paypal\BlankCordovaApp_Paypal\platforms\android\build\intermediates\exploded-aar\com.paypal.sdk\paypal-android-sdk\2.15.3\AndroidManifest.xml
1>  	uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.paypal.sdk:paypal-android-sdk:2.15.3] C:\Users\xxxxxxxxx\Documents\Visual Studio 2015\Projects\BlankCordovaApp_Paypal\BlankCordovaApp_Paypal\platforms\android\build\intermediates\exploded-aar\com.paypal.sdk\paypal-android-sdk\2.15.3\AndroidManifest.xml
1>MSBUILD : cordova-build error :  Suggestion: use tools:overrideLibrary="com.paypal.android.sdk.payments" to force usage
1>  	Suggestion: use tools:overrideLibrary="com.paypal.android.sdk.payments" to force usage`

**Comment by valgen** [comment]
I've found this..
[https://github.com/paypal/PayPal-Android-SDK/blob/master/README.md#override-minsdkversion](https://github.com/paypal/PayPal-Android-SDK/blob/master/README.md#override-minsdkversion)

**Comment by pp-randy** [comment]
@valgen did your findings resolve this?  Are you trying to use minSdk 14? 

If not you could specify 16 in the config XML
```
    <platform name="android">
        <preference name="android-minSdkVersion" value="14" />
    </platform>
</widget>
```

**Comment by maplerichie** [comment]
@pp-randy If not mistaken, it having conflict with phonegap-barcode-scanner plugin. Sorry, i manage to solved it month ago by trying different plugin combination. So i cant remember what combination is it

**Comment by maplerichie** [comment]
<plugin name="com.paypal.cordova.mobilesdk" source="npm"/>
 -    <plugin name="phonegap-plugin-barcodescanner" source="npm">
 +    <plugin spec="https://github.com/phonegap/phonegap-plugin-barcodescanner.git" source="git">

@pp-randy 
After check the commit history, i think is this issue, "com.paypal.cordova.mobilesdk" conflict with that release of "phonegap-plugin-barcodescanner", then it solved after pull from git

**Comment by valgen** [comment]
@pp-randy Thank you for your suggestion. My intention is to use 16 so I've added this code in my cordova config.xml and it worked straight away:

```
<platform name="android">
    <preference name="android-minSdkVersion" value="16" />
</platform>
```
