### ISSUE TITLE
PayPal Payouts

### ISSUE THREAD

**Issue by richardmarais** [paypal/PayPal-Cordova-Plugin#271]
* Environment:  Sandbox and Production
* Platforms: Both iOS and Android

My app needs to be able to **send and receive** payments to/from **other `PayPal` accounts**.

Is there a way for a Mobile App (`Facilitator`) to allow a `Payer` to make a payment to a `Payee`?

I have looked at the PayPal API's, and I can find how to facilitate a `Payer` to make a payment a `Payee`, if the `Payee` is the `Facilitator`. As then it can register the `Payees` PayPal client Id.  But in my case, the `Payee` does not supply their PayPal client Id (`Facilitator` & `Payee` are separate entities). i.e. The `Payee` is another PayPal Account.

[![enter image description here][1]][1]

It looks like [PayPal Payouts](https://developer.paypal.com/docs/api/payments.payouts-batch) allow payments to another PayPal account.

I would like to make a request to integrate this functionality.

  [1]: https://i.stack.imgur.com/ZECN2.png

**Comment by pp-randy** [comment]
With the REST API you can specify a payee to receive the payment.  We have an open pull request tracking this feature here https://github.com/paypal/PayPal-Cordova-Plugin/pull/232

Please follow the above pull request for further tracking. 

I apologize for the delay.  Closing this issue in favor of the above, but please let me know if you need further assistance.
