### ISSUE TITLE
Cannot find name 'PayPal'.

### ISSUE THREAD

**Issue by fredroo** [paypal/PayPal-Cordova-Plugin#273]
https://ionicframework.com/docs/v2/native/paypal/

```
$ ionic plugin add com.paypal.cordova.mobilesdk
$ npm install --save @ionic-native/paypal
```

import { PayPal, PayPalPayment, PayPalConfiguration } from '@ionic-native/pay-pal';

constructor(private payPal: PayPal) { }

Cannot find name 'PayPal'.

**Comment by fredroo** [comment]
solved

https://ionicframework.com/docs/v2/native/paypal/

in this page show this:
import { PayPal, PayPalPayment, PayPalConfiguration } from '@ionic-native/pay-pal';

but is:
import { PayPal, PayPalPayment, PayPalConfiguration } from '@ionic-native/paypal';

without slash

**Comment by dfa1234** [comment]
Your message is totally incomprehensible!
I have the same problem.

**Comment by pp-randy** [comment]
@dfa1234 what error are you getting?  I fixed the above comment to show the solution from @fredroo if it helps.

**Comment by dfa1234** [comment]
Thanks, but it was not the dash
The error is during the build (I mean the `ionic cordova build ios`)
I get `Cannot find name 'PayPal'.` as a compliation error (the aot compilation)
I will try again when I will be on mac

**Comment by xiaoleih41** [comment]
@dfa1234 Just want to point out that this plugin has been deprecated as it is stated in the README.MD. If you haven't got to the production stage, please consider to integration express checkout via braintree SDK or Braintree Direct.
