### ISSUE TITLE
currency BRL not work

### ISSUE THREAD

**Issue by fredroo** [paypal/PayPal-Cordova-Plugin#276]
Hi, try pay with BRL currency but not work

**Comment by fredroo** [comment]
@pp-randy how pay with BRL currency from this plugin

**Comment by pp-randy** [comment]
Some notes on BRL it can only be used with Brazil Buyer and Merchant.

https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/
> This currency is supported as a payment currency and a currency balance for in-country PayPal accounts only.


What is happening in your testing? An error or is it simply not using BRL?

**Comment by fredroo** [comment]
show this error: (pp_service_error_bad_currency)

**Comment by fredroo** [comment]
![erro paypal github](https://cloud.githubusercontent.com/assets/6863089/24625138/705e60a0-1884-11e7-8b51-b851ff977a3e.png)

**Comment by pp-randy** [comment]
Do you have more information like a debug id?  

You are using your Client ID for your Brazil Merchant?

**Comment by pp-randy** [comment]
I'm going to run some tests as well with a Brazil Rest app to see if I can reproduce.

**Comment by pp-randy** [comment]
Using the sample app with my Brazil Rest app this is working for me 
`var payment = new PayPalPayment("50.00", "BRL", "Awesome Sauce", "Sale", paymentDetails);`

I changed USD to BRL and it worked.   I also used another Brazil account as the buyer.

**Comment by fredroo** [comment]
i am using this: https://ionicframework.com/docs/native/paypal/

but with import: 

import { PayPal, PayPalPayment, PayPalConfiguration } from '@ionic-native/paypal';

**Comment by fredroo** [comment]
![whatsapp image 2017-04-03 at 17 22 23](https://cloud.githubusercontent.com/assets/6863089/24630227/4011d766-1892-11e7-8808-19de58e91102.jpeg)

**Comment by fredroo** [comment]
USD work but BRL not

**Comment by pp-randy** [comment]
BRL is not supported for a direct credit card payments.  This will only work between two Brazil PayPal accounts for BRL currency and the Pay with PayPal option.

**Comment by fredroo** [comment]
pay with paypal account also not work

try login but not work, show error login, but my password and email is right

**Comment by fredroo** [comment]
@pp-randy is possible add both in new version of this plugin?

**Comment by pp-randy** [comment]
This is a PayPal Payment limitation regarding BRL and not related to the plugin. 

What is the email address of your sandbox buyer account?
What is the email address associated to your sandbox merchant account?
What are you putting in for the client id sandbox value in the [ionic guide ](https://ionicframework.com/docs/native/paypal/)?
```
this.payPal.init({
  PayPalEnvironmentSandbox: "YOUR_SANDBOX_CLIENT_ID"
}).
```
You are using sandbox as environment too? 
```
this.payPal.prepareToRender('PayPalEnvironmentSandbox'
```

**Comment by fredroo** [comment]
my email merchant is: financeiro@livetechtecnologia.com.br, buyer is: jose.frederico@outlook.com

use sandbox ID from rest api app

**Comment by pp-randy** [comment]
I can't find your buyer account in sandbox.  Double check here: https://developer.paypal.com/developer/accounts/

**Comment by pp-randy** [comment]
Can you use the link above and create a new Brazil Buyer account?  Lets see if that gets things working for you.

**Comment by fredroo** [comment]
![paypal error](https://cloud.githubusercontent.com/assets/6863089/24633866/20e7cfda-18a1-11e7-866b-bbc065af5add.png)

try with BR and US accounts not work with both

**Comment by pp-randy** [comment]
You need to create a Brazil Personal Account to test the PayPal payment.

**Comment by fredroo** [comment]
I have Brazil account since 2009 try pay but not work

**Comment by pp-randy** [comment]
That is probably a live account, you need to create a sandbox one just like you did for the Business Account you are showing.

**Comment by fredroo** [comment]
i create and use sandbox until now

**Comment by pp-randy** [comment]
Your financeiro-buyer is showing an error status.  Can you try with a new Brazil Buyer sandbox account?

**Comment by fredroo** [comment]
yes same error bad currency

**Comment by pp-randy** [comment]
What is the email address of the new Brazil Buyer sandbox account you created?

**Comment by fredroo** [comment]
jose.frederico@outlook.com

**Comment by fredroo** [comment]
@pp-randy help me, i need this in this week for publish my app in google play store

**Comment by pp-randy** [comment]
I see you created a new Brazil Buyer account, it had an issue.  Try another Brazil Business and use it as your buyer, don't remove your current business. We resolved bank issues with business accounts and most likely need to look at buyer accounts further.

**Comment by pp-randy** [comment]
Also the buyer account you created was jose.frederico-buyer@outlook.com, don't confuse buyer account with your Live PayPal login.

**Comment by pp-randy** [comment]
@fredroo any updates on the new account?   I apologize you are having to use a workaround and use a business as a buyer, but it should work.

**Comment by fredroo** [comment]
this time create a new buyer BR account but login failed, but same email and password work in browser

**Comment by pp-randy** [comment]
Does the login in the app for paypal show sandbox at the bottom?

**Comment by fredroo** [comment]
![whatsapp image 2017-04-04 at 20 56 52](https://cloud.githubusercontent.com/assets/6863089/24684022/770c02c2-1979-11e7-8907-370db00b9e5d.jpeg)

yes look

**Comment by pp-randy** [comment]
Try this account
user: gh_cordova_276@test.com
pass: 11111111

**Comment by fredroo** [comment]
work very fine with this account

**Comment by pp-randy** [comment]
Do you want me to transfer it to you?

**Comment by pp-randy** [comment]
Let me know I am happy to move this account to your developer account.  Otherwise, I think we've finally resolved the issue 👍.

**Comment by fredroo** [comment]
@pp-randy use this account to pay not to rest api, please back account to try with rest api app

**Comment by pp-randy** [comment]
Yes, you use that account to pay with in sandbox. 

I apologize I don't understand, what else do you need?

**Comment by fredroo** [comment]
i use this account
user: gh_cordova_276@test.com
pass: 11111111

pay in sandbox, works fine

but with my Brazilian account jose.frederico@outlook.com not work
and my another account social@reciklado.com also brazilian account not work

**Comment by fredroo** [comment]
@pp-randy reopen this request

**Comment by pp-randy** [comment]
You can log into https://www.sandbox.paypal.com with those? I think you are trying with production accounts.

**Comment by fredroo** [comment]
with this account yes: gh_cordova_276@test.com

but my problem is pay com brazilian account jose.frederico@outlook.com or social@reciklado.com, first show bad currency, second login failed

**Comment by pp-randy** [comment]
Those are both live accounts and you cannot use them for testing transactions in the sandbox.  Sandbox has its own accounts you create them here https://developer.paypal.com/developer/accounts/ once you log into the PayPal Developer site.

**Comment by fredroo** [comment]
thank very much @pp-randy now i understand 

works very well

more one question

people for example from USA go pay with credit card directly

**Comment by pp-randy** [comment]
Brazil Accounts cannot accept credit card payments in REST.  Nor could you charge someone in USA an about with BRL, because only Brazil Accounts are able use BRL.  You might be able to charge them in USD however.  You should discuss with the Brazil Sales team shown here https://www.paypal.com/br/webapps/mpp/merchant  they would be more knowledgeable for what your options are.
