### ISSUE TITLE
I am not been able to get payment in Indian Currency

### ISSUE THREAD

**Issue by mihirp1730** [paypal/PayPal-Cordova-Plugin#277]
How can i get payments in Indian currency?
What is the solution of this problem?

### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Platforms: 
* Device OS Version and Device:

**Comment by xiaoleih41** [comment]
Indian Currency is not supported in PayPal REST API. Please refer to [ this page ](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/) for supported currency. Thanks.
