### ISSUE TITLE
Pay with Credit Card in BRL currency

### ISSUE THREAD

**Issue by fredroo** [paypal/PayPal-Cordova-Plugin#278]
please developers from paypal

i need this funcionality 

please add from Brazilian Account clients pay with credit card with currency BRL

**Comment by fredroo** [comment]
@pp-randy please open a ticket for this

**Comment by fredroo** [comment]
@bluk please help me

**Comment by xiaoleih41** [comment]
@fredroo Adding a currency is more than a product enhancement. It is limited by the country's currency policy as well as the card processing policy with PayPal's financial partners. Processing **BRL credit card payments** unfortunately cannot be supported at this time.
