### ISSUE TITLE
Paypal Adaptive Chained Payment

### ISSUE THREAD

**Issue by Amarjit1234** [paypal/PayPal-Cordova-Plugin#280]
Hi ,

Is this possible by using this PayPal cordova plugin to execute the adaptive chained payment. If this is possible then please help me.

Thanks

**Comment by xiaoleih41** [comment]
The PayPal version of Cordova plugin is build on mobile SDK only which doesn't support adaptive payment. However there's an [ paypal adaptive MPL version ](https://cordova.apache.org/plugins/?q=paypal) out there which is not built or supported by PayPal. However, please feel free look into this.

**Comment by Amarjit1234** [comment]
Thanks for the feedback.

*Best Regards,*

*Amarjit Prasad*

*Web Developer**.*
Brainium Information Technologies Pvt. Ltd.

www.brainiuminfotech.com | www.hireoutsourcingteam.com

*Phone: **033-40044560*

Skype: amarjit.brainium

*Twitter* <https://twitter.com/BrainiumIT>* | **Facebook*
<https://www.facebook.com/BrainiumInformationTechnologiesPvtLtd>* | *
*LinkedIn*
<https://www.linkedin.com/company/brainium-information-technologies-pvt-ltd->
