### ISSUE TITLE
gives system error: please try agin

### ISSUE THREAD

**Issue by Poojal123** [paypal/PayPal-Cordova-Plugin#282]
### General information

using paypal 3.5.0 version SDK library

* SDK/Library version: 
* Environment: sandbox
* `PayPal-Debug-ID` values: 

{
	"status": 400,
	"duration_time": 245,
	"body": {
		"message": "PayPal-Request-Id header was already used.",
		"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#DUPLICATE_REQUEST_ID",
		"name": "DUPLICATE_REQUEST_ID",
		"debug_id": "160ae1488f2e5"
	},
	"additional_properties": {},
	"header": {
		"Date": "Thu, 08 Jun 2017 10:41:10 GMT",
		"paypal-debug-id": "160ae1488f2e5",
		"APPLICATION_ID": "APP-80W284485P519543T",
		"Content-Language": "*",
		"CALLER_ACCT_NUM": "5L2H5Z3WB9WY6"
	}
}
* Platforms: android and ios
* Device OS Version and Device: ios 10 and lolipop android 

### Issue description

im integrating paypal in ionic 2.2.2. it works grate. but when im making payment gives me system error: please try later.

i have followed official doc of ionic 2 to integrating in ionic app..

when i check the request in paypals sandbox account API calls  it give status code 400 

{
	"status": 400,
	"duration_time": 245,
	"body": {
		"message": "PayPal-Request-Id header was already used.",
		"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#DUPLICATE_REQUEST_ID",
		"name": "DUPLICATE_REQUEST_ID",
		"debug_id": "160ae1488f2e5"
	},
	"additional_properties": {},
	"header": {
		"Date": "Thu, 08 Jun 2017 10:41:10 GMT",
		"paypal-debug-id": "160ae1488f2e5",
		"APPLICATION_ID": "APP-80W284485P519543T",
		"Content-Language": "*",
		"CALLER_ACCT_NUM": "5L2H5Z3WB9WY6"
	}
}

**Comment by xiaoleih41** [comment]
Please share your complete API request minus password. Are you trying to make credit card payment or PayPal payment?

**Comment by Poojal123** [comment]
@xiaoleih41 
hi i have resolved this problem.. actually problem is my account is not created correctly..

i have a new issue now..


i want to send some extra information to paypal like name address item name etc im sending with shippinAddress but in paypal not getting it..

**Comment by xiaoleih41** [comment]
Can you share your code and what kind of error have you got? What's the `debugId` in the response?

**Comment by xiaoleih41** [comment]
Close this ticket due to inactivity. Please resubmit if you have further questions.
