### ISSUE TITLE
i have a app where use can add multiple products and checkout.how can i integrate

### ISSUE THREAD

**Issue by techashish12** [paypal/PayPal-Cordova-Plugin#283]
the product is based on the magento api

**Comment by xiaoleih41** [comment]
Please contact the customer service number listed on your account, they will help you to choose the right product and may assign tech support to you to give you guidance on the integration.

**Comment by xiaoleih41** [comment]
Close this ticket as it's a non-SDK question. The correct assistant resource has been provided.
