### ISSUE TITLE
Can I user this plugin to make transaction between two different users using my app? 

### ISSUE THREAD

**Issue by sharjeel619** [paypal/PayPal-Cordova-Plugin#284]
I am implementing a functionality in which two users will be able to make a certain transaction. Any help would be greatly appreciated.

**Comment by pp-randy** [comment]
With the pull request https://github.com/paypal/PayPal-Cordova-Plugin/pull/232 you can specify a payee (receiver).  The buyer would be the phone user in most cases with this approach.

**Comment by sharjeel619** [comment]
If I don't specify a payee then where does the money go to. Is it the account I have used in my app from which I specify my the clientbox and the production id in the indes.js file?

**Comment by xiaoleih41** [comment]
Yes, it will go to the APP account.

**Comment by sharjeel619** [comment]
@xiaoleih41 Thanks. And just to confirm if I specify a payee email address, then the payment would go to that account right?

**Comment by xiaoleih41** [comment]
@sharjeel619 Yes, it should be.

**Comment by sharjeel619** [comment]
@xiaoleih41  I am experiencing sth wierd and that is when I login with incorrect credentials. It still Logs me in and gives a status of approved in the callback object. Do you know any fix for that?

**Comment by xiaoleih41** [comment]
Can I provide more detail into the situation? I don't quite understand you mean by logging in with incorrect credentials.

**Comment by sharjeel619** [comment]
If I enter a wrong password for my paypal account by email. It still logs me in.

**Comment by pp-randy** [comment]
What environment are you using?  Please send a screen shot of the full log in screen.

**Comment by sharjeel619** [comment]
@pp-randy I am using android (5.1.1) on a Lenovo Vibe K5 plus smartphone. By the way I checked with the original paypal and sandbox accounts. It still logs me in and when I pay it returs a success msg. I am attaching the necessary screenshots. Maybe i am using the wrong production and sandbox keys. I am using the keys user Client Id.
![live id](https://user-images.githubusercontent.com/11159443/28413428-e4f46802-6d60-11e7-8c71-be62f200cf57.JPG)
![sandbox id](https://user-images.githubusercontent.com/11159443/28413429-e4f5f866-6d60-11e7-9e67-c198c6c734da.JPG)
![screenshot_2017-07-20-15-14-31](https://user-images.githubusercontent.com/11159443/28413623-b5d828b4-6d61-11e7-8828-e5c6054c57f6.png)

**Comment by pp-randy** [comment]
That is the simulator and does not use the sandbox or live information.

For sandbox try `PayPalMobile.prepareToRender("PayPalEnvironmentSandbox", app.configuration(), app.onPrepareRender);`

Let me know if you have further questions.

**Comment by sharjeel619** [comment]
If this is a simulator. Then I how do I use the real thing using this plugin/ I followed the exact code that is written in the index.js file of this plugin

**Comment by sharjeel619** [comment]
@pp-randy Exactly, What am I doing wrong?

**Comment by pp-randy** [comment]
Provide your PayPalMobile.prepareToRender line of code please.

**Comment by pp-randy** [comment]
The blue box will say Sandbox when we get you configured correctly.  It won't show the blue box on live.

![image](https://user-images.githubusercontent.com/6819909/28428531-485b71aa-6d3f-11e7-92b7-172c152f53e2.png)

**Comment by sharjeel619** [comment]
You were right the issue was on that line. Thank you very much. But now how do I move this sandbox version to live version and how do I remove the sandbox button?

**Comment by sharjeel619** [comment]
I am also noticing that you cannot log in with the real paypal email account, only those which include "-buyer" which is a sandbox account, I believe . I am assuming that's because this is a sandbox environment so far.

**Comment by pp-randy** [comment]
For Live use: `PayPalEnvironmentProduction`

Sandbox accounts are separate from live account. You can create new sandbox test accounts here: https://developer.paypal.com/developer/accounts/

**Comment by sharjeel619** [comment]
So I have to use only one of these variables. And not both?
![capture](https://user-images.githubusercontent.com/11159443/28431062-48577b92-6d9c-11e7-8af6-9fcf3902c59b.JPG)

**Comment by pp-randy** [comment]
It the value in prepareToRender for Production. 
`PayPalMobile.prepareToRender("PayPalEnvironmentProduction",...`

**Comment by sharjeel619** [comment]
Yup, Got it. Thank you for helping me. One last thing in profile sharing button. After I click agree it gives me a msg: "Consent Failed. An error has occured". It does that for both live and sandbox accounts.

**Comment by pp-randy** [comment]
Can you capture any additional logs for this?  A  PayPal Debug-ID would be helpful. 

I usually just launch Android Studio and take a look with Logcat
![image](https://user-images.githubusercontent.com/6819909/28432240-db8015c8-6d4c-11e7-8e5b-4535b7f53d35.png)

**Comment by sharjeel619** [comment]
I don't have android studio. Is there any other way I can get that. Maybe through some code?

**Comment by pp-randy** [comment]
I haven't used Logcat with command line but you could give it a go https://developer.android.com/studio/command-line/logcat.html
