### ISSUE TITLE
payeeEmail TypeScript error 

### ISSUE THREAD

**Issue by FlexXxa** [paypal/PayPal-Cordova-Plugin#287]
### General information

* Environment: Sandbox
* Cordova version: 7.0.1
* Ionic version: 3.70.
* ionic-native/paypal: 4.1.0
* Platforms: Android
* Device OS Version and Device:  Android Marshmallow (7.1.1) on Nexus 5 

### Issue description

Hello,

I am using the PayPal-Cordova-Plugin in my App. The transaction between the user and the PayPal Sandbox Account works well. 

When I want to send the money to a different PayPal account with the 'payeeEmail' ,defined from an input field, an error of TypeScript occurs. 

Typescript error: Property 'payeeEmail' does not exist on type 'PayPalPayment'.

`import { PayPal, PayPalPayment, PayPalConfiguration } from 'ionic-native';`

`var payment = new PayPalPayment('10.10', 'USD', 'TV', 'sale');`
* I can change the amount of the transaction and my app is showing the new price of 20 USD.
`payment.amount = '20.00';`

* Here occurs the TS error 2339. 'payeeEmail' is no type of 'PayPalPayment'
`payment.payeeEmail("newEmail@test.com");`

Can you help me with this problem? I don't know what i am doing wrong. 

Thanks a lot!

**Comment by pp-randy** [comment]
What version is the PayPal Plugin?  Payee email was added in https://github.com/paypal/PayPal-Cordova-Plugin/releases/tag/3.5.0 with https://github.com/paypal/PayPal-Cordova-Plugin/pull/232

**Comment by FlexXxa** [comment]
`@ionic-native/paypal 4.1.0` is my current version

I was looking in the Ionic/PayPal Doc on https://ionicframework.com/docs/native/paypal/

I can't find the Instance Member 'payeeEmail'.  The other Instance Member like 

- amount()
- shortDescription()
- bnCode()
- ...

are working.

**Comment by pp-randy** [comment]
My understanding would be the ionic wrapper is not updated to the current release of this SDK.  I will escalate internally and see if someone is familiar with the process.

**Comment by jaypatel512** [comment]
Can you please double check if setting payeeEmail like this works:

```
payment.payeeEmail = "newEmail@test.com";
```
It feels like you are calling payeeEmail as a method, instead of a variable to be set there. I am looking into why the ionic docs are not update with it.

**Comment by FlexXxa** [comment]
Thank you so much!

**Comment by FlexXxa** [comment]
Hey @jaypatel512 ! Thanks for the PM.

I tried `payment.payeeEmail = "newEmail@test.com";` also, but the same error of TypeScript occurs.

**Comment by FlexXxa** [comment]
Hey @jaypatel512<https://github.com/jaypatel512> ! Thanks for the PM.

I tried payment.payeeEmail = "newEmail@test.com"; also, but the same error of TypeScript occurs.

________________________________
Von: Jay [notifications@github.com]
Gesendet: Dienstag, 8. August 2017 23:12
An: paypal/PayPal-Cordova-Plugin
Cc: Gördes, Marius; Author
Betreff: Re: [paypal/PayPal-Cordova-Plugin] payeeEmail TypeScript error (#287)


Can you please double check if setting payeeEmail like this works:

payment.payeeEmail = "newEmail@test.com";


It feels like you are calling payeeEmail as a method, instead of a variable to be set there. I am looking into why the ionic docs are not update with it.

**Comment by pp-randy** [comment]
Ionic needs to accept the pull request before this can be resolved. 

Please follow the pull request to them here https://github.com/ionic-team/ionic-native/pull/1872.  

Closing this issue, please let us know if you still have a problem after the above is merged by them.
