### ISSUE TITLE
Issuing refunds

### ISSUE THREAD

**Issue by kaashmonee** [paypal/PayPal-Cordova-Plugin#288]
### General information

* SDK/Library version:   3.5.0
* Environment:  Sandbox
* `PayPal-Debug-ID` values: 
* Platforms:  Ionic (iOS/Android)
* Device OS Version and Device:  iOS 9.x on iPhone 6, Nexus 5, Android 6.0

### Issue description

Looking at the documentation, I found no way to issue refunds to people. After looking through PayPal's documentation, it said they were looking for a "sale id," but this plugin returns only a response id which begins with "PAY," which apparently is not the correct one. Is there a way to implement this?

**Comment by pp-randy** [comment]
You will probably need a server side integration for refunds.  You can lookup the sale id, if you created a sale by looking up the payment and searching the related resources https://developer.paypal.com/docs/api/payments/#payment_get.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.
