### ISSUE TITLE
Payment Failed: System error. Please try again later.

### ISSUE THREAD

**Issue by ykpoh** [paypal/PayPal-Cordova-Plugin#290]
### General information

* SDK/Library version: 3.5.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Platforms: Android
* Device OS Version and Device: Android 7 on Nexus 5X (Emulator)

### Issue description
I have tested my app using the **Pay With Card** option with the test credit card number 5555555555554444 with CCV 123 & Expiry date: 12/20 from [this link](https://www.paypalobjects.com/en_US/vhelp/paypalmanager_help/credit_card_numbers.htm)

It shows **Payment Failed: System error. Please try again later.** sometimes:
![screenshot_1502432292](https://user-images.githubusercontent.com/8528166/29203243-25cdc222-7ea2-11e7-972d-64851ce26e01.png)

But, when I checked the PayPal Business test account in the **PayPal sandbox dashboard**, the transaction is shown as **completed** like this:
![1](https://user-images.githubusercontent.com/8528166/29203301-880aea5a-7ea2-11e7-8406-4474ce1e6511.PNG)

Sometimes it works normally, sometimes it doesn't and show me this error, what is the cause of this problem? Is there a fix or a quick hack to bypass it?

**Comment by pp-randy** [comment]
This is a problem when using the Payflow test cards.  

Please see https://github.com/paypal/PayPal-REST-API-issues/issues/22, which will have a link to a credit card generator in the top comment.

**Comment by ykpoh** [comment]
Thanks a lot! Myproblem is solved!
