### ISSUE TITLE
Brazil implementation

### ISSUE THREAD

**Issue by fredroo** [paypal/PayPal-Cordova-Plugin#291]
please conctact brazil support to update with paypal brazil

**Comment by fredroo** [comment]
@pp-randy please help me

**Comment by pp-randy** [comment]
What is going on @fredroo?  What is not working for you?

**Comment by fredroo** [comment]
paypal brazil rest api not work with this plugin

**Comment by pp-randy** [comment]
What error are you getting?  If you are on Android you can use LogCat to capture the error https://developer.android.com/studio/command-line/logcat.html

**Comment by pp-randy** [comment]
To my knowledge you should to send BRL currency for PayPal payments if both accounts are in Brazil.  You can't use credit cards though.

**Comment by fredroo** [comment]
yes work with BRL but not work with brazillian credit cards

**Comment by fredroo** [comment]
if possible call to brazillian developers to help with this integration

**Comment by pp-randy** [comment]
Direct Credit Card payments will not work for Brazil with the REST API.  If the Brazil account has a credit card funding source then that should work.  However, I'm not aware of specific country limitations.  I think you should discuss integration options with the Brazil Sales team found here: https://www.paypal.com/br/webapps/mpp/merchant

**Comment by xiaoleih41** [comment]
Close this issue as the question and further assistance direction has been provided.
