### ISSUE TITLE
Ionic Build: Invalid binary when sending to iTunes

### ISSUE THREAD

**Issue by dennerevaldt** [paypal/PayPal-Cordova-Plugin#292]
### General information

* SDK/Library version: 3.5.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Platforms:  Ionic(iOS)
* Device OS Version and Device: iOS 9.x on iPhone 6

### Issue description

I am using the plugin with latest ionic, i added it to the project with the command `ionic cordova plugin add com.paypal.cordova.mobilesdk --variable CAMERA_USAGE_DESCRIPTION = "do something"` however when i go up to itunes i get the message _Invalid binary_, and if remove the plugin and resubmit itunes it succeeds, what can it be?

**Comment by bluk** [comment]
Sorry for the late reply. For anyone that encounters this error, the iTunes Connect app should have emailed you with more details. Did you get an email and if there's a more specific error, we may be able to assist with that?

**Comment by xiaoleih41** [comment]
Close this issue due to inactivity.

**Comment by dennerevaldt** [comment]
@bluk I did not receive email

**Comment by dennerevaldt** [comment]
I did not receive email @bluk

**Comment by bluk** [comment]
Unfortunately without more specific information, it is difficult to diagnose. Usually the email would say if for instance you need to have a different version number. If you are using card.io for credit card scanning, I would verify the Info.plist has the correct `NSCameraUsageDescription` value set. See https://github.com/card-io/card.io-Cordova-Plugin#integration-instructions .

Note that the PayPal Mobile SDKs are deprecated so if you haven't done a release, you should look into [PayPal Express Checkout with Braintree SDKs](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/).
