### ISSUE TITLE
Issues installing the plugin

### ISSUE THREAD

**Issue by pdc95** [paypal/PayPal-Cordova-Plugin#295]
### General information

* SDK/Library version: latest
* Environment: Sandbox
* `PayPal-Debug-ID` values: n/a
* Platforms: iOS/Android and Browser for debug
* Device OS Version and Device: iOS > 9.0 and Android > 6.0

### Issue description

Trying to install the plugin i received the following error:
Error: Cordova does not know  plugin add com.paypal.cordova.mobilesdk; try `cordova help` for a list of all the available commands.

the updating Cordova i tried again but is not possible to install the plugin due errors for the Browser platform:

Unable to load PlatformApi from platform. Error: Cannot find module '[...]\platforms\browser\cordova\Api.js'
Failed to install 'card.io.cordova.mobilesdk': Error: Uncaught, unspecified "error" event. (The platform "browser" does not appear to be a valid cordova platform. It is missing API.js. browser not supported.)

how can i test and debug the app in browser with this plugin? am i forced to remove the browser Platform?

**Comment by xiaoleih41** [comment]
Both PayPal-iOS-SDK and PayPal-Android-SDK have been deprecated. Please find more detail [here](https://developer.paypal.com/docs/integration/mobile/mobile-sdk-overview/#paypal-mobile-sdks).

**Comment by pdc95** [comment]
I need Chained Payments and Braintree is not supporting them.
Braintree Marketplace is but it is available in US only.
So i need tu use the standard SDK or MPL.. How can i do that?

**Comment by xiaoleih41** [comment]
Please look into [PayPal for Marketplaces]( https://developer.paypal.com/docs/marketplaces/pp4mp/). It's for global clients.

**Comment by xiaoleih41** [comment]
Close the issue as the answer has been provided.
