### ISSUE TITLE
Query: Is it accept the payments from Paypal Pro? In my case, Paypal standard is working but paypal pro is not.

### ISSUE THREAD

**Issue by Simerjit-developer** [paypal/PayPal-Cordova-Plugin#296]
Query: Is it accept the payments from Paypal Pro? In my case, Paypal standard is working but paypal pro is not.

**Comment by xiaoleih41** [comment]
Direct credit card feature has been deprecated from REST API. Please consider to integrate Braintree SDK from braintreepayments.com for direct credit card processing needs.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.
