### ISSUE TITLE
UI keeps rending NoNetwork version despite changing config

### ISSUE THREAD

**Issue by motatoes** [paypal/PayPal-Cordova-Plugin#297]
### General information
My app keeps rending in `noNetwork` mode despite changing the parameter to `sandbox` and `production`

* SDK/Library version: 3.22
* Environment: Sandbox
* `PayPal-Debug-ID` values: N/A
* Platforms: iOS
* Device OS Version and Device: iPhone 6s Plus iOS 9.3 (simulator)

### Issue description

I use the following to render my payment within my app:

```
          window.PayPalMobile.prepareToRender("PayPalEnvironmentSandbox", this.configuration(), this.onPrepareRender.bind(this));
```

I have also tried using `PaypalEnvironmentProduction`, however, despite changing the configuration, the UI keeps rending in the mock version and I get the payment detiails bellow:

```
payment success: {
    "client": {
        "environment": "mock",
        "product_name": "PayPal iOS SDK",
        "paypal_sdk_version": "2.17.0",
        "platform": "iOS"
    },
    "response_type": "payment",
    "response": {
        "id": "PAY-NONETWORKPAYIDEXAMPLE123",
        "state": "approved",
        "create_time": "2017-10-25T12:22:21Z",
        "intent": "sale"
    }
}
```

![simulator screen shot - iphone 6s plus - 2017-10-25 at 13 27 55](https://user-images.githubusercontent.com/1627972/32001013-63032bc2-b990-11e7-9e7c-c7bee97154cd.png)
![simulator screen shot - iphone 6s plus - 2017-10-25 at 13 27 51](https://user-images.githubusercontent.com/1627972/32001018-665285c0-b990-11e7-80c7-8961a8352c93.png)

**Comment by xiaoleih41** [comment]
What 'client ID' did you use for this app?

**Comment by xiaoleih41** [comment]
Close due to inactivity. Please resubmit when you have additional info that was requested.
