### ISSUE TITLE
Plugin installation issue on cordova version 7.1.0

### ISSUE THREAD

**Issue by trishanet** [paypal/PayPal-Cordova-Plugin#299]
### General information

* SDK/Library version: 
* Environment: Both Sandbox and Production
* `PayPal-Debug-ID` values: 
* Platforms: Android
* Device OS Version and Device:  Android Marshmallow

### Issue description
We are facing this issue.

D:\pay>cordova plugin add com.paypal.cordova.mobilesdk
Error: Failed to fetch plugin com.paypal.cordova.mobilesdk via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm WARN retry will retry, error on last attempt: Error: EBUSY: resource busy or
 locked, rename 'C:\Users\Rakesh\AppData\Local\Temp\npm-344-8f3b50a5\registry.np
mjs.org\com.paypal.cordova.mobilesdk\-\com.paypal.cordova.mobilesdk-3.5.0.tgz.40
81247375' -> 'C:\Users\Rakesh\AppData\Local\Temp\npm-344-8f3b50a5\registry.npmjs
.org\com.paypal.cordova.mobilesdk\-\com.paypal.cordova.mobilesdk-3.5.0.tgz'
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "com.paypal.cordova.mobilesdk" "--
production" "--save"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10

npm ERR! tarball.destroy is not a function
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN com.example.pay@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "com.paypal.cordova.mobilesdk" "--
production" "--save"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10

npm ERR! Callback called more than once.
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\pay\npm-debug.log

**Comment by bluk** [comment]
The error: ```EBUSY: resource busy or
locked, rename 'C:\Users\Rakesh\AppData\Local\Temp\npm-344-8f3b50a5\registry.np
mjs.org\com.paypal.cordova.mobilesdk-\com.paypal.cordova.mobilesdk-3.5.0.tgz.40
81247375' -> 'C:\Users\Rakesh\AppData\Local\Temp\npm-344-8f3b50a5\registry.npmjs
.org\com.paypal.cordova.mobilesdk-\com.paypal.cordova.mobilesdk-3.5.0.tgz'```

seems to be a machine specific error. Have you tried this on a different machine or made sure that you have disk space and the correct disk permissions?

**Comment by bluk** [comment]
Also, this SDK has been deprecated so I would try to use the [Express Checkout with Braintree SDKs](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/) if possible. There isn't an official Cordova plugin, but it is the preferred underlying SDK to work with for mobile.

**Comment by xiaoleih41** [comment]
Close due to inactivity
