### ISSUE TITLE
Ionic 3 error, exec proxy not found for :: PayPalMobile :: init

### ISSUE THREAD

**Issue by HarounOujihi** [paypal/PayPal-Cordova-Plugin#301]
Hi,
I follow the steps to install and work with PayPal-Cordova-Plugin from here
https://ionicframework.com/docs/native/paypal/ 

and everything goes ok !
But when i run the command : ionic cordova run browser
 i got this error :

**Error: exec proxy not found for :: PayPalMobile :: init**
( Missing Command Error cdv-plugin-paypal-mobile-sdk.js:41 )

and even when i try it on my android device i get the same problem :(

can any one help me to understand what happen and what wrong i have done !?

@bluk is that because of the last deprecation ?? 

thank you :)

**Comment by HarounOujihi** [comment]
**I solve it**
all what i do is : run this command

> ionic cordova run android --device
(ionic cordova run browser is not working with me)

and i add this lines to my main.ts

> import {enableProdMode} from '@angular/core';
> enableProdMode();

**Comment by pp-randy** [comment]
Thank you for providing your solution.

**Comment by HarounOujihi** [comment]
Mr @pp-randy do you know why when i put currency "QR" or "QAR" is not working, but it works fine with "USD" !?
Thank you.

**Comment by pp-randy** [comment]
@HarounOujihi here is the list of currency codes that are supported https://developer.paypal.com/docs/integration/direct/rest/currency-codes/.
