### ISSUE TITLE
Query: Recurring payment 

### ISSUE THREAD

**Issue by Simerjit-developer** [paypal/PayPal-Cordova-Plugin#303]
Is this possible to do recurring payments on paypal with this plugin? If yes, then kindly mention the guidelines too.

**Comment by xiaoleih41** [comment]
PayPal mobile SDKs are deprecated. Please consider to use Braintree  SDK for your recurring payment need. Please read the [README.MD](https://github.com/paypal/PayPal-Cordova-Plugin) for more info.

**Comment by pp-randy** [comment]
Closing as the previous comment mentioned this SDK is deprecated and not supported for new integrations.
