### ISSUE TITLE
change card information

### ISSUE THREAD

**Issue by srishti-fwrk** [paypal/PayPal-Cordova-Plugin#304]
Can we change the card information in paypal

**Comment by xiaoleih41** [comment]
I don't quite understand your question. Please elaborate. If you are trying to update your own credit card information in side of your PayPal account, you can log in www.paypal.com and update funding source there.  You will not be able to update your customer's credit card information inside of his/her PayPal account.  When customer checkout, he/she will have the option of changing funding source inside of PayPal checkout iframe.

**Comment by pp-randy** [comment]
Closing as the solution has been provided.  For account related questions such as this you can search the PayPal Customer Service FAQs at https://www.paypal.com/help.

**Comment by srishti-fwrk** [comment]
hey


Thankyou guys for your reply . It's really usefull for me . Thankyou dear
once again.



Regards
srishti
