### ISSUE TITLE
Plugin Deprecated

### ISSUE THREAD

**Issue by renatobezerra** [paypal/PayPal-Cordova-Plugin#306]
Hi Everyone. 

I readed in Readme.md that this plugin are deprecated.
The Braintree API integration don't available on Brazil.

Because this, I can use this plugin?

Tks.

**Comment by xiaoleih41** [comment]
What exact feature are you looking for?

**Comment by renatobezerra** [comment]
I need a payment integration in my app, buy I see this information below in the Readme.md:

> Important: PayPal Mobile SDKs are now Deprecated and only existing integrations are supported. For all new integrations, use Braintree Direct in supported countries. In other countries, use Express Checkout and choose the Braintree SDK integration option.

I want know that plugin hasn't to use, because the suggested plugin (Braintree) not available in Brazil.

**Comment by xiaoleih41** [comment]
What about [Express Checkout via Braintree SDK](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/)? This SDK has been deprecated and no more feature updates. You won't get live credentials for direct credit card process through this REST SDK anymore.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given.
