### ISSUE TITLE
The merchant does not accept payments of this type.

### ISSUE THREAD

**Issue by ravuri-81** [paypal/PayPal-Cordova-Plugin#307]
When customers try to pay using credit/debit cards after login in with paypal account they where prompted with the error message "The merchant does not accept payments of this type."

plugin using:
<plugin name="com.paypal.cordova.mobilesdk" spec="^3.5.0" />

app name: flyingroses

loginid :   ronsayegh

As per our google search, it says we need to enable "Direct credit card payment" is My Account section but we couldn't find such an option in that place.. Please help us to fix this issue...

**Comment by xiaoleih41** [comment]
Direct credit card payment feature has been deprecated for REST API.  Please consider to integrate [Express Checkout via Braintree SDK](https://developer.paypal.com/docs/accept-payments/express-checkout/ec-braintree-sdk/get-started/) instead.

**Comment by xiaoleih41** [comment]
Close as the alternative solution has been provided.
