### ISSUE TITLE
App Crash on iOS 11

### ISSUE THREAD

**Issue by vtdesignz** [paypal/PayPal-Cordova-Plugin#308]
### General information

* SDK/Library version: 3.5.0
* Environment:  Sandbox
* `PayPal-Debug-ID` values: 
* Platforms:  iOS
* Device OS Version and Device:  iOS 11.0 to current

### Issue description

 On tapping Pay with Card on iOS 11.0 to current devices app is getting crashed.

**Comment by xiaoleih41** [comment]
We are looking into this.

**Comment by bluk** [comment]
Is there any trace or anything that can help with this? Also, note that if you're paying with Card, the Direct Credit Card REST API (which this SDK is eventually based on) is deprecated. The suggested replacement is using [Braintree Payments](https://www.braintreepayments.com/), a PayPal service.

**Comment by xiaoleih41** [comment]
Close due to inactivity please  resubmit if it's an existing integration.
