### ISSUE TITLE
Paypal Mass Payment in cordova

### ISSUE THREAD

**Issue by pzanwar03** [paypal/PayPal-Cordova-Plugin#309]
Hi ,

Is this possible by using this PayPal cordova plugin to execute the Mass payment. If this is possible then please help me.

Thanks

**Comment by pp-randy** [comment]
No the mobile apps are limited to creating payments mostly.  As a possible solution you could notify a server of yours to send a mass payment outside of the plugin if you have the email of the user.

**Comment by xiaoleih41** [comment]
Close the issue as the answer has been given
