### ISSUE TITLE
Invoice data support

### ISSUE THREAD

**Issue by suhaschitade** [paypal/PayPal-Cordova-Plugin#43]
Hi, Could you please let me know how to tweak singlepaymentUI function so that I can send invoice data to paypal. As per the example given, there is single transaction only however in real world there can be n number of items added to the cart which needs to be paid

Regards,
Suhas

**Comment by romk1n** [comment]
@suhaschitade i am happy to announce that [3.1.0](https://github.com/paypal/PayPal-Cordova-Plugin/releases/tag/3.1.0) version has been just released and supports itemization.

**Comment by suhaschitade** [comment]
Excellent news. Thanks Roman, will try this feature. Much needed one

Regards,
Suhas

Sent from my Windows Phone
________________________________
