### ISSUE TITLE
 Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by suhaschitade** [paypal/PayPal-Cordova-Plugin#44]
I am encountering below issues when doing build for publish

Undefined symbols for architecture arm64:
  "_CVPixelBufferGetBaseAddressOfPlane", referenced from:
      +[CardIOIplImage imageFromYCbCrBuffer:plane:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
  "_CVPixelBufferGetBytesPerRowOfPlane", referenced from:
      +[CardIOIplImage imageFromYCbCrBuffer:plane:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
  "_CVPixelBufferGetWidthOfPlane", referenced from:
      +[CardIOIplImage imageFromYCbCrBuffer:plane:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
  "_CVPixelBufferGetHeightOfPlane", referenced from:
      +[CardIOIplImage imageFromYCbCrBuffer:plane:] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
  "_CVPixelBufferLockBaseAddress", referenced from:
      -[CardIOVideoFrame process] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
  "_kCVPixelBufferPixelFormatTypeKey", referenced from:
      -[CardIOVideoStream addInputAndOutput] in libPayPalMobile.a(libCardIO.a-arm64-master.o)
  "_CVPixelBufferUnlockBaseAddress", referenced from:

Could you please help me, how should I resolve this. I am targeting iOS 7.1 build

**Comment by romk1n** [comment]
@suhaschitade In your project's Build Settings search for `Enable Modules (C and Objective-C)` and enable it and it should resolve this linking error. in the future version of the plugin it will be fixed.

**Comment by suhaschitade** [comment]
Hi Roman,
For resolving this issue, I have included CoreVideo framework in the project. It resolved all the undefined errors.
Is this ok, or should I follow your instructions.

Regards,
Suhas

Sent from my Windows Phone
________________________________

**Comment by romk1n** [comment]
@suhaschitade that's ok, this framework is missing from plugin.xml and hence you get linking errors when enable modules disabled.

**Comment by kdmny** [comment]
Hi @romk1n - this bug breaks automated builds. Which framework is missing from plugin.xml? Thanks!

**Comment by kdmny** [comment]
I learned that you can enable this from the command line using the `buildxcconfig`:

```
OTHER_CFLAGS=-Xclang -fmodules
```

**Comment by romk1n** [comment]
@kdmny that's the other option as well, thanks for pointing it out.

**Comment by romk1n** [comment]
fixed in [3.1.0](https://github.com/paypal/PayPal-Cordova-Plugin/releases/tag/3.1.0)
