### ISSUE TITLE
can't locate file for: -lPayPalMobile

### ISSUE THREAD

**Issue by suhaschitade** [paypal/PayPal-Cordova-Plugin#45]
I removed this plugin and reinstalled everything. now when trying to build I got above error, please let me know why this error is occurring

Regards,
Suhas

**Comment by romk1n** [comment]
@suhaschitade to properly remove the plugin and be able to reinstall it again follow this steps

```bash
cordova plugin remove com.paypal.cordova.mobilesdk
cordova platform remove ios
cordova platform remove android
```

**Comment by suhaschitade** [comment]
Hi Roman,
Thanks. This has worked. Please close the issue

Regards,
Suhas

Sent from my Windows Phone
________________________________
