### ISSUE TITLE
What is expected in clientIDs

### ISSUE THREAD

**Issue by suhaschitade** [paypal/PayPal-Cordova-Plugin#46]
Hi Roman,
what is expected in client ids, everytime I got success message after doing payment on sandbox environment however with same transaction id, is this is hardcoded?

Regards,
Suhas

**Comment by suhaschitade** [comment]
Now I am receiving order id as 
PAY-NONETWORKPAYIDEXAMPLE123

Although I am getting success message, Paypal developer account not showing any sign of transaction happened

I have implemented calls in following way



main service to paypal

LBapp.factory('paypalServ', function(cartDataServ, orderDataServ,payCheckServ,$ionicPopup){
	var paypalServFactory = [];
	var userId="";

 	 var _initPaymentUI =  function () {
            alert("initiating ");
            var clientIDs = {
              //  "PayPalEnvironmentProduction": "YOUR_PRODUCTION_CLIENT_ID",
                "PayPalEnvironmentSandbox": "some id"
            };
            PayPalMobile.init(clientIDs, onPayPalMobileInit);

        };

     var _onSuccesfulPayment =  function onSuccesfulPayment(payment) {
     		//alert("Payment successful, please click on save to continue with order.")
        $ionicPopup.alert({
               title: 'Alert',
               template: '<center>Payment successful, please click on save to continue with order..</center>'
             });
     		payCheckServ.set(true);
            console.log("payment success: " + JSON.stringify(payment, null, 4));
        };

      var _onFuturePaymentAuthorization =   function onFuturePaymentAuthorization(authorization) {
            console.log("authorization: " + JSON.stringify(authorization, null, 4));
        }; 

      var _createPayment =  function createPayment() {
            // for simplicity use predefined amount

          //  getUserServerId();
         // alert(JSON.stringify(orderDataServ.getPeopleResponse()));
            var short_desc = "lunchbite order User#: "+orderDataServ.getPeopleResponse();

            var paymentDetails = new PayPalPaymentDetails(cartDataServ.getPeopleResponse(), "0.00", "0.00");
            var payment = new PayPalPayment(cartDataServ.getPeopleResponse(), "USD", short_desc, "Sale", paymentDetails);
            //alert(payment);
            return payment;
        }; 
      var _configuration =  function configuration() {
            // for more options see `paypal-mobile-js-helper.js`
            var config = new PayPalConfiguration({merchantName: "My Test Shop", merchantPrivacyPolicyURL: "https://mytestshop.com/policy", merchantUserAgreementURL: "https://mytestshop.com/agreement"});
            return config;
        }; 
       var _onPayPalMobileInit =   function onPayPalMobileInit() {
            // must be called
            // use PayPalEnvironmentNoNetwork mode to get look and feel of the flow
            PayPalMobile.prepareToRender("PayPalEnvironmentNoNetwork", configuration(), onPrepareRender());
        }
       var _onUserCanceled = function onUserCanceled(result) {
       		payCheckServ.set(false);
            console.log(result);
        }
      var _onPrepareRender =  function onPrepareRender() {};

      var _makePayment = function makePayment() {
            PayPalMobile.renderSinglePaymentUI(createPayment(), onSuccesfulPayment, onUserCanceled);
        };

      

        paypalServFactory.initPaymentUI = _initPaymentUI;
        paypalServFactory.onSuccesfulPayment = _onSuccesfulPayment;
        paypalServFactory.onFuturePaymentAuthorization = _onFuturePaymentAuthorization;
        paypalServFactory.createPayment = _createPayment;
        paypalServFactory.configuration = _configuration;
        paypalServFactory.onPayPalMobileInit = _onPayPalMobileInit;
        paypalServFactory.onUserCanceled = _onUserCanceled;
        paypalServFactory.onPrepareRender = _onPrepareRender;
        paypalServFactory.makePayment = _makePayment;
      //  paypalServFactory.getUserServerId = _getUserServerId;

        return paypalServFactory;
});
LBapp.service('payCheckServ', function(){
    isPaySuccess=false;
  return {
      get: function(){
       // alert("returning " +isMyAcc);
          return isPaySuccess;
      },
      set : function(flag){
       // alert("setting flag to true");
        isPaySuccess=flag;
      }
  }
});


// Calling function

 paypalServ.initPaymentUI();
PayPalMobile.renderSinglePaymentUI(paypalServ.createPayment(), paypalServ.onSuccesfulPayment, paypalServ.onUserCanceled);

**Comment by suhaschitade** [comment]
Please note there is no alert displayed when paypal UI was rendering

**Comment by romk1n** [comment]
@suhaschitade you running in no network mode hence your transaction id is always `PAY-NONETWORKPAYIDEXAMPLE123`. You should also see PayPal UI word `mock` or `sandbox` when you running in other than production(live) modes.

I notice you never put the library into sandbox mode
```
// use PayPalEnvironmentNoNetwork mode to get look and feel of the flow
        PayPalMobile.prepareToRender("PayPalEnvironmentNoNetwork", configuration(), onPrepareRender());
```

change `PayPalEnvironmentNoNetwork` to `PayPalEnvironmentSandbox` if you want to use sandbox or `PayPalEnvironmentProduction` if you want to test live. For more info check the documentation https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/www/cdv-plugin-paypal-mobile-sdk.js#L48

**Comment by suhaschitade** [comment]
Thanks Roman. I did those changes for sandbox, and called initpaymentui also, however for some strange reasons this function never get called.

Anyways. I removed reference of my file and included index.js and called functions from there everything was perfectly executed

Regards,
Suhas

Sent from my Windows Phone
________________________________
