### ISSUE TITLE
Push notification

### ISSUE THREAD

**Issue by suhaschitade** [paypal/PayPal-Cordova-Plugin#48]
Hi Roman,
Does this plugin use apple push notification

Regards,
Suhas

**Comment by romk1n** [comment]
@suhaschitade plugin doesn't implement any push notification functionality. But i am curios why are you asking since it is usually a developer own choice ?

**Comment by suhaschitade** [comment]
Hi Roman,
I pushed my app on app store, I received an email from apple saying that Missing push notifications entitlement. I haven't implemented push notifications, just wanted to check with you.

Regards,
Suhas

Sent from my Windows Phone
________________________________
