### ISSUE TITLE
Production Vulnerability

### ISSUE THREAD

**Issue by jeremymlane** [paypal/PayPal-Cordova-Plugin#49]
I ran the following to initialize PayPalMobile (note, there is no production client id):

```javascript
var clientIDs = {
    "PayPalEnvironmentProduction": "123",
    "PayPalEnvironmentSandbox": "MySandboxClientId"
};
PayPalMobile.init(clientIDs,function(){
    var config = new PayPalConfiguration({merchantName: "Test", merchantPrivacyPolicyURL: "https://test.com/policy", merchantUserAgreementURL: "https://test.com/agreement"});
    PayPalMobile.prepareToRender("PayPalEnvironmentProduction", config, function(){
    });
});
```

and then ran 

```javascript
var payment = new PayPalPayment("1.00", "USD", "Donation");
PayPalMobile.renderSinglePaymentUI(payment, completionCallback, cancelCallback);
```

and used my credit card and it turns out my card was actually charged to some random store and shows up on my bank history as "KINDAFOREVER 818-632-4501 CA". 

There may be some kind of issue in how production client ids are used if using such a short production client id to test results in a random store creating an actual charge.

**Comment by romk1n** [comment]
@jeremymlane we will investigate can you please confirm what platform was it on and version information of the library in use ? Thanks.

**Comment by jeremymlane** [comment]
@romk1n It was on iOS 8.1 using Cordova 3.7.0. I guess it probably wasn't a random store. Could it be that there's actually a real production client id of "123"? I was using version 3.1.1 of the PayPal-Cordova-Plugin, so whatever SDK version is bundled with that.

**Comment by romk1n** [comment]
@jeremymlane you would get an error if the clientID doesn't exists or invalid at the preconnect time. If you not planning on doing anything with production just yet, just leave it unset. We will investigate further about "123" existence, but i am going to close this issue since SDK behavior is correct.
