### ISSUE TITLE
paypal payment plugin with cordova on android devices

### ISSUE THREAD

**Issue by pocahentez** [paypal/PayPal-Cordova-Plugin#50]
I'm trying to use paypal payment in my cordova application. For that I used this Paypal cordova plugin exemple :https://github.com/paypal/PayPal-Cordova-Plugin. I followed all the instructions mentioned there, but I get these errors:

01-13 05:18:06.650: E/PluginManager(2112): Uncaught exception from plugin
01-13 05:18:06.650: E/PluginManager(2112): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.hello/com.paypal.android.sdk.payments.PaymentActivity}; have you declared this activity in your AndroidManifest.xml?
01-13 05:18:06.650: E/PluginManager(2112):  at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1628)
01-13 05:18:06.650: E/PluginManager(2112):  at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
01-13 05:18:06.650: E/PluginManager(2112):  at android.app.Activity.startActivityForResult(Activity.java:3424)
01-13 05:18:06.650: E/PluginManager(2112):  at android.app.Activity.startActivityForResult(Activity.java:3385)
01-13 05:18:06.650: E/PluginManager(2112):  at org.apache.cordova.CordovaActivity.startActivityForResult(CordovaActivity.java:748)
01-13 05:18:06.650: E/PluginManager(2112):  at com.paypal.cordova.sdk.PayPalMobileCordovaPlugin.renderSinglePaymentUI(PayPalMobileCordovaPlugin.java:226)
01-13 05:18:06.650: E/PluginManager(2112):  at com.paypal.cordova.sdk.PayPalMobileCordovaPlugin.execute(PayPalMobileCordovaPlugin.java:54)
01-13 05:18:06.650: E/PluginManager(2112):  at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:84)
01-13 05:18:06.650: E/PluginManager(2112):  at org.apache.cordova.PluginManager.exec(PluginManager.java:147)
01-13 05:18:06.650: E/PluginManager(2112):  at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
01-13 05:18:06.650: E/PluginManager(2112):  at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:40)
01-13 05:18:06.650: E/PluginManager(2112):  at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
01-13 05:18:06.650: E/PluginManager(2112):  at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:27)
01-13 05:18:06.650: E/PluginManager(2112):  at android.os.Handler.dispatchMessage(Handler.java:102)
01-13 05:18:06.650: E/PluginManager(2112):  at android.os.Looper.loop(Looper.java:136)
01-13 05:18:06.650: E/PluginManager(2112):  at android.os.HandlerThread.run(HandlerThread.java:61)

THe same code works on ios devices. On android platforms when I click on the buy now button it crashed showing the above error messages.
Do you have any idea about this strange behaviour?

**Comment by romk1n** [comment]
@pocahentez what version of the plugin are you using ? can you check the content of the `platforms/android/AndroidManifest.xml` and see if the `<activity android:name="com.paypal.android.sdk.payments.PaymentActivity" />` is defined ? 

If not try doing `cordova platform remove android` and `cordova platform add android` again.

**Comment by pocahentez** [comment]
yes it exist in  my  `AndroidManifest.xml `:
  `<service android:exported="false" android:name="com.paypal.android.sdk.payments.PayPalService" />
        <activity android:name="com.paypal.android.sdk.payments.PaymentActivity" />
        <activity android:name="com.paypal.android.sdk.payments.LoginActivity" />
        <activity android:name="com.paypal.android.sdk.payments.PaymentMethodActivity" />
        <activity android:name="com.paypal.android.sdk.payments.PaymentConfirmActivity" />
        <activity android:name="com.paypal.android.sdk.payments.PayPalFuturePaymentActivity" />
        <activity android:name="com.paypal.android.sdk.payments.FuturePaymentConsentActivity" />
        <activity android:name="com.paypal.android.sdk.payments.FuturePaymentInfoActivity" />
        <activity android:name="com.paypal.android.sdk.payments.PayPalProfileSharingActivity" />
        <activity android:name="com.paypal.android.sdk.payments.ProfileSharingConsentActivity" />
        <activity android:configChanges="keyboardHidden|orientation" android:name="io.card.payment.CardIOActivity" />
        <activity android:name="io.card.payment.DataEntryActivity" />
        <activity android:configChanges="keyboardHidden|orientation" android:name="com.paypal.android.MEP.PayPalActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" />`

**Comment by pocahentez** [comment]
ok I figure out the problem. It seems like I have to call the `<script type="text/javascript" charset="utf-8" src="cdv-plugin-paypal-mobile-sdk.js"></script>` in the payment page.
Thank you for your support.

**Comment by romk1n** [comment]
You shouldn't include this file anywhere since Cordova includes it automatically if you have correctly followed this instructions.
