### ISSUE TITLE
Integration With Ionic framework?

### ISSUE THREAD

**Issue by Declan2345** [paypal/PayPal-Cordova-Plugin#53]
Has anyone managed to successfully integrate this plugin with Ionic framework.
my app doesn't have a Index.js , creating one doesn't work. 
I have tried to add the Script into the App.js also with no luck.
I am not sure how I can integrate this plugin as I can find very little documentation.

thanks any help is appreciated.

**Comment by romk1n** [comment]
@Declan2345 Just follow step 2 and 3 in integration guide in [readme](https://github.com/paypal/PayPal-Cordova-Plugin#your-app-integration). 

`PayPalMobile` and other objects defined [here](https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/www/paypal-mobile-js-helper.js) should be available to use in any of ionic js files. 

Follow the [example](https://github.com/romk1n/MyCordovaShop) to understand the usage. Make sure you registered at developer.paypal.com to get your clientIDs.

Hope it helps.

**Comment by clankiPad** [comment]
somebody know why does amount is reinit to $1 if it is a big amount (like $1900) ? thanks
