### ISSUE TITLE
Unable to run in android

### ISSUE THREAD

**Issue by Reiji87** [paypal/PayPal-Cordova-Plugin#54]
Hi,
I tried to implement the solution to my project, it works fine on the iOS but I will encounter a runtime error when executing it in android. and I've screenshot the error message.

Any help will be appreciated! 
Thanks!
![screen shot 2015-02-25 at 3 55 16 pm](https://cloud.githubusercontent.com/assets/8175305/6366861/d544f2da-bd06-11e4-9efc-e7e49ce23d68.png)

Update:
I think I called the function at the wrong place, please close the issue.
Thanks :)

**Comment by romk1n** [comment]
@Reiji87 great news! Thanks!
