### ISSUE TITLE
Possible to have a few merchant to pay?

### ISSUE THREAD

**Issue by Vincenttbk** [paypal/PayPal-Cordova-Plugin#57]
Hi,

Im trying to direct payments to  different merchants.

Trying to direct to company1:
What I did over here is, I did an init of the payment, which includes specifying the App ID and Ssandbox ID and I did a rendering of Single Payment. Everything seems to be working fine.

Trying to direct to company2:
so after making payment, Im trying to direct the payment to another company, so I did an init, which specify the app and sandbox ID of another company, and I render the single payment screen.

Both payment seems to be successful, but the result is that both payments are directed to company 1, instead of 1 payment for company 1 and another for company 2.

Is that the right way to do it? or is there anyway that I can recreate PaypalMobile object then I initialize a new payment?

Thank you :+1:

**Comment by romk1n** [comment]
@Vincenttbk please see this [issue](https://github.com/paypal/PayPal-iOS-SDK/issues/140) for the information.

**Comment by Vincenttbk** [comment]
Thank you romk1n :)
