### ISSUE TITLE
iOS Crash when adding invoiceNumber

### ISSUE THREAD

**Issue by cihadhoruzoglu** [paypal/PayPal-Cordova-Plugin#58]
Hi,

When we add invoiceNumber to the payment then iOS crashed.

Sample Code;
```
var payment = new window.PayPalPayment(totalPrice, "TRY", $scope.order.Product.Name, "Sale", paymentDetails);
payment.invoiceNumber($scope.order.orderId); // orderId is string
```

![screen shot 2015-03-12 at 16 16 29](https://cloud.githubusercontent.com/assets/1528616/6619489/34888c5c-c8d3-11e4-8706-a58937b07849.png)

2015-03-12 16:14:40.157 CicekSepeti[800:147913] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber length]: unrecognized selector sent to instance 0xb000000000057f33'
*** First throw call stack:
(0x18330659c 0x193a5c0e4 0x18330d664 0x18330a418 0x18320eb6c 0x100213fa0 0x1000776a4 0x100dace30 0x100dacdf0 0x100db99a0 0x100dbaf18 0x19427d2e4 0x19427cfa8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

Android works well but iOS crashing. How can we fix that?

PayPalMobile sdk version 3.1.3
We tested on iPhone 6, 6+ and 4S.

**Comment by romk1n** [comment]
@cihadhoruzoglu can you try and see if you can reproduce the same issue if you force convert to string ?

`payment.invoiceNumber(String($scope.order.orderId));`

The crash seems to happen when we check if the payment is processable and expects some property to be `NSString` but is getting `NSNumber`.

**Comment by cihadhoruzoglu** [comment]
@romk1n Thank you! It works right now :)

**Comment by romk1n** [comment]
@cihadhoruzoglu great!
