### ISSUE TITLE
App stopped when click paypal button

### ISSUE THREAD

**Issue by omaisali** [paypal/PayPal-Cordova-Plugin#60]
App Stops when click on Paypal button. 
I am using Cordova version 4.2.0

TypeError: window.PayPalMobile is undefined

**Comment by romk1n** [comment]
@omaisali please specify plugin version and also console logs. Thanks!

**Comment by omaisali** [comment]
com.paypal.cordova.mobilesdk 3.1.4 "PayPalMobile"


D/CordovaActivity( 7913): onMessage(onPageFinished,file:///android_asset/www/pay
ment.html)
D/CordovaLog( 7913): file:///android_asset/www/js/payment.js: Line 43 : Uncaught
 TypeError: Cannot call method 'querySelector' of null
D/CordovaActivity( 7913): Paused the application!
D/CordovaWebView( 7913): Handle the pause

**Comment by romk1n** [comment]
@omaisali can you try first fixing the issue reported in the log ?
```
D/CordovaLog( 7913): file:///android_asset/www/js/payment.js: Line 43 : Uncaught
TypeError: Cannot call method 'querySelector' of null
```

**Comment by omaisali** [comment]
i dont have idea about this issue. but let me try if i can,

**Comment by omaisali** [comment]
I solved that issue, Now the log is 

D/CordovaLog(13639): file:///android_asset/www/plugins/com.paypal.cordova.mobile
sdk/www/cdv-plugin-paypal-mobile-sdk.js: Line 60 : The provided environment is n
ot supported
D/CordovaActivity(13639): Paused the application!
D/CordovaWebView(13639): Handle the pause

**Comment by omaisali** [comment]
Ok thanks. I solved it. 

in these lines of code
function onPayPalMobileInit () {
                window.PayPalMobile.prepareToRender(
                  "PayPalEnvironmentSandbox", // <===here was entering my sandbox client id directly //which caused the issue.

**Comment by romk1n** [comment]
@omaisali great find!
