### ISSUE TITLE
Can't Launch on Sub pages

### ISSUE THREAD

**Issue by Declan2345** [paypal/PayPal-Cordova-Plugin#61]
I have been trying to Implement this plugin into my app,but can only seem to get anything to happen on the First page of my app.

The plugin works fine on startup, and I can use the paypal services as long as I am on the first page of the app.

however if it try to move the button onto one of my subpages the button no longer works.
I have tried to copy the scripts to the page and also included the Index.html on the page.

but had no luck.

has anyone else solved a similar issue ? 

thanks.

**Comment by romk1n** [comment]
@Declan2345 can you provide more details ? Thanks.

**Comment by Declan2345** [comment]
Hi romk1n, 
I am using the Ionic framework specifically the side menu Template. 

when my app loads up via the app.js the First page loaded is playlists.
which is under 'www/templates/playlists'.
on this initial page load I have full use of the plugin.
however if I navigate to another page for instance browse ('www/templates/browse')
I am unable to use the plugin on this subpage.

the buttons no longer works and I do not receive any logs.

I have no Idea why the Plugin works on the home page but will not load on any other ? 

thanks

**Comment by romk1n** [comment]
@Declan2345 unfortunately i didn't use `ionic` and maybe it would be worth asking at their forums? can you build a sample code and share it somewhere on the github so it is possible to have a look?

**Comment by Declan2345** [comment]
Hi I have created a repository here https://github.com/Declan2345/Issues-with-ionic-and-paypal-cordova-plugin. 
It is just the basic ionic template with the buttons on the Starting Page and also on the browse page of the app.
Im not sure If i am missing something obvious as I am new to phonegap and don't really have a wealth of experience behind me. 
However i have spent some time tinkering and found nothing. 

Hope that helps 

Thanks

**Comment by romk1n** [comment]
@Declan2345 you need to follow `angular.js` pattern [Ionic guide](http://ionicframework.com/docs/guide/preface.html). First of all you shouldn't use index.js. Take this example as base and rename `app` to something else. It can be your wrapper around PayPal functions. Lets say `PayPalApp` for now.

For Browse, you need to specify what controller is used for this view. For example inside of the `app.js` specify `controller: 'BrowseCtrl'` after `templateUrl: "templates/browse.html",`

You also need to use what ionic provides, therefore to make a button in `browse.html` use `<button class="button" ng-click="buy()"> Buy Now !</button> ` 

In `controller.js` we now need to set Browse controller. That can be done like this:
```js
.controller('BrowseCtrl', function($scope) {
  // Open the login modal
  $scope.buy = function() {
    PayPalApp.buy();
  };
})
```

you can now listen to the actions which happen on this view. We defined `buy()` click, therefore we can call into the PayPalApp which is defined in index.js.

in Index.js you can for testing purposes just create a function buy:

```js
 buy : function () {
    PayPalMobile.renderSinglePaymentUI(PayPalApp.createPayment(), PayPalApp.onSuccesfulPayment,
        PayPalApp.onUserCanceled);
  }
```

Hope it helps and happy learnings !!
