### ISSUE TITLE
Is there any way to display item list when renderSinglePaymentUI?

### ISSUE THREAD

**Issue by myc0210** [paypal/PayPal-Cordova-Plugin#64]
Can anyone tell me is there any way to list items while calling renderSinglePaymentUI. I have already add 
\* var items = [];
    items.push(new PayPalItem("product 1", "1", "25.00", "SGD", "P01"));
    items.push(new PayPalItem("product 2", "2", "12.50", "SGD", "P02"));
    payment.items(items); *\
to the createPayment function and these two items have already be put inside the transaction which i verified by curling the rest api. But the UI inside my application only show shortDescription and amount only. I want to reproduce the same experience like express checkout. Is there any way to do it?

**Comment by romk1n** [comment]
@myc2010 no. it is responsibility of the app developer to show the items before taking the user to make the purchase. The items will be shown in the receipt PayPal sends. Thanks.

**Comment by myc0210** [comment]
@romk1n but the mobile express checkout also list those items at top of the page when make purchase. It is different implement from the mobile sdk? I just want to give hint to customer since he need to log in to paypal and then see the checkout information. There is a gap. Thanks for the help.

**Comment by romk1n** [comment]
Express checkout is a different product and there are no plans to support displaying itemised items in the SDK. Sorry

**Comment by myc0210** [comment]
Ok. Thanks.
