### ISSUE TITLE
Paypal not working with other plugin - opentok for video call in android..

### ISSUE THREAD

**Issue by kalyanpkumar** [paypal/PayPal-Cordova-Plugin#65]
Hi Team..

We are using the Paypal phonegap plugin for our phonegap application.We are also using opentok phonegap plugin for video call.

with these both plugins, app works fine in iOS but not in Android.

1. We created a fresh phonegap project and had added the opentok plugin...
2. Then we see the app working with video in Android.
3. We added paypal plugin.
4. The app stopped working.. we dont see any video on Android.
5. We removed paypal plugin and tested, then also the app is not working.. we dont get any video..
6. Similarly we have added paypal plugin first and we can see paypal screen coming up for payment.
7. We then added opentok plugin.
8. Then both are not working.

May we Please know the possible reasons for this behaviour.

**Comment by romk1n** [comment]
@kalyanpkumar can you please create a sample code on github and share the repository so we can have a look. Also, please confirm the version of the plugin you tried and what Android setup you have. In addition please share the logcat output when the app is running. Thanks!

**Comment by romk1n** [comment]
Since there were no further updates to the issue i am going to close it. Feel free to re-open it with more details.
