### ISSUE TITLE
include payer details 

### ISSUE THREAD

**Issue by kiempoturner** [paypal/PayPal-Cordova-Plugin#66]
Hi, first of all, your plugin rocks. Im still confused on how to include payer details . I tried it on Sandbox.

As you can see here, there name field is `null` :
![screen shot 2015-03-27 at 8 13 27 pm](https://cloud.githubusercontent.com/assets/6310473/6867527/0249c156-d4be-11e4-828d-46ca58a0ec41.png)

**Comment by ppmtscory** [comment]
@kiempoturner The name does not appear for a credit card payment as there's currently no implementation to allow it to be entered or passed through.  Closing this now since the feature is already being tracked with [this issue](https://github.com/paypal/PayPal-iOS-SDK/issues/185).
