### ISSUE TITLE
i get always specific error: "The client credentials are invalid"

### ISSUE THREAD

**Issue by roysG** [paypal/PayPal-Cordova-Plugin#67]
PayPal SDK: Request has failed with error: invalid_client - שגיאת מערכת (invalid_client‏). נסה שוב מאוחר יותר. (401) | PayPal Debug-ID: 8274a1db2b8d8 [sandbox, PayPal iOS SDK 2.8.5] | Details: (
        {
        "error_description" = "The client credentials are invalid";
    }
).

I putted the correct client key for both sandbox and live.
Why does it happen ?
What i am missing ?

**Comment by roysG** [comment]
some response ?

**Comment by romk1n** [comment]
@roysG sandbox sometimes can be have intermittent issues. Can you please make sure that you have put the client id correctly from the developer.paypal.com portal for both sandbox and live. If the problem persists, can you also try using this sample app [here](https://github.com/romk1n/MyCordovaShop). Make sure you change this [line](https://github.com/romk1n/MyCordovaShop/blob/master/www/js/index.js#L113) to the environment you trying to use.

Please provide output for both sandbox and live.

**Comment by roysG** [comment]
It Works !!
I was problem on my client sandbox token.
two last questions, if i want to go live, what should i need to change in the line:

payPalMobile.prepareToRender("PayPalEnvironmentSandbox", paypal.configuration(), paypal.onPrepareRender);

and the second thing, if i want to go live, in text next few hours, do i need to submit to paypal my app and get some approval from them or i just can go live with my app ?

Thanks.

**Comment by romk1n** [comment]
@roysG great you figured it out.
