### ISSUE TITLE
App crashes working when in sandbox mode

### ISSUE THREAD

**Issue by khinze** [paypal/PayPal-Cordova-Plugin#68]
Hi Guys,

I have an existing angular app using phonegap cordova. As soon as I switch my environment to PayPalEnvironmentSandbox the app crashes. Could anyone point me in right direction to see what I am doing wrong
//PayPalEnvironmentSandbox
 var environment = "PayPalEnvironmentNoNetwork";
    var merchantId = "*";
    var apiKey = "*";
    var paypalClientId = "my client id I see on the paypal sandbox ";

    var clientIDs = {
        "PayPalEnvironmentProduction": paypalClientId,
        "PayPalEnvironmentSandbox": paypalClientId
    };
  
    var configuration = function () {
        var config = new PayPalConfiguration({merchantName: "Name", merchantPrivacyPolicyURL: "", merchantUserAgreementURL:""});
        return config;
    };

   var onAuthorized = function(autorization){
       alert('authorized');
       alert(JSON.stringify(autorization));
       alert(autorization.response.code);
   };

   var onExited = function(response){

   };

    var mobileInit = function(amount, description){
        alert('opening');
        PayPalMobile.prepareToRender(environment, configuration(), function(){
            alert('redering');
            PayPalMobile.renderFuturePaymentUI(onAuthorized, onExited);
        });
    };

    $scope.BuyNew = function(){
        alert('setting environment');
        PayPalMobile.init(clientIDs, mobileInit("45.00", 'example'));
    };

**Comment by romk1n** [comment]
@khinze can you please provide console log output ? It looks like you trying to use future payments functionality if that's the case the `merchantPrivacyPolicyURL` and `merchantUserAgreementURL` must be valid URLs. For details message we will have to see the log. Thanks.

**Comment by romk1n** [comment]
@khinze also `PayPalMobile.init(clientIDs, mobileInit("45.00", 'example'));` doesn't seem right. the 2nd argument takes a callback function to notify the `init` has finished.

Also bare in mind the in future payment functionality all payments must happen from the server not from the mobile app.

**Comment by khinze** [comment]
@romk1n Thanks for the response. merchantPrivacyPolicyURL and merchantUserAgreementURL I didnt enter valid urls. Dumb question, can I just create a random html page and host it and link it to it for testing purposes? PayPalMobile.init(clientIDs, mobileInit("45.00", 'example')); I will provide you with console output. Basically we trying set up recurring payments via braintree. We need the user to validate with paypal so we set up recurring payments using braintree. Braintree provides sdk however have no clue how to import it into cordova. So what our plan was is get the code from paypal, send it to our server so we can generate the nonce. You have any suggestions?

**Comment by khinze** [comment]
PayPalMobile.init(clientIDs, mobileInit());

**Comment by khinze** [comment]
var mobileInit = function(){
        alert('opening');
        PayPalMobile.prepareToRender(environment, configuration(), function(){
            alert('redering');
            PayPalMobile.renderFuturePaymentUI(onAuthorized, onExited);
        });
    };

**Comment by romk1n** [comment]
@khinze in that case you shouldn't call `mibileInit()` just pass it the name `PayPalMobile.init(clientIDs, mobileInit);` also please submit the actual log. Thanks

**Comment by romk1n** [comment]
> Dumb question, can I just create a random html page and host it and link it to it for testing purposes?

For testing you can just point to any valid website, even it it doesn't exists but it needs to be a valid url i.e. `https://paypal.com/privacy.html`

**Comment by khinze** [comment]
Thanks. I've been using console.log. Don't know how to get the actual stack trace. Ill figure this out tomorrow and get back to you. The app also crashes when it gets to prepareToRender on ios, however on android it loads when in PayPalEnvironmentNoNetwork. I changed the url  to https://paypal.com/privacy.html it still crashes when in sandbox mode.

**Comment by romk1n** [comment]
@khinze you can also load project in Xcode and try running to see where the crash is. without crash stack i am running out of the ideas what maybe wrong.

**Comment by khinze** [comment]
@romk1n I removed the plugin and re added it. I also removed the platforms from cordova and readded them. The plugin is working now in sandbox mode . Not sure what was  wrong.

**Comment by romk1n** [comment]
@khinze great you figured it out! when updating to new version you would normally have to remove plugin first before adding it.
