### ISSUE TITLE
Payment Status

### ISSUE THREAD

**Issue by mtriponi** [paypal/PayPal-Cordova-Plugin#71]
When Plugin execute app.onSuccesfulPayment(). If state == approved, 

It means that the payment was approved and there is no way to be canceled?

Can enter by the app.onSuccesfulPayment () and Payment not completed?

thanks you

**Comment by romk1n** [comment]
@mtriponi i am sorry i don't think i understand what the question is. what `state` are you referring to ? state of the payment when you did validation ?

**Comment by mtriponi** [comment]
Thanks for your answer.

I Have:
buyNowBtn.onclick = function(e) {
            // single payment
            PayPalMobile.renderSinglePaymentUI(app.createPayment(), app.onSuccesfulPayment,
                                               app.onUserCanceled);
};

When the user complete the Payment, the plugin execute the callback "app.onSuccesfulPayment" and I can see state. In this point, I will register the payment in my system.

I want make sure that approved status is permanent (to process the user purchase) and not will change, for example, if the user does not complete the payment.

Sorry for my low level english . Do you understand?

Thanks you..

**Comment by mtriponi** [comment]
I need to be sure that the customer paid to enable purchase in my android application.

**Comment by romk1n** [comment]
@mtriponi got it. state won't change. there are a number of values to the state property and some require you to go and review the payment to payment before acceptance, but user can no longer cancel it. For more information see https://developer.paypal.com/webapps/developer/docs/api/#look-up-a-payment-resource
