### ISSUE TITLE
Extra paypal configuration

### ISSUE THREAD

**Issue by joomlaevolved** [paypal/PayPal-Cordova-Plugin#72]
Hi,

I am developing an app for one of my clients and I am trying to use the paypal condova plugin in a phonegap environment.

Once I call the PayPalMobile.renderSinglePaymentUI function, the application hangs and I get in the logat, the follwing errors:

04-30 16:47:12.121: W/paypal.sdk(19813): PayPalService created. PayPalSDK/PayPal-Android-SDK 2.8.8 (Android 4.1.2; LGE LG-E410i; )
04-30 16:47:12.181: W/dalvikvm(19813): VFY: unable to resolve static method 6009: Lcom/google/android/gms/common/GooglePlayServicesUtil;.isGooglePlayServicesAvailable (Landroid/content/Context;)I
04-30 16:47:12.681: D/dalvikvm(19813): GC_CONCURRENT freed 747K, 13% free 8039K/9223K, paused 20ms+4ms, total 75ms
04-30 16:47:12.681: D/dalvikvm(19813): WAIT_FOR_CONCURRENT_GC blocked 36ms
04-30 16:47:12.731: W/dalvikvm(19813): threadid=1: thread exiting with uncaught exception (group=0x41c30460)
04-30 16:47:12.741: E/AndroidRuntime(19813): FATAL EXCEPTION: main
04-30 16:47:12.741: E/AndroidRuntime(19813): java.lang.RuntimeException: Unable to bind to service com.paypal.android.sdk.payments.PayPalService@424e0938 with Intent { cmp=gr.joomlaevolved.vmapp/com.paypal.android.sdk.payments.PayPalService (has extras) }: java.lang.RuntimeException: Missing EXTRA_PAYPAL_CONFIGURATION. To avoid this error, set EXTRA_PAYPAL_CONFIGURATION in both PayPalService, and the initializing activity.
04-30 16:47:12.741: E/AndroidRuntime(19813): 	at android.app.ActivityThread.handleBindService(ActivityThread.java:2447)
04-30 16:47:12.741: E/AndroidRuntime(19813): 	at android.app.ActivityThread.access$1700(ActivityThread.java:138)
04-30 16:47:12.741: E/AndroidRuntime(19813): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
04-30 16:47:12.741: E/AndroidRuntime(19813): 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-30 16:47:12.741: E/AndroidRuntime(19813): 	at android.os.Looper.loop(Looper.java:137)
04-30 16:47:12.741: E/AndroidRuntime(19813): 	at android.app.ActivityThread.main(ActivityThread.java:4950)
04-30 16:47:12.741: E/AndroidRuntime(19813): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-30 16:47:12.741: E/AndroidRuntime(19813): 	at java.lang.reflect.Method.invoke(Method.java:511)
04-30 16:47:12.741: E/AndroidRuntime(19813): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
04-30 16:47:12.741: E/AndroidRuntime(19813): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
04-30 16:47:12.741: E/AndroidRuntime(19813): 	at dalvik.system.NativeStart.main(Native Method)
04-30 16:47:12.741: E/AndroidRuntime(19813): Caused by: java.lang.RuntimeException: Missing EXTRA_PAYPAL_CONFIGURATION. To avoid this error, set EXTRA_PAYPAL_CONFIGURATION in both PayPalService, and the initializing activity.
04-30 16:47:12.741: E/AndroidRuntime(19813): 	at com.paypal.android.sdk.payments.PayPalService.a(Unknown Source)
04-30 16:47:12.741: E/AndroidRuntime(19813): 	at com.paypal.android.sdk.payments.PayPalService.onBind(Unknown Source)
04-30 16:47:12.741: E/AndroidRuntime(19813): 	at android.app.ActivityThread.handleBindService(ActivityThread.java:2434)
04-30 16:47:12.741: E/AndroidRuntime(19813): 	... 10 more

Has anyone came across such a situation? Have you got anything to propose?

Thank you in advance.

**Comment by romk1n** [comment]
@joomlaevolved are you able to reproduce it with this sample code https://github.com/romk1n/MyCordovaShop ?

**Comment by romk1n** [comment]
@joomlaevolved we have also updated to new version of the plugin today with Android SDK version 2.9.3 which resolved quite a number of crashes. Would you also mind trying to reproduce it with new version ? Thanks.

**Comment by joomlaevolved** [comment]
Thank you for the quick response, I will try it today and let you know!

**Comment by joomlaevolved** [comment]
I get the same error. I will try now your example project to check if it is my configuration and let you know.

**Comment by joomlaevolved** [comment]
Hi, I founded, 

Client Ids or  configuration (no sure now - ;-) ) where null before initing the PaypalMobile.
I had to create some callback functions in order to make sure that the data where initialised before calling the init function.

Thank you, and sorry for the hassle.

**Comment by romk1n** [comment]
@joomlaevolved great you figured it out!

**Comment by Jamesmallon1** [comment]
Hi there,

got exact issue. What exactly did you do to resolve?

**Comment by pp-randy** [comment]
@Jamesmallon1 the values in the config appear that they were null and didn't have the intended values.
