### ISSUE TITLE
A plugin in your app does not support the compulsory arm64 (64-bit support) architecture.

### ISSUE THREAD

**Issue by KeKs0r** [paypal/PayPal-Cordova-Plugin#73]
Hi,

I wanted to play around with the Paypal Plugin, but adding it to my App is causing the iOS Build on PhoneGap build to fail with the following error message:

`Error - A plugin in your app does not support the compulsory arm64 (64-bit support) architecture`

My config.xml contains the following plugins:
```
    <gap:plugin name="com.phonegap.plugin.statusbar" version="1.1.0" />
    <gap:plugin name="org.apache.cordova.device" version="0.2.8" />
    <gap:plugin name="org.apache.cordova.splashscreen" version="0.2.7" />
    <gap:plugin name="org.apache.cordova.network-information" version="0.2.7" />
    <gap:plugin name="org.apache.cordova.camera" version="0.2.9" />
    <gap:plugin name="org.apache.cordova.inappbrowser" version="0.2.4" />
    <gap:plugin name="nl.x-services.plugins.socialsharing" version="4.3.0" />
    <gap:plugin name="net.bgta.phonegap.plugin.appversion" version="1.1.1" />
    <gap:plugin name="com.phonegap.plugins.pushplugin" version="2.4.0" />
    <gap:plugin name="com.paypal.cordova.mobilesdk" source="plugins.cordova.io" />
    <gap:plugin name="org.apache.cordova.dialogs" version="0.2.10" />
```

**Comment by romk1n** [comment]
@KeKs0r the iOS version of mobile sdk definitely has arm-64 support. you can double check that by running 

```bash
$ file src/ios/PayPalMobile/libPayPalMobile.a                                                                                                                                                                            
libPayPalMobile.a: Mach-O universal binary with 5 architectures
libPayPalMobile.a (for architecture armv7):	current ar archive random library
libPayPalMobile.a (for architecture armv7s):	current ar archive random library
libPayPalMobile.a (for architecture i386):	current ar archive random library
libPayPalMobile.a (for architecture x86_64):	current ar archive random library
libPayPalMobile.a (for architecture arm64):	current ar archive random library
```
are you sure it is the `com.paypal.cordova.mobilesdk` it is complaining about ?

**Comment by romk1n** [comment]
@KeKs0r can you confirm what Xcode version are you using as well?

**Comment by KeKs0r** [comment]
I am using no Xcode at all. I am just using PhoneGap Build.
And it must be this plugin, since its the only one I added. But I think its actually not the problem that this plugin doesn't support it, but rather that it supports it.

If I use an older version (also from Phonegap Build instead of cordova.io) it works:
`<gap:plugin name="com.paypal.cordova.mobilesdk" version="3.1.2" />`

**Comment by drdalziel** [comment]
adding version="3.1.6" causes Phonegap Build to throw the error: plugin unsupported: com.paypal.cordova.mobilesdk @ 3.1.6

**Comment by romk1n** [comment]
@drdalziel arm64 support was there since the beginning. phone gap build maybe using Xcode 6.2 and obfuscates the real error, please try version 3.1.6

**Comment by romk1n** [comment]
@drdalziel it should be available now through the registry.

**Comment by drdalziel** [comment]
It builds now with no errors. Thanks!

**Comment by romk1n** [comment]
@KeKs0r have you managed to reproduce the issue with new build ?

**Comment by KeKs0r** [comment]
I solved it by using different config and the plugin from the build.phonegap service.

`<gap:plugin name="com.paypal.cordova.mobilesdk" version="3.1.6" />`

**Comment by romk1n** [comment]
@KeKs0r great. when using phone gap build that's the right way as shown in our [readme](https://github.com/paypal/PayPal-Cordova-Plugin#phonegap-build)
