### ISSUE TITLE
Directly navigate into payment with credit card & Paypal

### ISSUE THREAD

**Issue by KeKs0r** [paypal/PayPal-Cordova-Plugin#74]
Hi,

I want to implement credit card payment as well as normal paypal payment. Since I also have prepay as payment option I would like to show all 3 options (credit card, paypal, prepay) in my own app. But as far as I understood this plugin, there is no option to directly navigate into the credit card or paypal login screen of the payment UI?

I know there is a option to disable creditCard Payment. 

Are there other possibilities to achieve this?

**Comment by romk1n** [comment]
@KeKs0r that's correct the only 2 options you can have is credit card or PayPal. There is no way to customize it to show 3rd option.

**Comment by KeKs0r** [comment]
I did not want to add my third option into the paypal plugin. I wanted to directly navigate into either Credit Card option or the paypal option. But I am afraid there is no option that can be passed to `PayPalMobile.renderSinglePaymentUI`

**Comment by romk1n** [comment]
@KeKs0r sorry for misunderstanding your question. We don't have such functionality. However, if the user has selected credit card in the past it will be remembered, so the user doesn't need to supply his credit card again. Unfortunately in the case of PayPal they would still will have to click on PayPal and login. Hope it helps.

**Comment by KeKs0r** [comment]
Ok thanks for the clarification. In that case my user will have to live with an additional click.
