### ISSUE TITLE
Integration Issue with Sencha Javascript: uncaught exception 'PayPalIncompleteIntegration', reason: 'preconnectWithEnvironment was called without a preceding call to initializeWithClientIdsForEnvironments:'

### ISSUE THREAD

**Issue by jollysean** [paypal/PayPal-Cordova-Plugin#75]
Hi,

I am trying to integrate this plugin with Sencha Touch 2 using Javascript as per the given documentation. But I get the following error.

Can someone please guide for right way to do it.

TIA.
------------------------------------------------------------------------------------------
2015-05-04 23:18:33.652 OrgJS[2341:84525] *** Terminating app due to uncaught exception 'PayPalIncompleteIntegration', reason: 'preconnectWithEnvironment was called without a preceding call to initializeWithClientIdsForEnvironments:'
*** First throw call stack:
(
	0   CoreFoundation                      0x00624946 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x03a0ea97 objc_exception_throw + 44
	2   CoreFoundation                      0x0062486d +[NSException raise:format:] + 141
	3   OrgJS                               0x001b42eb +[PayPalMobile preconnectWithEnvironment:] + 639
	4   OrgJS                               0x00135e46 __45-[PayPalMobileCordovaPlugin prepareToRender:]_block_invoke_2 + 54
	5   libdispatch.dylib                   0x03fe1a2a _dispatch_call_block_and_release + 15
	6   libdispatch.dylib                   0x03ffe03f _dispatch_client_callout + 14
	7   libdispatch.dylib                   0x03fe7764 _dispatch_main_queue_callback_4CF + 470
	8   CoreFoundation                      0x0057e95e __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	9   CoreFoundation                      0x0053d760 __CFRunLoopRun + 2256
	10  CoreFoundation                      0x0053cbcb CFRunLoopRunSpecific + 443
	11  CoreFoundation                      0x0053c9fb CFRunLoopRunInMode + 123
	12  GraphicsServices                    0x04eb224f GSEventRunModal + 192
	13  GraphicsServices                    0x04eb208c GSEventRun + 104
	14  UIKit                               0x009d68b6 UIApplicationMain + 1526
	15  OrgJS                               0x000dabd9 main + 89
	16  libdyld.dylib                       0x04023ac9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by romk1n** [comment]
@jollysean did you check the sample app? as error says you need to call `PayPalMobile.init`

**Comment by romk1n** [comment]
please open an issue if the problem persists.
