### ISSUE TITLE
App Crashes when rendering Payment UI on iOS

### ISSUE THREAD

**Issue by KeKs0r** [paypal/PayPal-Cordova-Plugin#76]
Hi,

i have looked into the issues of the plugin and it seems that there are some occasions when the app crashes. Unfortunately I have no idea what causes it. I have tried several Versions of this plugin. And since I am using PG Build I don't have access to any logs from native. Only thing I could get from xcode is the following:

https://gist.github.com/KeKs0r/73c040afc4b4b5e0cc5f

I really don't know how to investigate this further.

**Comment by romk1n** [comment]
@KeKs0r unfortunately without symbols files it is hard to say what exactly happened. Although you are using phone gap build it shouldn't stop you to be able to run your app locally (provided you have a mac). Is that something you can do ?

**Comment by KeKs0r** [comment]
I turned out that I was using the shipping address wrong. Unfortunately
this kind of issue is very hard to find, since the app immediately crashes.
And with phonegap build I did not have better logging.

**Comment by romk1n** [comment]
@KeKs0r glad you figured it out. Can you provide the example on what have you been sending ? 

also if you want to submit a pull request how this issue could have been caught earlier we would really appreciate it!

**Comment by KeKs0r** [comment]
@romk1n: I am again facing similar issues. This time it seems to work fine on the "javascript" side. How can I access the "symbol" files in order to investigate this. (This is somehow urgent, since the issue made it into our production app :cry:  )

**Comment by romk1n** [comment]
@KeKs0r unfortunatley i am not familiar with Phonegap Build to know. The `.dsym` file is produced along with `.ipa`. You still will require to open Xcode to analyze it. Have you tried reproducing the crash yourself using Xcode ?

**Comment by KeKs0r** [comment]
Unfortunately not. I have never worked with xcode and are ver unfamiliar with native app development (Hence the usage of PG Build) . I could fix it somehow with change versions of the plugin. This seems to be very flaky. Since I changed the version of the plugin back and forth sometimes working sometimes not. I just hope it stays like that. But without debugging it or having logs to really find the issue, its kind of hard to predict. 

Is the '.dsym' file created while creating the ipa file? Since PG Build also has some logs that are created while building.

**Comment by romk1n** [comment]
@KeKs0r you don't have to get very familiar with Xcode to run it. you just do `cordova build` in the command line and inside `platforms/ios` you will have a `.xcodeproj` file with the name of your project. Open it and just click Run.

From a quick google search on the `.dsym` file from phonegap build it looks those files are not provided http://community.phonegap.com/nitobi/topics/_dsym_file_required_for_analyzing_app_crashes

**Comment by KeKs0r** [comment]
ok I'll try to get cordova working from the cli and see if I can figure something out. Problem is that PGB and normal cordova also use slightly different config.xml and handle plugins differently.

**Comment by romk1n** [comment]
@KeKs0r you can use phone gap CLI. it is built on top of the cordova.
