### ISSUE TITLE
i get error "pp_service_error_bad_currency paypal" on production

### ISSUE THREAD

**Issue by roysG** [paypal/PayPal-Cordova-Plugin#77]
When i am trying to make transaction from typing credit card option, i get the message:
"pp_service_error_bad_currency paypal" 
I am using israel currency.

**Comment by romk1n** [comment]
@roysG can you please provide the sample of the actual payment you trying to send to the api. Thanks. Also the console log should have a `debug-id` and full message description.

**Comment by roysG** [comment]
2015-05-12 07:22:33.178 picktags[318:90711] PayPal SDK: Request has failed with error: pp_service_error_bad_currency - This currency is not presently supported. (400) | PayPal Debug-ID: 632bf4b2596b1 [live, PayPal iOS SDK 2.8.5] | Details: (
        {
        field = "transactions[0].amount.currency";
        issue = "Value is not supported at this time";
    }
).

**Comment by dgoldman-ebay** [comment]
@roysG please see our discussion of currencies [here](https://github.com/paypal/PayPal-iOS-SDK#currencies).

As noted there (and also [here](https://developer.paypal.com/webapps/developer/docs/integration/direct/rest_api_payment_country_currency_support/#direct-credit-card-payments)), the only currencies that PayPal supports for credit card payments are `USD`, `GBP`, `CAD`, `EUR`, and `JPY`.
