### ISSUE TITLE
How to change UI 

### ISSUE THREAD

**Issue by suhaschitade** [paypal/PayPal-Cordova-Plugin#80]
@romk1n ,  this is not an issue just a request, could you please let me know if I need to change UI in plugin how should I do it?, is it possible to do? I have opened the project in xcode however no xib files were there in plugin.

Your help is really appreciated.

Regards,
Suhas

**Comment by romk1n** [comment]
@suhaschitade the plugin is based on the native PayPal Mobile which doesn't allow any UI customization. For more details please see this section https://github.com/paypal/PayPal-iOS-SDK#usability

**Comment by suhaschitade** [comment]
Hi Roman, agreed. However I want to create new plugin although not for PayPal, could you please let me know how to make it and integrate with PayPal 

Regards
Suhas

Sent from my Windows Phone

-----Original Message-----

**Comment by romk1n** [comment]
@suhaschitade the only integration point with PayPal on iOS and Android is through PayPal Mobile SDKs.

**Comment by suhaschitade** [comment]
@romk1n  , agreed however where is SDK in this plugin I can see only .m and .h files. No xib or user- interface files
Regards,
Suhas

**Comment by romk1n** [comment]
@suhaschitade the library is embedded in the plugin https://github.com/paypal/PayPal-Cordova-Plugin/tree/master/src/ios/PayPalMobile and is usually the same version as latest github.com/paypal/PayPal-iOS-SDK

**Comment by suhaschitade** [comment]
@romk1n , so is user interface is part of libPayPalMobile.a file. if yes how to create such file

Regards,
Suhas

**Comment by romk1n** [comment]
Well I guess first you need to learn how to create a static library. You may start here http://www.raywenderlich.com/41377/creating-a-static-library-in-ios-tutorial

**Comment by suhaschitade** [comment]
@romk1n , thank you very much. I will have a look
