### ISSUE TITLE
New version is throwing a Phonegap error

### ISSUE THREAD

**Issue by drdalziel** [paypal/PayPal-Cordova-Plugin#81]
It seems that the new version of the plugin is throwing the old,  A plugin in your app does not support the compulsory arm64 (64-bit support) architecture, error. It was working for me with version 3.1.6.
If I add version="3.1.7" or version="3.1.8" to the config.xml file, I get a plugin unsupported error.

**Comment by romk1n** [comment]
@drdalziel as mentioned in the release notes you require Xcode 6.3 for the latest versions. It sounds like phone gap is not upgraded to 6.3 and you may continue using earlier versions.

**Comment by drdalziel** [comment]
Unfortunately Phonegap isn’t letting me use any earlier version so I’m stuck. 

 

Thanks,

 

Dennis Dalziel

VP Production and Technology

G & R Publishing Co.

507 Industrial St.

Waverly, IA 50677

319-352-5391

**Comment by romk1n** [comment]
@drdalziel specifying the version should work `<gap:plugin name="com.paypal.cordova.mobilesdk" version="3.1.6" />` same issue was fixed that way https://github.com/paypal/PayPal-Cordova-Plugin/issues/73

**Comment by drdalziel** [comment]
That worked before, now you must also add: source="npm"
