### ISSUE TITLE
"Checking this device" always hangs the first time

### ISSUE THREAD

**Issue by trongrg** [paypal/PayPal-Cordova-Plugin#82]
We are experiencing this problem on many devices.

When Paypal SKD show "Checking this device", it hangs for the first time.

After that, we click back button to return to our app, and click "Pay" again, "Checking this device" doesn't appear, it goes straight to payment page. 

However, on the device Acer Iconia A1-713, when pay with card, the camera is not available, the screen appears with just the form to fill in card details. The camera is available on other devices that we tested.

We also tried with the sample app in readme, and the same problem occurs.

There is nothing in logcat that related to this problem. The only thing I get from Paypal Activity is about "EXTRA_PAYPAL_CONFIGURATION", which isn't available/used.

**Comment by romk1n** [comment]
@trongrg please provide more details like version of the plugin and android sdk in use. what version of the android are you using ?

> However, on the device Acer Iconia A1-713, when pay with card, the camera is not available, the screen appears with just the form to fill in card details. The camera is available on other devices that we tested.

please make sure that `platforms/android/libs` has the following files:
```bash 
$ ls *
PayPalAndroidSDK-2.8.8.jar
arm64-v8a:
libcardioDecider.so
armeabi:
libcardioDecider.so
armeabi-v7a:
libcardioDecider.so           libcardioRecognizer_tegra2.so libopencv_imgproc.so
libcardioRecognizer.so        libopencv_core.so
mips:
libcardioDecider.so
mips64:
libcardioDecider.so
x86:
libcardioDecider.so
x86_64:
libcardioDecider.so
```

> We also tried with the sample app in readme, and the same problem occurs.

Can you try reproducing this using the following repo ? https://github.com/romk1n/MyCordovaShop

**Comment by jaypatel512** [comment]
Hey @trongrg ! Any update on this ? 

Any more information should help us find the root cause ? Please let us know.

**Comment by markharding** [comment]
Since iOS 9 I'm not able to get past 'checking this device...' - it then says 'There was a problem communicating with the PayPal services. Please try again'. Multiple devices.

Android is working fine with the same config.

**Comment by tomwhipple** [comment]
@markharding can you open this as a new issue? This one was opened about Android, and given the age, should be closed.

But please make sure you are using the latest SDK version and include any messages from the XCode/device console.
