### ISSUE TITLE
PayPalPayment not processable - iOS

### ISSUE THREAD

**Issue by ds8k** [paypal/PayPal-Cordova-Plugin#84]
Running into an issue only on iOS. I'm passing all the correct values, but the SDK is throwing this error:
```
PayPalPayment not processable: subtotal (42), tax ((null)), and shipping ((null)) do not sum to amount (46.73).
```

For some reason tax and shipping isn't getting set even though I've confirmed that I'm passing them correctly:
```
var createPayment = function() {
                var paymentDetails = new PayPalPaymentDetails(scope.totals.subTotal, scope.totals.shippingTotal, scope.totals.taxTotal);
                var payment = new PayPalPayment(scope.totals.grandTotal, "USD", "Purchase", "Sale", paymentDetails);
                return payment;
            };
```

I don't have this issue on Android

**Comment by ds8k** [comment]
It looks like the iOS SDK can only acceptable strings for values. Running toString() on them fixed the issue.

**Comment by romk1n** [comment]
@ds8k make sure you passing string. Check https://github.com/paypal/PayPal-Cordova-Plugin/blob/master/www/paypal-mobile-js-helper.js for documentation.

**Comment by juwlee** [comment]
Closing per @ds8k's last comment. Thanks @romk1n for the pointer to documentation.
