### ISSUE TITLE
Can't run on iOS 9

### ISSUE THREAD

**Issue by igormages** [paypal/PayPal-Cordova-Plugin#85]
Hi,
My app - and the sample cordova paypal app - can't run on iOS 9 : 
![capture d ecran 2015-06-22 a 01 00 53](https://cloud.githubusercontent.com/assets/1811772/8273738/2b4a3dec-187a-11e5-8dc8-07806c44cfec.png)

If i run in another phone on iOS 8 or the emulator, this works fine.

Someone know how to fix it ?
Thanks !

**Comment by romk1n** [comment]
@igormages unfortunately the information you have provided is not enough to determine the problem, do you have the full message from the log? Also bare in mind that iOS 9 support will only be available once [PayPalMobile iOS SDK](https://github.com/paypal/PayPal-iOS-SDK) adds it. Thanks.

**Comment by tomwhipple** [comment]
iOS 9 dependencies are https://github.com/paypal/PayPal-iOS-SDK/issues/290 and https://github.com/paypal/PayPal-iOS-SDK/issues/297.

**Comment by cihadhoruzoglu** [comment]
We have faced the same issue which is mentioned above. And we get following exception log;

> *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[NSTaggedPointerString getCharacters:range:]: Range {0, 7} out of bounds; string length 4'
*** First throw call stack:
(0x1838c8f5c 0x1984bbf80 0x1838c8ea4 0x1838b04e4 0x1837bb0d4 0x1838b0c90 0x1001cb804 0x183801124 0x1001cb550 0x1001cc0a8 0x1001b94d0 0x1001ba68c 0x1001a7a28 0x188e1f62c 0x188e1f1b0 0x1891ae84c 0x18916d750 0x18916a2b0 0x1890c8844 0x1890d4de4 0x188e111e4 0x18387fc30 0x18387d9d4 0x18387de04 0x1837acdc0 0x18e900088 0x188e86f60 0x100016e0c 0x198ce68b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by avidas** [comment]
@cihadhoruzoglu at what point was the exception thrown? Were you just trying to run the sample cordova app?

**Comment by jaypatel512** [comment]
Running the [sample app](https://github.com/romk1n/MyCordovaShop), on IPhone 6 Simulator (IOS 9), I was able to run the sample successfully. Can you give us more information on how to reproduce this issue ?

**Comment by cihadhoruzoglu** [comment]
Hi @avidas & @jaypatel512 ,

We have fixed this issue with upgrading the version of PayPal plugin on Xcode 7. Thanks.

**Comment by jaypatel512** [comment]
Thats wonderful !! Happy Coding :+1:
