### ISSUE TITLE
its giving me error "Cannot read property 'PayPalMobile' of undefined"

### ISSUE THREAD

**Issue by chumstech** [paypal/PayPal-Cordova-Plugin#88]
Hi,
 i used this plugin in android phonegap app but its giving me error "Cannot read property 'PayPalMobile' of undefined",
but i correctly configured the config.xml and manifest file .
can you please help me in this.

Thanks in Advance

**Comment by romk1n** [comment]
@chumstech can you provide more details please ? the only bit you need to do is add one line to your config.xml if you using Phonegap build https://github.com/paypal/PayPal-Cordova-Plugin#phonegap-build

Do you have sample code where this error is thrown and full console log?

**Comment by tomwhipple** [comment]
I'm not sure what action remains here, so I'm going to close this. Please feel free to reopen if the problem persists.
