### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by ds8k** [paypal/PayPal-Cordova-Plugin#90]
Android appears to have randomly started throwing a "JSON Error" on tap of the PayPal button. This was on 3.1.8. I updated to 3.1.9 assuming this might fix the problem but it still persists. I can't even get the UI to show up setting the environment to NoNetwork. Logcat doesn't even give me any more information about what's going on. I've literally not changed my code and it has gone from working fine to not at all.

iOS has no problems.

Here's the code:

This runs on Checkout init
```
          var ids = {
                PayPalEnvironmentProduction : 'REDACTED',
                PayPalEnvironmentSandbox : 'REDACTED'
          };

            PayPalMobile.init(ids, function() {
                var configuration = new PayPalConfiguration({
                    merchantName: "Test",
                    merchantPrivacyPolicyURL: "https://mytestshop.com/privacy",
                    payPalShippingAddressOption: 1,
                    acceptCreditCards: false
                });

                PayPalMobile.prepareToRender('PayPalEnvironmentSandbox', configuration);
            });
```

The above runs without issues.

Following runs when PayPal button is tapped:
```
          var scope = this,
                shippingAddress = new PayPalShippingAddress(scope.shippingAddress.recipientName, scope.shippingAddress.line1, scope.shippingAddress.line2, scope.shippingAddress.city, scope.shippingAddress.state, scope.shippingAddress.postalCode, scope.shippingAddress.countryCode);
                payment = new PayPalPayment(scope.totals.grandTotal.toString(), "USD", "Test Purchase", "Sale", null);

            payment.shippingAddress = shippingAddress;

            var onSuccesfulPayment = function(payment) {
                console.log(payment);
            };

            var onUserCanceled = function(result) {
                console.log(result);
            };

            PayPalMobile.renderSinglePaymentUI(payment, onSuccesfulPayment, onUserCanceled);
```

And all I get back is "JSON Error"

Running on Android 5.1

**Comment by romk1n** [comment]
@ds8k try putting some breakpoints, i don't see what can go wrong here and it is unclear what component sends the error. Also, since you using only single payment functionality you don't need to set 

`merchantName: "Test",
merchantPrivacyPolicyURL: "https://mytestshop.com/privacy",
`
it is required only for future payments and profile sharing.

**Comment by ds8k** [comment]
Thanks for the heads up.

It looks like the issue is passing in null for the paymentDetails. I originally left it out but could have sworn I got some error because of that. Looks like Android doesn't like when it's set to null, however if I don't pass anything in it works fine for both iOS and Android.
