### ISSUE TITLE
What is the merchantPrivacyPolicyURL and merchantUserAgreementURL?

### ISSUE THREAD

**Issue by arnoldbenda** [paypal/PayPal-Cordova-Plugin#92]
I am a beginner of programming.
I want to integrate paypal-cordova-plugin on my app.
By the way , I don't know what is the merchantPrivacyPolicyURL  and merchantUserAgreementURL.
Please help me.

**Comment by romk1n** [comment]
If you using future payments or profile sharing you must supply your privacy and agreement URL links.

**Comment by arnoldbenda** [comment]
Thank you for reply. 
I see.
