### ISSUE TITLE
Issue with IOS

### ISSUE THREAD

**Issue by tsukasa1989** [paypal/PayPal-Cordova-Plugin#94]
Hello,

I'm getting the following error when I'm building:

	Error: [xcode-build] Link /tmp/builds/ZUcH8JecJ4cbdIfWBJ/app/DerivedData/Cordova350/Build/Intermediates/Cordova350.build/Release-iphoneos/Cordova350.build/Objects-normal/armv7/Cordova350: Undefined symbols for architecture armv7:
     "_OBJC_CLASS_$_NSExtensionItem", referenced from:
      objc-class-ref in libPayPalMobile.a(PPZebraOnePasswordExtension.o)
     "_OBJC_CLASS_$_NSItemProvider", referenced from:
      objc-class-ref in libPayPalMobile.a(PPZebraOnePasswordExtension.o)
     "_kUTTypePropertyList", referenced from:
      -[PPZebraOnePasswordExtension processExtensionItem:completion:] in libPayPalMobile.a(PPZebraOnePasswordExtension.o)
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
	Error: [xcode-build] Link /tmp/builds/ZUcH8JecJ4cbdIfWBJ/app/DerivedData/Cordova350/Build/Intermediates/Cordova350.build/Release-iphoneos/Cordova350.build/Objects-normal/arm64/Cordova350: Undefined symbols for architecture arm64:
     "_OBJC_CLASS_$_NSExtensionItem", referenced from:
      objc-class-ref in libPayPalMobile.a(PPZebraOnePasswordExtension.o)
    "_OBJC_CLASS_$_NSItemProvider", referenced from:
      objc-class-ref in libPayPalMobile.a(PPZebraOnePasswordExtension.o)
     "_kUTTypePropertyList", referenced from:
      -[PPZebraOnePasswordExtension processExtensionItem:completion:] in libPayPalMobile.a(PPZebraOnePasswordExtension.o)
	ld: symbol(s) not found for architecture arm64
	clang: error: linker command failed with exit code 1 (use -v to see invocation)
		Error: 'Build failed with error code 2'

Any suggestions?

Thank you

**Comment by romk1n** [comment]
@tsukasa1989 are you using old version of Xcode ? https://github.com/paypal/PayPal-iOS-SDK/issues/190

**Comment by tsukasa1989** [comment]
I have found my issue, I was using an older version of phonegap. Now I've updated my version the error is gone.

**Comment by avidas** [comment]
@tsukasa1989 if you could report what version of phonegap you were using, that would be great.

**Comment by tsukasa1989** [comment]
Version 3.5, now i've updated to 3.7 and it does not give any issues.
