### ISSUE TITLE
Camera feature not showing after  app signed (Android)

### ISSUE THREAD

**Issue by Vincenttbk** [paypal/PayPal-Cordova-Plugin#95]
Hi,

The credit card scanning feature seems to be working on my development environment for a long time. But after signing the app in android, the camera function seems to be deactivated. 

Is there any special step i need to do in order for the camera function to work?

Thanks :)

Regards
Vincent

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.
